### ISSUE TITLE
net-sha1 format performance regression

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#3816] opened 2019-04-13 17:28 UTC
1.8.0-jumbo-1 `--disable-openmp`:

```
[solar@super run]$ ./john -test -form=net-sha1
Benchmarking: net-sha1, "Keyed SHA1" BFD [SHA1 32/64]... DONE
Many salts:     11419K c/s real, 11419K c/s virtual
Only one salt:  7704K c/s real, 7704K c/s virtual
```

Today's bleeding-jumbo `--disable-openmp`, `Benchmarks_1_8 = Y`:

```
[solar@super run]$ ./john -test -form=net-sha1
Benchmarking: net-sha1, "Keyed SHA1" BFD [SHA1 32/64]... DONE
Many salts:     9339K c/s real, 9339K c/s virtual
Only one salt:  7568K c/s real, 7568K c/s virtual
```

I haven't tried playing with `MAX_KEYS_PER_CRYPT` yet.

I haven't checked if the test vectors have possibly changed in a way causing this.

**Comment by solardiz** [comment] 2019-04-23 18:22
This looks related to #3814 because the net-sha1 format is implemented as a thin dynamic format.

Switching to new benchmarks doesn't significantly change performance. The regression is still there.

Playing with `MAX_KEYS_PER_CRYPT` is I think irrelevant - dynamic formats have their own logic for that. This format itself sets MKPC to 1, and it did before. It also sets OMP_SCALE to 2048, but then never uses that macro (a minor bug) - again, I hope the dynamics framework takes care of that scaling somehow?

The test vectors are unchanged.

**Comment by magnumripper** [comment] 2019-05-06 22:11
I believe this is just a dupe of #3814, closing.

**Closed by magnumripper** 2019-05-06 22:11 UTC
Labels: Regression
