### ISSUE TITLE
Some PuTTY format self tests missing

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#814] opened 2014-10-18 15:05 UTC
static struct custom_salt has 2 integers, is_mac and old_fmt.
Both of them influence how the hash is computed.
Both self tests, however, have is_mac set to 1 and old_fmt set to 0.

Does anybody know how to get valid hashes and their corresponding passwords for the other combinations of is_mac and old_fmt?
Otherwise we don't know whether the algorithm and/or putty2john really work correctly for those other combinations.

**Comment by kholia** [comment] 2017-09-28 08:04
https://www.chiark.greenend.org.uk/~sgtatham/putty/releases/0.52.html

Very old PuTTY version 0.52 (released on 2002-01-14) too has `is_mac` set to `1`. It should be reasonable to assume that keys with `old_fmt` set to `1` are very rare.

**Comment by kholia** [comment] 2017-09-28 08:10
![old-puttgen](https://user-images.githubusercontent.com/79528/30955606-cf2efb7c-a451-11e7-8c82-4ad1a24e5807.png)

We also don't support the `SSH1 (RSA)` keys it seems. It might be by design but I don't remember.

```
$ ../run/putty2john old-puttygen-ssh1-nopass 
old-puttygen-ssh1-nopass : this private key doesn't need a passphrase!

$ ../run/putty2john old-puttygen-ssh1-pass
old-puttygen-ssh1-pass : this private key doesn't need a passphrase!
```

This behavior is not great. We should instead say that `SSH1 private keys are not supported`.

**Comment by kholia** [comment] 2017-09-28 08:25
I don't see a practical way to solve this issue. Hence, I am closing it.

**Closed by kholia** 2017-09-28 08:25 UTC
Labels: enhancement, notes/external issues
