### ISSUE TITLE
./configure doesn't detect libbz2 correctly

### ISSUE THREAD

**Issue by zzlei** [magnumripper/JohnTheRipper#1772] opened 2015-09-21 07:38 UTC
When I cross-compile JtR for ARM, the output of ./configure says
```
Optional libraries/features found:
...
BZ2 (gpg2john extra decompression logic) ... yes
```
But in autoconfig.h there's no corresponding definition for `HAVE_LIBBZ2`, only:
```
/* Define to 1 if you have bz2 library and headers */
/* #undef HAVE_LIBBZ2 */
```

A direct consequence of that is a compiler warning for gpg2john.c:
```
gpg2john.c:2526:14: warning: ‘d_buf2’ defined but not used [-Wunused-variable]
```

**Comment by magnumripper** [comment] 2015-09-21 16:14
That's very odd. Check config.log for clues!

**Comment by zzlei** [comment] 2015-09-23 15:21
This issue is not specific to cross-compiling. I reproduced it on my Linux host with a single `./configure` (falsely detects libbz2).

I think this piece of code in configure.ac is suspicious:
```ac
if test "x$ac_cv_lib_bz2_main" != xno; then
   using_bz2=yes
else
   using_bz2=no
fi
```

Things behave sanely after changing it into
```ac
if test $ac_cv_lib_bz2_main = yes; then
   using_bz2=yes
else
   using_bz2=no
fi
```

The latter detects libbz2 correctly in my experimentation. I have no idea why the code was written in the former way. I also noticed quite a few snippets of code in configure.ac written in the same pattern; I doubt if they are correct at all.

**Comment by magnumripper** [comment] 2015-09-23 16:51
> I have no idea why the code was written in the former way. 

```
AC_CHECK_HEADER([bzlib.h], [AC_CHECK_LIB([bz2],[main],
configure.ac:                          AC_DEFINE([HAVE_LIBBZ2],1,[Define to 1 if you have bz2 library and headers]) [AC_SUBST(BZ2_LIBS, [-lbz2])])])
```
The x's are usually added to protect from empty strings ending up in incorrect syntax (eg. `test  != no`) in case the $ac_cv_lib_bz2_main is undefined (when the header wasn't found AC_CHECK_LIB is not called at all). Not sure why it ends up wrong here. Can you try printing the actual string in $ac_cv_lib_bz2_main?

**Comment by jfoug** [comment] 2015-09-23 16:58
It is wrong because it is  "x$var" != xno      It should be "x$var" = xyes

**Comment by magnumripper** [comment] 2015-09-23 18:43
@jfoug will you change it or should I?

**Comment by jfoug** [comment] 2015-09-23 18:54
I am tied up at work right now.

HOWEVER, every time we need to KNOW the answer to one of these logic questions (i.e. when we get down to USING that knowledge), we should do so with:     ```if "x$var" = xyes```       Only when we are digging deeper (probing), should we be using the ```if "x$var" != xno```   In that case, we execute the code unless we have been told NOT to, or unless an prior probe has already fully determined that the condition can never be valid on this machine.

Part of the problem is that some of our probes are not 100% in depth. Thus, we have cases where our detection variables are not set to yes or no in the end.  We should try to find these cases and fix them to make sure that things are FULLY defined in the end of the script.  BUT we should never depend upon $var!=no as meaning that $var=yes

Like has been mentioned, I bet we have more than one case where we need to use the knowledge of something being ON the system, and are doing it using the != no method.

**Comment by jfoug** [comment] 2015-09-23 18:56
It would be a good 'test', to get this changed for the bz2, and make sure this problem goes away.  Knowing that things are REALLY fully cleaned up will  not be easy, since 'it works on my system' makes it so the config script works right.  ONLY when run on a system where something is not installed, would these items get caught.  Since @zzlei has such a situation right now, we can know when THIS instance is fixed, and once we know that, we can look for any other generalization of the problem in the rest of the configure.ac file (or any of the m4 files).

**Comment by magnumripper** [comment] 2015-09-23 19:14
Fixed in bc0be4a. Since @zzlei already tested practically the same solution, I'm closing this.

**Closed by magnumripper** 2015-09-23 19:14 UTC

**Comment by magnumripper** [comment] 2015-09-26 00:48
Funny, I now know I missed bz2 on a lot of the hosts I use - I thought I had it. OTOH it's not used very much.

**Comment by zzlei** [comment] 2015-09-26 03:41
> I never got that gpg2john warning though.

I think this warning is emitted only when both libbz2 and libz are absent.
