### ISSUE TITLE
./jtrts.pl errors on Raspberry Pi 2: Cannot allocate memory trying to allocate 1073741824 bytes

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1872] opened 2015-10-31 23:13 UTC
```
./jtrts.pl 
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper 1.8.0.6-jumbo-1-1547-gf864eba OMP [linux-gnueabihf 32-bit NEON-ac]
--------------------------------------------------------------------------------

John Jumbo build detected.

form=dynamic_0                    guesses: 1502 0:00:00:00 DONE  [PASSED]
mem_alloc(): Cannot allocate memory trying to allocate 1073741824 bytes
.pot CHK:dynamic_0                guesses:    0 -show=   0 N/A N/A : Expected count(s) (1500)  [!!!FAILED6!!! exited, return code 1]

form=dynamic_0                    guesses:  920 0:00:00:00 DONE  [PASSED]
mem_alloc(): Cannot allocate memory trying to allocate 1073741824 bytes
.pot CHK:dynamic_0                guesses:    0 -show=   0 N/A N/A : Expected count(s) (1500)  [!!!FAILED6!!! exited, return code 1]

form=dynamic_0                    guesses: 1500 0:00:00:00 DONE  [PASSED]
mem_alloc(): Cannot allocate memory trying to allocate 1073741824 bytes
.pot CHK:dynamic_0                guesses:    0 -show=   0 N/A N/A : Expected count(s) (1500)  [!!!FAILED6!!! exited, return code 1]

form=dynamic_0-raw                guesses: 1500 0:00:00:00 DONE  [PASSED]
mem_alloc(): Cannot allocate memory trying to allocate 1073741824 bytes
.pot CHK:dynamic_0-raw            guesses:    0 -show=   0 N/A N/A : Expected count(s) (1500)  [!!!FAILED6!!! exited, return code 1]

form=dynamic_1                    guesses: 1500 0:00:00:02 DONE  [PASSED]
mem_alloc(): Cannot allocate memory trying to allocate 1073741824 bytes
.pot CHK:dynamic_1                guesses:    0 -show=   0 N/A N/A : Expected count(s) (1500)  [!!!FAILED6!!! exited, return code 1]
^C
```

```
./jtrts.pl -type saph
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper 1.8.0.6-jumbo-1-1547-gf864eba OMP [linux-gnueabihf 32-bit NEON-ac]
--------------------------------------------------------------------------------

John Jumbo build detected.

form=saph-sha1                    guesses: 1500 0:00:00:00 DONE  [PASSED]
mem_alloc(): Cannot allocate memory trying to allocate 1073741824 bytes
.pot CHK:saph-sha1                guesses:    0 -show=   0 N/A N/A : Expected count(s) (1500)  [!!!FAILED6!!! exited, return code 1]
```

Not even `--save-memory=3` helps:

```
$ ./jtrts.pl -passthru="--save-memory=3"
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper 1.8.0.6-jumbo-1-1547-gf864eba OMP [linux-gnueabihf 32-bit NEON-ac]
--------------------------------------------------------------------------------

John Jumbo build detected.

form=dynamic_0                    guesses: 1502 0:00:00:00 DONE  [PASSED]
mem_alloc(): Cannot allocate memory trying to allocate 1073741824 bytes
.pot CHK:dynamic_0                guesses:    0 -show=   0 N/A N/A : Expected count(s) (1500)  [!!!FAILED6!!! exited, return code 1]

form=dynamic_0                    guesses:  920 0:00:00:00 DONE  [PASSED]
mem_alloc(): Cannot allocate memory trying to allocate 1073741824 bytes
.pot CHK:dynamic_0                guesses:    0 -show=   0 N/A N/A : Expected count(s) (1500)  [!!!FAILED6!!! exited, return code 1]
```

**Comment by priorityinterrupt** [comment] 2015-10-31 23:46
Im nto a dev and Im not sure what the expected behavior should be. Should this detect the max amount of memory and not try to exceed it?

But since its trying to allocate 1GB and the RPI2 only has 1GB with 64MB dedicated to the GPU (possibly more) it makes sense it cannot allocate 1GB. 

You can set the amount dedicated to the GPU using raspi-config under Advanced Options -> Memory Split.

Could this be the problem?

**Comment by frank-dittrich** [comment] 2015-10-31 23:48
Apparently, `./john --show` is allocating too much memory, even for tests with just a few hashes (rar).

**Comment by magnumripper** [comment] 2015-11-01 01:18
@frank-dittrich please run a -show manually and try to establish where we're trying to allocate that much memory. It doesn't make sense.

I can't recall we bumped anything relevant other than SALT_HASH_LOG and that shouldn't be a problem (or is it?). No, wait, Solar bumped CRACKED_HASH_LOG in 33aaaeba. I bet that's the problem.

**Comment by magnumripper** [comment] 2015-11-01 01:26
My 64-bit build only allocates 256 MB from the CRACKED_HASH_LOG and it should be even less for a 32-bit build, so that's probably not it (at least not by itself).

**Comment by magnumripper** [comment] 2015-11-01 01:47
I enabled memdbg and added a print of allocated memory, and max use during `../run/john -show ../test/dynamic_0_tst.in` is only 269,862,332 bytes. So is this something specific to ARM? A bug? Another problem with assuming signed char?

**Comment by frank-dittrich** [comment] 2015-11-01 23:22
unique is the culprit, not john!

```
 $ ./jtrts.pl -v -v -v -stoponerror
[...]
u1498-dynamic_0:good to KN0W__17:1498:0:good to KN0W__17::
u1499-dynamic_0:1__18:1499:0:1__18::

1502 password hashes cracked, 0 left



d_show_line = 
1502 password hashes cracked, 0 left

form=dynamic_0                    guesses: 1502 0:00:00:00 DONE  [PASSED]
mem_alloc(): Cannot allocate memory trying to allocate 1073741824 bytes
Execute john (.pot check): ../run/john -ses=tst-  -pot=tst-.pot tst-tst.in --wordlist=tst-pw3 -form=dynamic_0 2>_stderr 2>_stderr


Cmd_data = 
Loaded 1500 password hashes with no different salts (dynamic_0 [md5($p) (raw-md5) 32/32 x2])
fopen64: tst-pw3: No such file or directory


Execute john: ../run/john -show   -pot=tst-.pot dynamic_0_tst.in -form=dynamic_0 2>&1


Cmd_show_data2 = 
0 password hashes cracked, 1502 left



d_show_line2 = 
0 password hashes cracked, 1502 left
0 invalid passwords
0 valid passwords

.pot CHK:dynamic_0                guesses:    0 -show=   0 N/A N/A : Expected count(s) (1500)  [!!!FAILED6!!! exited, return code 1]
Exiting on error. The .pot file tst-.pot contains the found data
The command used to run this test was:

../run/john -ses=tst-  -pot=tst-.pot dynamic_0_tst.in --wordlist=pw.dic -form=dynamic_0
```

I guess `unique` is allocating that much memory, that's why tst-pw3 doesn't exist.


```
my $cmd2 = sprintf("cut -f 2- -d: -s < $pot | $UNIQUE tst-pw3 > /dev/null");
```



```
$ echo test | ../run/unique test.test
mem_alloc(): Cannot allocate memory trying to allocate 1073741824 bytes
```

**Comment by magnumripper** [comment] 2015-11-02 00:00
Oh lulz, that's 199561f85. The default can be overridden with -mem but I think I'll rewrite jtrts.pl not to use unique at all, there's no need to use external programs for that given Perl's excellent hash speed. I'm closing this and opening one for JtrTestSuite.

**Closed by magnumripper** 2015-11-02 00:00 UTC
