### ISSUE TITLE
OpenCL sha512crypt is failing on OSX

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#3234] opened 2018-04-21 05:11 UTC
See: http://www.openwall.com/lists/john-dev/2018/04/19/1

```
./john -test -format:sha512crypt-opencl -devices=2
Device 2: AMD Radeon RX 580 Compute Engine

Benchmarking: sha512crypt-opencl, crypt(3) $6$ (rounds=5000) [SHA512 OpenCL]... Options used: -I /Users/emwinkler/Desktop/JohnTheRipper/run/kernels -cl-mad-enable -D__OS_X__ -D__GPU__ -DDEVICE_INFO=10 -DSIZEOF_SIZE_T=8 -DDEV_VER_MAJOR=1 -DDEV_VER_MINOR=2 -D_OPENCL_COMPILER  $JOHN/kernels/cryptsha512_kernel_GPU.cl
Build log: <program source>:164:16: error: call to 'bitselect' is ambiguous
    w_vector = SWAP64_V(w_vector);
               ^~~~~~~~~~~~~~~~~~
/Users/emwinkler/Desktop/JohnTheRipper/run/kernels/opencl_sha512.h:33:33: note: expanded from macro 'SWAP64_V'
#define SWAP64_V(n)             SWAP64(n)
                                ^~~~~~~~~
/Users/emwinkler/Desktop/JohnTheRipper/run/kernels/opencl_misc.h:182:3: note: expanded from macro 'SWAP64'
                bitselect(rotate(n, 24UL), \
  ^~~~~~~~~
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:5254:22: note: candidate function
ulong16 __OVERLOAD__ bitselect( ulong16 x, ulong16 y, long16 m);
                     ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:5302:22: note: candidate function
ulong16 __OVERLOAD__ bitselect( ulong16 x, ulong16 y, ulong16 m);
```

Strange that the compiler supposes that data can be long or ulong.
My fix (testing on super).
```
diff --git a/src/opencl/cryptsha512_kernel_GPU.cl b/src/opencl/cryptsha512_kernel_GPU.cl
index d03b7b6ac..b4c459044 100644
--- a/src/opencl/cryptsha512_kernel_GPU.cl
+++ b/src/opencl/cryptsha512_kernel_GPU.cl
@@ -13,7 +13,7 @@
 
 #include "opencl_sha512crypt.h"
 
-#if (gpu_amd(DEVICE_INFO) && DEV_VER_MAJOR < 1729)
+#if (gpu_amd(DEVICE_INFO) && DEV_VER_MAJOR < 1729 && !defined(__OS_X__))
     #define VECTOR_USAGE    1
 #endif
```

**Comment by magnumripper** [comment] 2018-04-21 09:15
Silly bug, I've seen it before on macOS. Nothing is actually ambiguous but the compiler is confused. I can reproduce but can't find any workaround other than the one you suggested. It almost looks like `ulong16 __OVERLOAD__ bitselect( ulong16 x, ulong16 y, ulong m);` is missing!

With your fix, I get a fail on my GPU anyway though
```
Device 2: AMD Radeon Pro 560 Compute Engine
Benchmarking: sha512crypt-opencl, crypt(3) $6$ (rounds=5000) [SHA512 OpenCL]... FAILED (cmp_all(1))
```
Just the usual macOS driver bugs I'm afraid..

**Comment by magnumripper** [comment] 2018-04-21 09:32
> It almost looks like `ulong16 __OVERLOAD__ bitselect( ulong16 x, ulong16 y, ulong m);` is missing!

This is actually the problem! And `ulong16 __OVERLOAD__ bitselect( ulong16 x, ulong16 y, long m);` is missing too.

**Comment by magnumripper** [comment] 2018-04-21 12:35
@claudioandre I committed your fix. Will look into working around the rest in #3235.

**Closed by magnumripper** 2018-04-21 12:35 UTC
Labels: notes/external issues, portability

**Comment by claudioandre** [comment] 2018-04-21 16:28
> With your fix, I get a fail on my GPU anyway though (my old MBPr died so I have a new one with AMD GPU)

@magnumripper, could you try this?
```
diff --git a/src/opencl/cryptsha512_kernel_GPU.cl b/src/opencl/cryptsha512_kernel_GPU.cl
index d03b7b6ac..bf3c09a78 100644
--- a/src/opencl/cryptsha512_kernel_GPU.cl
+++ b/src/opencl/cryptsha512_kernel_GPU.cl
@@ -30,7 +30,7 @@
     #elif nvidia_sm_5x(DEVICE_INFO)
         #define UNROLL_LOOP    33686536
     #else
-        #define UNROLL_LOOP    0
+        #define UNROLL_LOOP    132098
     #endif
 #endif

```

Or (maybe using a noisy verb=5, if you want to feel the stuff running)
```
rm ../run/kernels/*.bin; _CALIBRATE=1 ../run/john -dev=2 -test -form=sha512crypt-opencl -verb=4
```

**Comment by magnumripper** [comment] 2018-04-21 19:41
That change somehow re-introduces the fail:
```
$ make -sj4 && _CALIBRATE=1 ../run/john -dev=2 -test -form=sha512crypt-opencl 

Make process completed.
Device 2: AMD Radeon Pro 560 Compute Engine
Benchmarking: sha512crypt-opencl, crypt(3) $6$ (rounds=5000) [SHA512 OpenCL]... Calibration is trying to figure out the best configuration to use at runtime. Please, wait...
Options used: -I /Users/magnum/src/john/run/kernels -cl-mad-enable -D__OS_X__ -D__GPU__ -DDEVICE_INFO=10 -DSIZEOF_SIZE_T=8 -DDEV_VER_MAJOR=1 -DDEV_VER_MINOR=2 -D_OPENCL_COMPILER -DUNROLL_LOOP=33686018 $JOHN/kernels/cryptsha512_kernel_GPU.cl
Build log: <program source>:164:16: error: call to 'bitselect' is ambiguous
    w_vector = SWAP64_V((ulong16)w_vector);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/magnum/src/john/run/kernels/opencl_sha512.h:33:33: note: expanded from macro 'SWAP64_V'
#define SWAP64_V(n)             SWAP64(n)
                                ^~~~~~~~~
/Users/magnum/src/john/run/kernels/opencl_misc.h:186:3: note: expanded from macro 'SWAP64'
                bitselect(rotate(n, 24UL), \
  ^~~~~~~~~
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:5254:22: note: candidate function
ulong16 __OVERLOAD__ bitselect( ulong16 x, ulong16 y, long16 m);
                     ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:5302:22: note: candidate function
ulong16 __OVERLOAD__ bitselect( ulong16 x, ulong16 y, ulong16 m);
                     ^

Error -11 building kernel $JOHN/kernels/cryptsha512_kernel_GPU.cl. DEVICE_INFO=10
OpenCL CL_BUILD_PROGRAM_FAILURE (-11) error in opencl_common.c:1168 - clBuildProgram failed.
```

**Comment by magnumripper** [comment] 2018-04-21 19:44
No wait, it's `_CALIBRATE=1` that re-introduces the build error. Without it, it just fails as before:
```
$ make -sj4 && ../run/john -dev=2 -test -form=sha512crypt-opencl 

Make process completed.
Device 2: AMD Radeon Pro 560 Compute Engine
Benchmarking: sha512crypt-opencl, crypt(3) $6$ (rounds=5000) [SHA512 OpenCL]... FAILED (cmp_all(1))
```

**Comment by claudioandre** [comment] 2018-04-21 19:47
Yes, `_CALIBRATE=1` will reintroduce the error at some testings (using at line 37).

```
#if (UNROLL_LOOP & (1 << 25))
    #define VECTOR_USAGE    1
#endif
```

**Comment by claudioandre** [comment] 2018-04-21 19:53
This is a kind of hopeless without debugging.

You can also try the "value" for old AMDs.
`#define UNROLL_LOOP    133128`

And introduce other code paths, like
`#define NVIDIA_UNROLL_BUG_1    1`

Or (not AND)
`#define AMD_UNROLL_BUG_1    1`

**Comment by magnumripper** [comment] 2018-04-21 20:03
Tried that and more, none of it helped.
