### ISSUE TITLE
"sorry, SSE4.1 required for this build" on VM

### ISSUE THREAD

**Issue by kost123** [magnumripper/JohnTheRipper#2089] opened 2016-03-15 08:53 UTC
I am using virtualbox running kali, I am getting that error.

I have an i5 CPU.

Whats up?

**Comment by ukasz** [comment] 2016-03-15 11:34
cat /proc/cpuinfo - likely there is no SSE4.1 on guest so you won't be able to use it. Does it build after that error?

**Comment by frank-dittrich** [comment] 2016-03-15 12:16
To me the error looks like trying to run an SSE 4.1 build of john (apparently built outside of that VM) in a VM that doesn't support SSE 4.1.

`. /configure && make -s clean && make -s` inside the VM should produce a binary without SSE 4.1.
JUst a few formats which require SSE 4.1 will not be included.

**Comment by magnumripper** [comment] 2016-03-15 13:33
I'm pretty sure this is a dupe of #1986, which is a bug in VirtualBox, not JtR.

**Comment by magnumripper** [comment] 2016-03-15 13:34
VirtualBox 5.0.10 r104061 was reported to work better.

**Comment by jfoug** [comment] 2016-09-09 21:11
Found this one.  The problem is in old core code! My method (which Solor hates), works like a F'n champ, but the legacy cpuid checking crap in x86.S sux.

The work around (for now), is to simply set   ```export CPUID_DISABLE=1``` prior to running john in the VM.   Then the CPUID checking code will be skipped.   NOTE, only do that if the program was build using the configure script, since it 'properly' checks for CPU extensions by blindly running code, and if the code does not crash, then that extension IS valid on the machine.

**Comment by magnumripper** [comment] 2016-09-19 20:09
OK but why reopen this? Do you intend to do any more work with it than that note? I regard it a bug in VirtualBox and that's about it.

**Comment by jfoug** [comment] 2016-09-19 21:04
It can be closed.  I was looking at doing work, BUT it is obvious that this is bugs in VB interface, as far as the recommended probing goes.  There were 2 types of probing listed in the intel specs. One uses the cpuid, and the other does what I do in the configure script. Well the dox lists to setup exception handlers, and then run the commands.  I simply do it by building a process that ONLY does the command and then returns 0.  But same concept.

So what is built by ./configure IS right, it knows what commands run properly.   But VBox is causing certain 'subsets' of functionality to not be present in the CPUID checks.   Likely those subfunctions within the AVX2/XOP are not working, BUT it is nothing used by john.    I am not overly worried about this, now that I know 'how' to make the native built process run on a buggy VBox instance.

**Closed by jfoug** 2016-09-19 21:04 UTC
Labels: core John (master branch), notes/external issues

**Comment by jfoug** [comment] 2016-09-19 21:07
I was actually looking for ways to detect when we were running under VBox.  There is no safe/generic way to do that.  Especially, since there are ways to 'hide' the few techniques to detect, and some of the users we would be targeting may take those form of steps to hide the fact their processes are VM bound.
