### ISSUE TITLE
dynamic_1026 doesn't load full-size hashes

### ISSUE THREAD

**Issue by AlbertVeli** [magnumripper/JohnTheRipper#3319] opened 2018-07-23 17:17 UTC
### Steps to reproduce ###
./john --list=subformats
...
UserFormat = dynamic_1026  type = dynamic_1026: sha1(sha1($p))

   ./john --format:dynamic_1026 ...

doesn't load any hashes. Although:

   ./john --format:dynamic='sha1(sha1($p))' ...

does work and both loads and cracks the hash as it should.
I think it might be a bug that dynamic_1026 doesn't work.

### System configuration ###
Tested on latest bleeding-jumbo 23 July 2018 built from source. OS X.

**Comment by magnumripper** [comment] 2018-07-23 22:04
Since dynamic ad-hoc format worked I'm guessing he used bare (untagged) hashes. That should work (given either `--format=dynamic_xx` or `--bare-always-valid=Y`).
```
$ echo > test.in 71b37a2d9b0a7d5dc4da8a08d9092817
$ echo >> test.in 30f8cf133eaac8e3b6af4bcba722921d
$ ../run/john -form:dynamic_1026 test.in
Using default input encoding: UTF-8
Loaded 2 password hashes with no different salts (dynamic_1026 [sha1(sha1($p)) (hash truncated to length 32) 256/256 AVX2 8x1])
(...)
```
...OK I just tried that and it works for me (on macOS even). So let's try with logins as well
```
$ echo > test.in user1:71b37a2d9b0a7d5dc4da8a08d9092817
$ echo >> test.in user2:30f8cf133eaac8e3b6af4bcba722921d
$ ../run/john -form:dynamic_1026 test.in
Using default input encoding: UTF-8
Loaded 2 password hashes with no different salts (dynamic_1026 [sha1(sha1($p)) (hash truncated to length 32) 256/256 AVX2 8x1])
(...)
```
That works fine as well. Not sure why it doesn't work for you @AlbertVeli ?

**Comment by magnumripper** [comment] 2018-07-26 09:15
> Loaded 2 password hashes with no different salts (dynamic_1026 [sha1(sha1($p)) (**hash truncated to length 32**) 256/256 AVX2 8x1])

Perhaps this is the problem. Both me and @claudioandre-br used 32-byte truncated hashes above:
```
$ echo > test.in abcdef0971b37a2d9b0a7d5dc4da8a08d9092817  # That's a full 40 bytes
magnum@mbpr:src [bleeding-jumbo]$ ../run/john -form:dynamic_1026 test.in
Using default input encoding: UTF-8
No password hashes loaded (see FAQ)
```
The dynamic_1026 format doesn't only *use* 32 of the 40 bytes, it also don't accept any longer. I'm not sure whether that's a bug or not.

**Comment by AlbertVeli** [comment] 2018-07-27 12:34
Oh, I didn't get any notifications about new comments. Didn't see this until now. Example hash (password = albert):

5dd2738c3dacabdc2e6ece6b22ef4f52e07da6af

As you said it is probably this 32 vs 40 bytes problem. I just wanted to try out a normal "double sha1" for a hash in a CTF competition where the format was not given so some guessing was needed.

**Comment by magnumripper** [comment] 2018-08-01 21:06
Ok so the problem is this format not only just considers 128 bits out of 160, it doesn't even recognize 160-bit hashes. I suspect it's working as intended though - the algorithm name says "hash truncated to length 32".

We could probably add some `prepare()` magic to "fix" this but since @jfoug isn't active here right now, I'm just gonna close this for now.

**Closed by magnumripper** 2018-08-01 21:06 UTC
Labels: RFC / discussion
