### ISSUE TITLE
--max-run-time and --fork

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#2757] opened 2017-09-15 08:32 UTC
Sometimes, I don't see a final status line for each forked process when running john with --fork and --max-run-time.
```
$ ./john raw-sha1-ng --fork=4 --format=raw-sha1-ng --nolog --max-run-time=4
Using default input encoding: UTF-8
Loaded 1 password hash (Raw-SHA1-ng, (pwlen <= 15) [SHA1 128/128 AVX 4x])
Node numbers 1-4 of 4 (fork)
Press 'q' or Ctrl-C to abort, almost any other key for status
1 0g 0:00:00:04  3/3 0g/s 5738Kp/s 5738Kc/s 5738KC/s 2poce6..2poy6m
Waiting for 3 children to terminate
Session stopped (max run-time reached)
```
But sometimes I see status lines of 3 or 4 processes (4 would be expected):
```
$ ./john raw-sha1-ng --fork=4 --format=raw-sha1-ng --nolog --max-run-time=4
Using default input encoding: UTF-8
Loaded 1 password hash (Raw-SHA1-ng, (pwlen <= 15) [SHA1 128/128 AVX 4x])
Node numbers 1-4 of 4 (fork)
Press 'q' or Ctrl-C to abort, almost any other key for status
2 0g 0:00:00:04  3/3 0g/s 8414Kp/s 8414Kc/s 8414KC/s 00c6ak..00des!
4 0g 0:00:00:04  3/3 0g/s 8555Kp/s 8555Kc/s 8555KC/s jugmpc..jupbc3
1 0g 0:00:00:04  3/3 0g/s 8985Kp/s 8985Kc/s 8985KC/s tmsaii2..tms31az
Waiting for 3 children to terminate
```

```
$ ./john raw-sha1-ng --fork=4 --format=raw-sha1-ng --nolog --max-run-time=4
Using default input encoding: UTF-8
Loaded 1 password hash (Raw-SHA1-ng, (pwlen <= 15) [SHA1 128/128 AVX 4x])
Node numbers 1-4 of 4 (fork)
Press 'q' or Ctrl-C to abort, almost any other key for status
3 0g 0:00:00:04  3/3 0g/s 8212Kp/s 8212Kc/s 8212KC/s rb14ko..rb2buk
4 0g 0:00:00:04  3/3 0g/s 8511Kp/s 8511Kc/s 8511KC/s bucz8w..bufgnt
2 0g 0:00:00:04  3/3 0g/s 8338Kp/s 8338Kc/s 8338KC/s mabn0g..mafhex
1 0g 0:00:00:04  3/3 0g/s 8973Kp/s 8973Kc/s 8973KC/s tmopy3...tmolang
```

I don't think I'll be able to bisect, since the problem isn't reproducable reliably.

I am afraid it is not just some cosmetic problem, because in longer runs (--max-run-time=600) with millions of hashes, ./john --status reported 10:01 run time for 1 or 2 of the forked processes, and 09:01 for the other forked processes.

**Comment by magnumripper** [comment] 2017-09-15 08:53
john.conf
```
# This sets the "grace time" for --max-run-time=N. If john has not finished
# this long after the initial abort signal, it will send another one (similar
# to pressing ctrl-c a second time) which will stop john immediately and not
# wait further for an optimal resume point.
# Setting this to 0 means NO grace time - immediately abort. Setting it to
# a negative number means UNLIMITED grace time - never hard abort.
AbortGraceTime = 30
```
I would guess this is what you see. Not a bug.

**Comment by frank-dittrich** [comment] 2017-09-15 08:59
I guess it is not AbortGraceTime.
I haven't redefined it, so it is still 30 seconds. But stopping john due to --max-run-time takes about a second, as far as I can see.
Can I increase verbosity, or drop --nolog, to see if a process has been killed due to  AbortGraceTime?

```
$ time ./john raw-sha1-ng --fork=4 --format=raw-sha1-ng --nolog --max-run-time=1
Using default input encoding: UTF-8
Loaded 1 password hash (Raw-SHA1-ng, (pwlen <= 15) [SHA1 128/128 AVX 4x])
Node numbers 1-4 of 4 (fork)
Press 'q' or Ctrl-C to abort, almost any other key for status
1 0g 0:00:00:01  3/3 0g/s 2942Kp/s 2942Kc/s 2942KC/s r176225..0920011123
Waiting for 3 children to terminate
Session stopped (max run-time reached)

real	0m1.167s
user	0m4.124s
sys	0m0.352s
```

**Comment by magnumripper** [comment] 2017-09-15 09:01
You probably need to add debug output in signals.c to see what's happening.

**Comment by frank-dittrich** [comment] 2017-09-15 09:30
I did try `git bisect` instead, just assuming a good commit when more than 10 repeated tests didn't show the problem.

This is the result:
```
commit 0168a45a145d3c3ff714dd9f6bf73128f5408bac
Author: magnum <john.magnum@hushmail.com>
Date:   Tue May 16 10:54:15 2017 +0200

    Don't start "the clock" until all loading, auto-tune etc. are done. This
    ensures stable speed readings from start, and things like --progress-every
    and --max-run-time will work better.

```

**Comment by frank-dittrich** [comment] 2017-09-15 09:44
BTW:
Sometimes, there isn't even a single status line:
```
Using default input encoding: UTF-8
Loaded 1 password hash (Raw-SHA1-ng, (pwlen <= 15) [SHA1 128/128 AVX 4x])
Node numbers 1-4 of 4 (fork)
Press 'q' or Ctrl-C to abort, almost any other key for status
Session stopped (max run-time reached)
```

And setting ` AbortGraceTime = 0` doesn't help, either.

**Comment by frank-dittrich** [comment] 2017-09-15 09:51
I didn't see any problem with --progress-every.
And pressing q or 1^C instead of using --max-run-time also works.

**Comment by magnumripper** [comment] 2017-09-15 10:20
Try this
```diff
diff --git a/src/signals.c b/src/signals.c
index 2e3bcd75a..702514d9a 100644
--- a/src/signals.c
+++ b/src/signals.c
@@ -209,7 +209,7 @@ static void sig_handle_abort(int signum)
        int saved_errno = errno;
 
 #if OS_FORK
-	if (john_main_process) {
+	if (john_main_process && !aborted_by_timer) {
 /*
  * We assume that our children are running on the same tty with us, so if we
  * receive a SIGINT they probably do as well without us needing to forward the
```

**Comment by magnumripper** [comment] 2017-09-15 10:25
That looks like it. I committed it in 058d1bdd0.

**Comment by frank-dittrich** [comment] 2017-09-15 10:26
I just confirmed this change fixed the problem for me. Thanks!

**Closed** 2017-09-15 10:31 UTC
Labels: bug
