### ISSUE TITLE
gpg-opencl speed improvements

### ISSUE THREAD

**Issue by ukasz** [magnumripper/JohnTheRipper#332] opened 2013-06-12 20:46 UTC
Current code is non gpu friendly:
basic things to do:
-remove HUGE buffers
-use preprocessed values for LCM(64,passlength) //minor impact
-internal loop can be simplified

**Comment by magnumripper** [comment] 2015-03-19 16:53
I have a lot leaner code now, regression testing.

**Comment by magnumripper** [comment] 2015-03-19 19:12
b98f514c introduced an (optional) KISS code, which was just slow but easier to understand.
efa03b63 changed it to optional lean code that does use a buffer but only a couple hundred bytes instead of 8.5 KB. This is a lot faster on many GPUs.
Many nvidias has some weird problem with the lean code (crashes, very likely compiler bug) so cfe24b6a disables it for all nvidias and revert to the original (well very trimmed from the original) code. CPUs also use that code path as they get slower with the lean one.

Still work in progress.

**Comment by kholia** [comment] 2017-06-24 11:38
[Here is a paper from 2011 on GPG cracking](https://github.com/magnumripper/JohnTheRipper/files/1099640/milo2011.pdf). Maybe we can reuse some techniques from this paper?

**Comment by claudioandre-br** [comment] 2018-12-15 18:37
I skipped issues like this. But, it is clear that:

* **Low Priority** - They have a tendency to become high priority if enough of the users complain.

* **Business Priority** - Obsolete hardware and software. Hardware nobody owns, etc.

* **WontFix** - Covers all the reasons we chose to close the bug without taking action.
  * Nobody cares (5 years).

**Comment by magnumripper** [comment] 2018-12-15 19:45
It also looks like most of the problems were fixed (although I can't remember really)

**Closed** 2018-12-15 20:03 UTC
Labels: enhancement
