### ISSUE TITLE
BFegg TS error

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1069] opened 2015-03-03 13:06 UTC
I get this error for about 3 out of 4 test runs:

```
(master)test $ ./jtrts.pl -v -stoponerror -passthru="--fork=2" -type bfegg
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.2-jumbo-1-bleeding_omp_memdbg-ex_asan [linux-gnu 64-bit AVX-autoconf]
--------------------------------------------------------------------------------

John Jumbo build detected.
--pot=NAME option is valid
--encoding=NAME option is valid
all.chr (../run/all.chr) not found
alnum.chr found, inc_alnum_ee8763c850dee8e4b88ef547a8ed39b8 added as a capability
Types to filter on:
bfegg
Capabilities in this build of john:
jumbo core inc local_pot_valid encode_valid utf8 cp1252 cp1251 koi8r cp437 cp737 cp850 cp858 cp866 iso8859-1 iso8859-15 inc_alnum_ee8763c850dee8e4b88ef547a8ed39b8

form=BFegg                        guesses: 1500 0:00:00:00 DONE  [PASSED]
FAILED line = 1                (11)
.pot CHK:BFegg                    guesses: 1501 -show=1500 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED4!!!]  (1500 val-pwd  1 inval-pwd)
Exiting on error. The .pot file ./tst.pot contains the found data
The command used to run this test was:

../run/john -ses=./tst  --fork=2 -pot=./tst.pot BFegg_tst.in --wordlist=pw.dic -form=bfegg
```

**Comment by magnumripper** [comment] 2015-03-03 13:27
I believe this is a dupe of #1045

**Comment by jfoug** [comment] 2015-03-03 14:31
It may be, but it could also be interaction between memdbg mode that does NOT flush screen, and -fork, causing lines that have characteristics of  a password output line.  It shows 1501 guesses with 1 invalid.  In #1045 there were no invalids. There were passwords cracked with multiple 'correct' passwords I thought, but not incorrect ones.  I guess it 'could' be that there is some word dupe (or that triggers this), just beyond the 1500 level that is found, that is not in the list, while some other thread gets the one we know about.

**Comment by jfoug** [comment] 2015-03-03 18:17
Nope, this is from 1045.  The password found was 11, not 1   But 1 and 11 are identical for this format.

This addition (in the -v mode), tells me all I need to know (once I remembered it).

```
FAILED line = 1                (11)
```

**Closed by jfoug** 2015-03-03 18:17 UTC

**Comment by jfoug** [comment] 2015-03-03 18:18
This is just an SOB format, when it comes to the TS.  We may have to make a special dictionary which does not have any dupes for this format.  But it is such an insignificant format, that I really do not care.
