### ISSUE TITLE
MinGW builds do not run at all on Windows 10

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2190] opened 2016-07-29 09:08 UTC
Running john.exe exits with "The application was unable to start correctly (0xc0000142)" error message on Windows 10 64-bit.

**Comment by jfoug** [comment] 2016-07-29 12:01
This only happens on the cross compiles.  'native' mingw on win32 builds and runs fine (I think).

**Comment by magnumripper** [comment] 2016-08-17 19:56
I believe this a dupe of #2083

**Closed by magnumripper** 2016-08-17 19:56 UTC
Labels: non-trivial, portability
