### ISSUE TITLE
Use strnzcpy in more places

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2928] opened 2017-11-27 15:03 UTC
@magnumripper Is this a good idea? Would you prefer the usage of `strnzcpy` over the following boilerplate code in our formats?

```
        int saved_len = strlen(key);
        if (saved_len > PLAINTEXT_LENGTH)
                saved_len = PLAINTEXT_LENGTH;
        memcpy(saved_key[index], key, saved_len);
        saved_key[index][saved_len] = 0;
```

Here is a Coccinelle semantic patch to get things going,

```
$ cat modernize-1.cocci 
@@
identifier saved_len;
identifier key;
identifier saved_key;
identifier index;
@@
-int saved_len = strlen(key);
-...
-saved_key[index][saved_len] = 0;
+strnzcpy(saved_key[index], key, PLAINTEXT_LENGTH + 1);
```

```
$ spatch modernize-1.cocci net_ah_fmt_plug.c 
init_defs_builtins: /usr/lib64/coccinelle/standard.h
HANDLING: net_ah_fmt_plug.c
diff = 
--- net_ah_fmt_plug.c
+++ /tmp/cocci-output-14536-e33159-net_ah_fmt_plug.c
@@ -201,11 +201,7 @@ static int cmp_exact(char *source, int i
 
 static void netah_set_key(char *key, int index)
 {
-        int saved_len = strlen(key);
-        if (saved_len > PLAINTEXT_LENGTH)
-                saved_len = PLAINTEXT_LENGTH;
-        memcpy(saved_key[index], key, saved_len);
-        saved_key[index][saved_len] = 0;
+        strnzcpy(saved_key[index], key, PLAINTEXT_LENGTH + 1);
 }
 
 static char *get_key(int index)
```

**Comment by solardiz** [comment] 2017-11-27 20:48
Regardless of immediate effect on performance, yes we should do this since it removes the duplicate code.

We should then separately see the effect on performance, and if it's negative then consider optionally implementing `strnzcpy()` in terms of `strlen()` + `memcpy()` or other fast libc functions (which for long enough strings commonly process multiple chars at a time). However, I expect a speedup right away since typical passwords are short (and so our code's simplicity probably wins over libc code's extra checks and setup needed to start and finish the multi-char processing).

**Comment by kholia** [comment] 2017-11-29 08:17
I did some light testing, and it seems that this change had no adverse effect on performance.

**Comment by jfoug** [comment] 2017-11-29 11:41
I am working on this at the current time, and yes, I have seen no performance regressions.  There  are some nuances a bit beyond your patch code, that require a bit of hand work.  There are times to use strnzcpy and times to use strnzcpyn.  Also, there are different variable names.  It is not that big of an undertaking to get them all done (all except the 'special' loading set_key functions are likely candidates).

**Comment by jfoug** [comment] 2017-11-29 11:49
A much better 'patch' would have been this

```c
static void set_key(char *key, int index)
 {
	strnzcpy(saved_key[index], key, sizeof(*saved_key));
 }
```

That way, if the format was setup like

```c
extern (*saved_key)[16+1];
```

The function would work correctly.  With your patch, you now would allow PLAINTEXT_LENGTH strings to be written, vs 16 byte strings .......

**Comment by kholia** [comment] 2017-11-29 11:57
Hmm. Yes, this approach seems better.

**Comment by jfoug** [comment] 2017-11-29 12:33
I have it done, and am testing.  I also found numerous other places where the strnzcpy would work (have not done all formats yet).  I did about half last nite.

**Comment by jfoug** [comment] 2017-11-29 12:37
09ccc79e8 uses the dynamically computed size. Also, there were some formats not found by your auto-script that are in there now.  I still have formats from m*.c -> x*.c to hand look at for slightly non-standard set_key, which require some hand editing.  The scripting got the largest percentage however.  GOOD stuff.

**Comment by jfoug** [comment] 2017-11-29 15:37
I believe with 9b088e2fc  this issue is pretty much addressed in full (for set_key), and that was the big place where the original ``` strlen+memcpy+key[len]=0 ``` logic was seen.

**Closed by jfoug** 2017-11-29 15:37 UTC
Labels: Maintenance/cleanup

**Comment by kholia** [comment] 2017-11-29 15:45
Nice work @jfoug 👍

**Comment by jfoug** [comment] 2017-11-29 17:44
Always nice to drop about 500-700 lines, but get equal end results ;)  There are other 'format' methods which we could also do this to.  I am working on the SIMD setkey stuff (that is much harder).   But the cmp_* functions, possibly binary, possibly the get_hash/salt_hash are other candidates.

It would be really nice to use a 'real' library function for some of this (like fmt_default_set_key type functions).  BUT since each .c file has it's own static data members, it makes doing this in a library NOT an easy thing to do, and thus we have to deref the method pointer, and now in the method, it simply calls another function.  It really would be nice to simply call the strnzcpy directly on these 'trivial' formats without having to call set_key for it to do the work.  I will spend a bit of time thinking about this one, BUT any solution may not be pretty or really doable at all.

**Comment by jfoug** [comment] 2017-11-29 17:51
About the only way I can see to REALLY do this, is set these data variables to be part of the format structure (Damn, I wish Solar would let us build this thing in C++).   Speaking of such, I really should look at redoing john IN C++ (for jumbo).  Many of these maintenance issues are all due to the current layout with data and methods not well tied to each other.  Well, with a C++ polymorphic base class, a LOT of this simply goes away (or can be easily managed). Since we have 100's of formats all to deal with, I really think it is time to revisit this, AT LEAST FOR jumbo. Then we would get rid of the 'jumbo' moniker, and simply call it john++   :)  JK.
