### ISSUE TITLE
OpenCL errors on OSX 10.9.5

### ISSUE THREAD

**Issue by denis0** [magnumripper/JohnTheRipper#1657] opened 2015-08-13 09:02 UTC
Hi,

System = Macbook Pro 17' - I7 - SSD - Full of Ram -Mac_OSX Mavericks , 1.9.5

a/ fresh install of bleeding last verion from today / to be noted = no tweak for optimal install on the Mac , like ; Homebrew, GCC etc...just classic fresh install

1/ macbookpro:run xxx$ ./john --list=build-info

Version: 1.8.0.6-jumbo-1-bleeding
Build: darwin13.4.0 64-bit AVX-ac
SIMD: AVX, interleaving: MD4:4 MD5:5 SHA1:2 SHA256:1 SHA512:1
$JOHN is ./
Format interface version: 13
Max. number of reported tunable costs: 3
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
Max. Markov mode level: 400
Max. Markov mode password length: 30
clang version: 6.0 (clang-600.0.57) (gcc 4.2.1 compatibility)
OpenCL library version: 1.2
Crypto library: OpenSSL
OpenSSL library version: 0009081af (loaded: 0009081df)
OpenSSL 0.9.8za 5 Jun 2014 (loaded: OpenSSL 0.9.8zd 8 Jan 2015)
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's

******************************

I have error once i launch the opencl test... ( one some other algo' i don't have that type of errors, ...on other i have the same type ).

1/ macbookpro:run xxxx$ ./john -form=raw-md5-opencl --test
Device 1: ATI Radeon HD 6750M
Benchmarking: Raw-MD5-opencl [MD5 OpenCL]... Build log: :257:18: warning: unknown attribute 'max_constant_size' ignored
attribute((max_constant_size (NUM_INT_KEYS * 4)))
^

DONE
Raw: 8305K c/s real, 69905K c/s virtual

2/ macbookpro:run xxxx$ ./john -form=descrypt-opencl --test
Device 1: ATI Radeon HD 6750M
Build log: :97:43: warning: unknown attribute 'max_constant_size' ignored
attribute((max_constant_size(3072)))
^
:101:43: warning: unknown attribute 'max_constant_size' ignored
attribute((max_constant_size(384)))
^

Benchmarking: descrypt-opencl, traditional crypt(3) [DES OpenCL]... DONE
Many salts: 1028K c/s real, 104857K c/s virtual
Only one salt: 1149K c/s real, 21845K c/s virtual

Thank you in advance for your help,

Denis

**Comment by magnumripper** [comment] 2015-08-13 09:16
OK that's just a benign warning. But it should be fixed.

**Comment by magnumripper** [comment] 2015-08-25 00:11
@denis0 if you can test latest code, please confirm that the problem is gone.

**Closed** 2015-08-25 00:11 UTC
Labels: portability

**Comment by denis0** [comment] 2015-08-25 20:00
Hi Magnum,

Thank you very much for the quick fix, all is run fine now !

But seem i loose a few speed on the "raw-md5" comparated at the test ( with
the issue )

Now :

macbookpro:run xxxx$ ./john --format=descrypt-opencl --test
Device 1: ATI Radeon HD 6750M
Benchmarking: descrypt-opencl, traditional crypt(3) [DES OpenCL]... DONE
Warning: "Many salts" test limited: 4/256
Many salts:    1018K c/s real, 34952K c/s virtual
Only one salt:    1110K c/s real, 14563K c/s virtual

macbookpro:run xxxxx$ ./john --format=raw-md5-opencl --test
Device 1: ATI Radeon HD 6750M
Benchmarking: Raw-MD5-opencl [MD5 OpenCL]... DONE
Raw:    *7419K c/s real, 37449K* c/s virtual

***********************

Before :


macbookpro:run xxxx$ ./john -form=raw-md5-opencl --test
Device 1: ATI Radeon HD 6750M
Benchmarking: Raw-MD5-opencl [MD5 OpenCL]... Build log: <program
source>:257:18: warning: unknown attribute 'max_constant_size' ignored
                __attribute__((max_constant_size (NUM_INT_KEYS * 4)))
                 ^

DONE
Raw:   * 8305K c/s real, 69905K* c/s virtual


*******************************



2015-08-25 2:12 GMT+02:00 magnum <notifications@github.com>:

**Comment by magnumripper** [comment] 2015-08-25 21:13
That is unrelated and my guess it's just an imprecise figure. Maybe it's caused by other changes, but the real-life speed is probably not worse (maybe better).

Try this for some real speed figure
```
$ echo aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa > test.in
$ ../run/john test.in -form:raw-md5-opencl -mask:?a?a?a?a?a
```

**Comment by denis0** [comment] 2015-08-26 15:09
Hi Magnum,

yep, you right, here my run ;

( Beside look in Bold an error appear...with modification of the ETA,
restablished couples of sec after...)

**************************************************************

macbookpro:run xxxx$ ./john md5.txt -form:raw-md5-opencl -mask:?a?a?a?a?a
Device 1: ATI Radeon HD 6750M
Using default input encoding: UTF-8
Loaded 2984 password hashes with no different salts (Raw-MD5-opencl [MD5
OpenCL])

Press 'q' or Ctrl-C to abort, almost any other key for status

0g 0:00:00:11 7.17% (ETA: 17:01:18) 0g/s 46285Kp/s 46285Kc/s 150419MC/s
fl&..  p8'
$M$11            (?)
1g 0:00:00:19 18.15% (ETA: 17:00:29) 0.05040g/s 70802Kp/s 70802Kc/s
220615MC/s $M/\1..  Pb1
Z4Nd@            (?)
2g 0:00:00:33 37.74% (ETA: 17:00:12) 0.05915g/s 86375Kp/s 86375Kc/s
264017MC/s   .qC..  8=D
*Get key error! 11831774 11831774*
2g 0:00:01:18 *0.01% (ETA: 2015-09-03 20:13) *0.02552g/s 99202Kp/s
99202Kc/s 295875MC/s ##3q~..##3q~
Use the "--show" option to display all of the cracked passwords reliably
Session completed

& without openCL

macbookpro:run xxxx$ ./john md5.txt -form:raw-md5 -mask:?a?a?a?a?a
Using default input encoding: UTF-8
Loaded 2984 password hashes with no different salts (Raw-MD5 [MD5 128/128
AVX 4x5])
Remaining 2982 password hashes with no different salts
Press 'q' or Ctrl-C to abort, almost any other key for status

0g 0:00:00:31 7.70% (ETA: 17:07:16) 0g/s 19222Kp/s 19222Kc/s 57320MC/s 4}
>'..G} >'
0g 0:00:02:56 44.10% (ETA: 17:07:14) 0g/s 19281Kp/s 19281Kc/s 57822MC/s
>nHuI..QnHuI
0g 0:00:03:21 50.28% (ETA: 17:07:14) 0g/s 19261Kp/s 19261Kc/s 57720MC/s
9dlhO..LdlhO


2015-08-25 23:13 GMT+02:00 magnum <notifications@github.com>:
