### ISSUE TITLE
descrypt-opencl fails self test on super with --device=0

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#2051] opened 2016-02-14 21:11 UTC
```
$ ./john --test=0 --format=descrypt-opencl --device=0
Device 0: Juniper [AMD Radeon HD 6700 Green Edition]
Testing: descrypt-opencl, traditional crypt(3) [DES OpenCL]... FAILED (cmp_all(0))

```

**Comment by solardiz** [comment] 2016-08-10 10:57
Confirmed. FWIW, the problem is hidden when the last 3 out of the 6 test vectors in opencl_DES_fmt_plug.c are removed. IOW, leaving these:

```
        {"CCNf8Sbh3HDfQ", "U*U*U*U*"},
        {"CCX.K.MFy4Ois", "U*U***U"},
        {"CC4rMpbg9AMZ.", "U*U***U*"},
```

and removing these:

```
        {"XXxzOu6maQKqQ", "*U*U*U*U"},
        {"SDbsugeBiC58A", ""},
        {"..X8NBuQ4l6uQ", ""},
```

makes the self-test pass on this same "problematic" device. Of course, this only hides the problem. Trying to crack 25 other hashes with a corresponding wordlist, still on this same device, resulted in only 12 of them getting cracked. (All 25 are cracked on CPU or when targeting a different AMD GPU in this same machine, with this same driver.) So it looks like this problem is affecting half of the hashes, or half of the candidate passwords (can't tell which it is from these experiments so far).

**Comment by magnumripper** [comment] 2018-05-09 20:42
I believe that device is now EOL and (I think) not even supported by recent drivers. Closing.

**Closed by magnumripper** 2018-05-09 20:42 UTC
Labels: bug
