### ISSUE TITLE
29% performance regression for --format=bcrypt

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1199] opened 2015-04-11 19:24 UTC
On 64bit Linux:

```
fd@fdu:~/git/JtR/src$ git status |head -n 2
On branch bleeding-jumbo
Your branch is up-to-date with 'origin/bleeding-jumbo'.
fd@fdu:~/git/JtR/src$ make -s distclean ; ./configure > /dev/null && make -s -j 8 && cd ../run/ && ./john --test --format=bcrypt; cd ../src/
DES_std.c: In function 'DES_std_set_key':
DES_std.c:639:17: warning: array subscript is above array bounds [-Warray-bounds]
   while (DES_key[i++]) k += 2;
                 ^
/usr/bin/ar: creating aes.a

Make process completed.
Will run 4 OpenMP threads
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X2]... (4xOMP) DONE
Speed for cost 1 (iteration count) of 32
Raw:    3888 c/s real, 967 c/s virtual

fd@fdu:~/git/JtR/src$ git checkout 88b1a10889405a9f33690795368d1faa21c1c59b
Note: checking out '88b1a10889405a9f33690795368d1faa21c1c59b'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 88b1a10... Revert "bcrypt / opencl: created a BF_common set of functions / data"
fd@fdu:~/git/JtR/src$ make -s distclean ; ./configure > /dev/null && make -s -j 8 && cd ../run/ && ./john --test --format=bcrypt; cd ../src/
DES_std.c: In function 'DES_std_set_key':
DES_std.c:639:17: warning: array subscript is above array bounds [-Warray-bounds]
   while (DES_key[i++]) k += 2;
                 ^
/usr/bin/ar: creating aes.a

Make process completed.
Will run 4 OpenMP threads
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X3]... (4xOMP) DONE
Speed for cost 1 (iteration count) of 32
Raw:    5040 c/s real, 1253 c/s virtual

fd@fdu:~/git/JtR/src$ git checkout bbe3e324121a55d40d845b7eea94cd0963951d95
Previous HEAD position was 88b1a10... Revert "bcrypt / opencl: created a BF_common set of functions / data"
HEAD is now at bbe3e32... Merge branch 'master' into bleeding-jumbo
fd@fdu:~/git/JtR/src$ make -s distclean ; ./configure > /dev/null && make -s -j 8 && cd ../run/ && ./john --test --format=bcrypt; cd ../src/
DES_std.c: In function 'DES_std_set_key':
DES_std.c:639:17: warning: array subscript is above array bounds [-Warray-bounds]
   while (DES_key[i++]) k += 2;
                 ^
/usr/bin/ar: creating aes.a

Make process completed.
Will run 4 OpenMP threads
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X2]... (4xOMP) DONE
Speed for cost 1 (iteration count) of 32
Raw:    3825 c/s real, 966 c/s virtual
```

So, for some reasons, merging Solar's core changes caused this performance regression on my hardware:

```
$ head -n 25 /proc/cpuinfo 
processor   : 0
vendor_id   : GenuineIntel
cpu family  : 6
model       : 60
model name  : Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
stepping    : 3
microcode   : 0x16
cpu MHz     : 800.390
cache size  : 6144 KB
physical id : 0
siblings    : 4
core id     : 0
cpu cores   : 4
apicid      : 0
initial apicid  : 0
fpu     : yes
fpu_exception   : yes
cpuid level : 13
wp      : yes
flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm
bogomips    : 5986.37
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:
```

**Comment by frank-dittrich** [comment] 2015-04-11 20:10
BTW:

Looks like you just missed some performance improvement bleeding-jumbo had over core john after you merged Solar's changes.

Core 1.8.0:
```
fd@fdu:~/git/JtR$ ./run/john  |head -n 1
John the Ripper password cracker, version 1.8.0
fd@fdu:~/git/JtR$ ./run/john --test --format=bcrypt 
Will run 4 OpenMP threads
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X2]... DONE
Raw:	3811 c/s real, 953 c/s virtual
```

jumbo 1:
```
fd@fdu:~/git/JtR$ ./run/john |head -n 1
John the Ripper password cracker, version 1.8.0-jumbo-1_omp [linux-gnu 64-bit AVX2-autoconf]
fd@fdu:~/git/JtR$ ./run/john --test --format=bcrypt 
Will run 4 OpenMP threads
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X3]... (4xOMP) DONE
Raw:	5040 c/s real, 1253 c/s virtual
```

Note the X2 vs. X3 difference

**Comment by frank-dittrich** [comment] 2015-04-11 22:36
Apparently, the BF related changes of commit f64b42fee9e368cd85cf546f08b694510824fea2 make the difference.
If I build linux-x86-64-native for this commit (this was before autoconf got introduced), I get
```
Will run 4 OpenMP threads
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X3]... (4xOMP) DONE
Raw:	4954 c/s real, 1251 c/s virtual
```

With f212f898754a1b0ab000883f156917ab5b6b3c96, I get
```
Will run 4 OpenMP threads
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X2]... (4xOMP) DONE
Raw:	3864 c/s real, 966 c/s virtual
```

**Comment by magnumripper** [comment] 2015-04-11 23:16
Try the latest core code from the master branch (d686010da) versus 1.8. Doesn't it show the same problem?

**Comment by frank-dittrich** [comment] 2015-04-11 23:27
Apparently, on well the current logic is almost 5 percent faster than the one which works best for me.
May be that's why Solar didn't enable this logic for avx.

When I test commit d686010da1febe937041177bd3f15f1f998a0544 (latest master commit) on my system (linux-x86-65-native), I get
```
fd@fdu:~/git/JtR/run$ ./john --test --format=bcrypt 
Will run 4 OpenMP threads
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X2]... DONE
Raw:	3796 c/s real, 949 c/s virtual
```

Similar for a generic build:
```
fd@fdu:~/git/JtR/run$ ./john --test --format=bcrypt 
Will run 4 OpenMP threads
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X2]... DONE
Raw:	3830 c/s real, 958 c/s virtual
```
Apparently, `Blowfish 32/64 X3` is not tested in a generic build:
```
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64]... 1992 c/s real, 499 c/s virtual
Compiling: Blowfish benchmark (scale)
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64]... 2068 c/s real, 517 c/s virtual
Compiling: Blowfish benchmark (two hashes at a time)
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X2]... 3830 c/s real, 958 c/s virtual
```

May be the benchmark should try X > 2, as long as the resulting c/s rate increases?

And may be we need to introduce --benchmark into out ./configure script?

**Comment by frank-dittrich** [comment] 2015-04-11 23:53
BTW, this patch to master helps creating a generic build with improved bcrypt performance for my system:
```
diff --git a/src/best.sh b/src/best.sh
index 5e671b1..0192183 100755
--- a/src/best.sh
+++ b/src/best.sh
@@ -122,11 +122,21 @@ echo "Compiling: Blowfish benchmark (two hashes at a time)"
 $MAKE bench || exit 1
 RES=`./bench 3` || exit 1
 if [ $RES -gt $MAX ]; then
+	MAX=$RES
 	BF_X2=1
+	./detect $DES_BEST $DES_COPY $DES_BS $MD5_X2 $MD5_IMM $BF_SCALE 3 > arch.h
+	rm -f $BF_DEPEND bench
+	echo "Compiling: Blowfish benchmark (three hashes at a time)"
+	$MAKE bench || exit 1
+	RES=`./bench 3` || exit 1
+	if [ $RES -gt $MAX ]; then
+		BF_X2=3
+	fi
 else
 	BF_X2=0
 fi
 ```

```
fd@fdu:~/git/JtR/src$ make -s generic
Compiling: DES benchmark (code version #1)
DES_std.c: In function ‘DES_std_set_key’:
DES_std.c:635:17: warning: array subscript is above array bounds [-Warray-bounds]
   while (DES_key[i++]) k += 2;
                 ^
Benchmarking: descrypt, traditional crypt(3) [DES 48/64 4K]... 545843 c/s real, 545843 c/s virtual
Compiling: DES benchmark (code version #2)
DES_std.c: In function ‘DES_std_set_key’:
DES_std.c:635:17: warning: array subscript is above array bounds [-Warray-bounds]
   while (DES_key[i++]) k += 2;
                 ^
Benchmarking: descrypt, traditional crypt(3) [DES 48/64 128K]... 483328 c/s real, 483328 c/s virtual
Compiling: DES benchmark (code version #3)
DES_std.c: In function ‘DES_std_set_key’:
DES_std.c:635:17: warning: array subscript is above array bounds [-Warray-bounds]
   while (DES_key[i++]) k += 2;
                 ^
Benchmarking: descrypt, traditional crypt(3) [DES 48/64 4K]... 563123 c/s real, 563123 c/s virtual
Compiling: DES benchmark (code version #4)
DES_std.c: In function ‘DES_std_set_key’:
DES_std.c:635:17: warning: array subscript is above array bounds [-Warray-bounds]
   while (DES_key[i++]) k += 2;
                 ^
Benchmarking: descrypt, traditional crypt(3) [DES 48/64 4K]... 569318 c/s real, 569318 c/s virtual
Compiling: DES benchmark (code version #5)
DES_std.c: In function ‘DES_std_set_key’:
DES_std.c:635:17: warning: array subscript is above array bounds [-Warray-bounds]
   while (DES_key[i++]) k += 2;
                 ^
Benchmarking: descrypt, traditional crypt(3) [DES 48/64 4K]... 539315 c/s real, 539315 c/s virtual
Compiling: DES benchmark (code version #4, no key copying)
DES_std.c: In function ‘DES_std_set_key’:
DES_std.c:635:17: warning: array subscript is above array bounds [-Warray-bounds]
   while (DES_key[i++]) k += 2;
                 ^
Benchmarking: descrypt, traditional crypt(3) [DES 48/64 4K]... 570470 c/s real, 570470 c/s virtual
Compiling: DES benchmark (bitslice, code version #1)
DES_std.c: In function ‘DES_std_set_key’:
DES_std.c:635:17: warning: array subscript is above array bounds [-Warray-bounds]
   while (DES_key[i++]) k += 2;
                 ^
Benchmarking: descrypt, traditional crypt(3) [DES 64/64]... 9350K c/s real, 2339K c/s virtual
Compiling: DES benchmark (bitslice, code version #2)
Benchmarking: descrypt, traditional crypt(3) [DES 64/64]... 9325K c/s real, 2332K c/s virtual
Compiling: DES benchmark (bitslice, code version #3)
Benchmarking: descrypt, traditional crypt(3) [DES 64/64]... 5585K c/s real, 1397K c/s virtual
Benchmarking: md5crypt [MD5 32/64]... 42086 c/s real, 10516 c/s virtual
Compiling: MD5 benchmark (two hashes at a time)
Benchmarking: md5crypt [MD5 32/64 X2]... 63770 c/s real, 15950 c/s virtual
Compiling: MD5 benchmark (immediate values)
Benchmarking: md5crypt [MD5 32/64 X2]... 65740 c/s real, 16435 c/s virtual
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64]... 1992 c/s real, 498 c/s virtual
Compiling: Blowfish benchmark (scale)
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64]... 2066 c/s real, 516 c/s virtual
Compiling: Blowfish benchmark (two hashes at a time)
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X2]... 3830 c/s real, 958 c/s virtual
Compiling: Blowfish benchmark (three hashes at a time)
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X3]... 4982 c/s real, 1245 c/s virtual
DES_std.c: In function ‘DES_std_set_key’:
DES_std.c:635:17: warning: array subscript is above array bounds [-Warray-bounds]
   while (DES_key[i++]) k += 2;
                 ^
fd@fdu:~/git/JtR/src$ ../run/john --test --format=bcrypt 
Will run 4 OpenMP threads
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X3]... DONE
Raw:	4946 c/s real, 1237 c/s virtual
```

Tomorrow (after I got some sleep) I'll report my findings to john-dev, so that Solar can improve the generic build and may be reconsider setting BF_X2 to 3 even for avx systems.

**Comment by frank-dittrich** [comment] 2015-04-12 10:29
I reported the regression here:
http://openwall.com/lists/john-dev/2015/04/12/4
http://thread.gmane.org/gmane.comp.security.openwall.john.devel/11239

Unfortunately, I forgot a link to this issue.

**Comment by frank-dittrich** [comment] 2015-04-12 10:56
Some more data:
Intel(R) Core(TM) i7-2820QM CPU @ 2.30GHz (quad core with HT), generic build without OMP, also a 23% improvement:
```
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64]... 412 c/s real, 412 c/s virtual
Compiling: Blowfish benchmark (scale)
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64]... 455 c/s real, 455 c/s virtual
Compiling: Blowfish benchmark (two hashes at a time)
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X2]... 807 c/s real, 807 c/s virtual
Compiling: Blowfish benchmark (three hashes at a time)
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X3]... 999 c/s real, 1001 c/s virtual
```
With OMP enabled (8*OMP due to HT), just a 2% performance improvement:
```
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64]... 1916 c/s real, 240 c/s virtual
Compiling: Blowfish benchmark (scale)
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64]... 2174 c/s real, 272 c/s virtual
Compiling: Blowfish benchmark (two hashes at a time)
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X2]... 3200 c/s real, 400 c/s virtual
Compiling: Blowfish benchmark (three hashes at a time)
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X3]... 3276 c/s real, 409 c/s virtual
```
With OMP_NUM_THREADS=4, a 25% improvement:
```
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64]... 1276 c/s real, 320 c/s virtual
Compiling: Blowfish benchmark (scale)
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64]... 1353 c/s real, 338 c/s virtual
Compiling: Blowfish benchmark (two hashes at a time)
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X2]... 2423 c/s real, 606 c/s virtual
Compiling: Blowfish benchmark (three hashes at a time)
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X3]... 3046 c/s real, 762 c/s virtual
```

**Comment by jfoug** [comment] 2015-08-31 15:01
> Try the latest core code from the master branch (d686010) versus 1.8.0. Doesn't it show the same problem?
> Note: You have to build for AVX or XOP for a comparable build.

I have built on all 3 types (AVX, XOP, AVX2). I see improvements to all processors.

AVX2 I see abotu 25% or so (as what was reported by @frank-dittrich).  XOP I see about 12% improvement, and AVX I see about 15% improvement.

But for all systems I have that are >= AVX  I am seeing BF_X2=3 to be an improvement over BF_X2=1

**Comment by frank-dittrich** [comment] 2015-08-31 15:24
I even have a 36% performance improvement on my i5-4570 CPU (quad core with AVX2 and ht, but number of logical cores = number of physical cores = 4), but Solar found a regression (either on super or on well or even on both) for BF_X2 = 3 compered ro BF_X2 = 1.

**Comment by jfoug** [comment] 2015-09-01 17:09
I wonder if this should be a configuration check, and not hard coded into x86-64.h ?   @magnumripper what do you think about that idea?  Or at least a configure check, that can OVERRIDE the value in x86-64.h

**Comment by frank-dittrich** [comment] 2015-09-01 17:23
What kind of check do you have in mind?
Something similar to the benchmark for `make -f Makefile.legacy generic`, except that you would try BF_X2 = 3 as well?
But then the build process can pick non-optimal values depending on varying system load.

**Comment by frank-dittrich** [comment] 2015-09-01 17:25
May be we have to repeat Solar's test on super and well. The performance regression or improvement could also depend on compiler version.

**Comment by magnumripper** [comment] 2015-09-01 17:46
I'm open for configure-time benchmarking, but it does have the caveat @frank-dittrich mentioned with system load.

If nothing else, we should wrap any `#define BF_X2` in arch.h's with `#ifndef BF_X2 ... #endif`. That would mean you can override it at configure time (we wouldn't really need to add any option for it, just add it to CFLAGS or CPPFLAGS).

**Comment by jfoug** [comment] 2015-09-01 17:54
That is a viable alternative (the CPPFLAGS).  It would be nice to find out the 'truth' about the regression.  Possibly it was only OMP builds or something.  From what I have seen it runs faster on all of my systems (xop, avx and avx2).  Both under windows (cygwin), and a linux-64 VM. BUT by reading the comment, this is due to SMT-capable CPU's . Could that be something that is turned on, when running physical installed unix on these CPU's ?

But like frank mentioned, it may also be compiler version dependent and was a bug that has been fixed.

**Comment by magnumripper** [comment] 2015-09-01 19:48
> If nothing else, we should wrap any `#define BF_X2` in arch.h's with `#ifndef BF_X2 ... #endif`.

Anyone of you doing this? Otherwise I'll do it.

**Comment by magnumripper** [comment] 2015-09-01 23:33
i7-3615QM (Ivy Bridge, AVX), OSX, gcc 4.9.2

Non-OMP build:
```
$ ../run/john-no_omp_h24 -test -form:bcrypt
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X2]... DONE
Speed for cost 1 (iteration count) of 32
Raw:	860 c/s real, 860 c/s virtual

$ ../run/john-no_omp-h24X3 -test -form:bcrypt
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X3]... DONE
Speed for cost 1 (iteration count) of 32
Raw:	1089 c/s real, 1089 c/s virtual
```

OMP w/o HT:
```
$ OMP_NUM_THREADS=4 ../run/john-omp-h24 -test -form:bcrypt
Will run 4 OpenMP threads
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X2]... (4xOMP) DONE
Speed for cost 1 (iteration count) of 32
Raw:	3255 c/s real, 824 c/s virtual

$ OMP_NUM_THREADS=4 ../run/john-omp-h24X3 -test -form:bcrypt
Will run 4 OpenMP threads
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X3]... (4xOMP) DONE
Speed for cost 1 (iteration count) of 32
Raw:	3956 c/s real, 1009 c/s virtual
```

OMP w/ HT:
```
$ ../run/john-omp-h24 -test -form:bcrypt
Will run 8 OpenMP threads
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X2]... (8xOMP) DONE
Speed for cost 1 (iteration count) of 32
Raw:	4368 c/s real, 624 c/s virtual

$ ../run/john-omp-h24X3 -test -form:bcrypt
Will run 8 OpenMP threads
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X3]... (8xOMP) DONE
Speed for cost 1 (iteration count) of 32
Raw:	4562 c/s real, 628 c/s virtual
```

**Comment by magnumripper** [comment] 2015-11-13 18:19
https://github.com/magnumripper/JohnTheRipper/commit/14685372f4394f3ffe8ba58f797deb9f01fcfba9#commitcomment-14375823

**Comment by magnumripper** [comment] 2015-11-13 21:46
@frank-dittrich please test on that non-HT hardware you got. We are now checking for hyperthreading with a cpuid call in autoconf, and use the results accordingly.

**Comment by magnumripper** [comment] 2015-11-13 21:50
I'm not sure whether we should set X3 even for HT machines when not building OpenMP. I think I recall Solar argued against it (because X2 should be better for -fork too).

**Comment by magnumripper** [comment] 2015-11-13 21:54
BTW the test runs fine on 32-bit too.

**Comment by frank-dittrich** [comment] 2015-11-13 21:55
@magnumripper I did teswt on my CPU. /proc/cpuinfo reports ht capability, and autoconf detects ht capability, so BF_X2 is defined as 1. But 3 would be much better for my CPU.

Do we have a recent compiler version (gcc >= 5.0) on those systems where we see a regression with BF_X2 = 3? May be the value of BF_X2 should depend on gcc version?

**Comment by magnumripper** [comment] 2015-11-13 21:59
> But 3 would be much better for my CPU.

When actually using all available threads too?

I use gcc 5.2.0 and I definitely see a regression when running X3. That's measured **with** HT.

**Comment by jfoug** [comment] 2015-11-13 22:02
It should not only depend upon compiler version.   But right now, it bases 100% on the HT bit.   That is not right logic either.

I use non-omp build running on 6 cores (with fork and a few stand alone), and it is MUCH faster than when built with X2=1.   It also allows the machine to  be useful.  There is a tiny gain going to 7 runs, and almost none going to 8 threads.  But even at 8 threads, it IS faster than OMP, and faster than X2=1 for fork=8

**Comment by magnumripper** [comment] 2015-11-13 22:03
> right now, it bases 100% on the HT bit. That is not right logic either.

Then we should challenge Solar's statements in that thread on john-dev.

**Comment by magnumripper** [comment] 2015-11-13 22:05
You can obviously still `./configure CPPFLAGS=-DBF_X2=3` if you like. That overrules everything else.

**Comment by jfoug** [comment] 2015-11-13 22:06
Just got this message:

"Sorry, AVX2 is required for this build"

Running on virtualbox.  AVX2 worked just fine, until you added runtime checks.

**Comment by magnumripper** [comment] 2015-11-13 22:07
That's odd. It's well tested.

**Comment by magnumripper** [comment] 2015-11-13 22:08
Could my addition of HAVE_HT have had this side effect?

**Comment by jfoug** [comment] 2015-11-13 22:08
configure has given me AVX2 for a while (an update to VirtualBox about a year ago), and configure worked, as did all formats, doing AVX2

**Comment by jfoug** [comment] 2015-11-13 22:09
I am testing on cygwin-64    Nope, that one works fine.

**Comment by magnumripper** [comment] 2015-11-13 22:35
I gave in and set it to 3 for non-OpenMP builds. It's unreasonable not to do so IMHO.

**Comment by magnumripper** [comment] 2015-11-13 23:01
On a side note I updated my [fallback wiki page](https://github.com/magnumripper/JohnTheRipper/wiki/Fallback-binary-chain,-without-JOHN_SYSTEMWIDE#openmp-fallback) to include "native CPU, but with OpenMP fallback"

**Comment by magnumripper** [comment] 2015-11-13 23:15
Although I seem to have to change a few bits to make it actually work. I'm puzzled that Solar didn't make OMP_FALLBACK work without JOHN_SYSTEMWIDE.

**Comment by magnumripper** [comment] 2015-11-13 23:23
Fallback stuff fixed in 9852e5e.

**Comment by jfoug** [comment] 2015-11-16 16:38
Here is on my CoreI7-HT AVX machine.   X3 is quite a bit better, and much more 'stable'

$ ../run/john -test=5 -form=bcrypt
Will run 8 OpenMP threads
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X2]... (8xOMP) DONE
Speed for cost 1 (iteration count) of 32
Raw:    4322 c/s real, 602 c/s virtual

$ ../run/john -test=5 -form=bcrypt
Will run 8 OpenMP threads
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X2]... (8xOMP) DONE
Speed for cost 1 (iteration count) of 32
Raw:    3936 c/s real, 614 c/s virtual

$ ../run/john -test=5 -form=bcrypt
Will run 8 OpenMP threads
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X2]... (8xOMP) DONE
Speed for cost 1 (iteration count) of 32
Raw:    4118 c/s real, 607 c/s virtual


$ ../run/john -test=5 -form=bcrypt
Will run 8 OpenMP threads
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X3]... (8xOMP) DONE
Speed for cost 1 (iteration count) of 32
Raw:    4538 c/s real, 625 c/s virtual

$ ../run/john -test=5 -form=bcrypt
Will run 8 OpenMP threads
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X3]... (8xOMP) DONE
Speed for cost 1 (iteration count) of 32
Raw:    4571 c/s real, 617 c/s virtual

$ ../run/john -test=5 -form=bcrypt
Will run 8 OpenMP threads
Benchmarking: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X3]... (8xOMP) DONE
Speed for cost 1 (iteration count) of 32
Raw:    4536 c/s real, 609 c/s virtual


I am sorry, I still argue that the proper setting is 3x, always.

**Comment by jfoug** [comment] 2015-11-16 16:40
Is there any way to build both X2=1 and X2=3, and have runtime selection of the proper code?

**Comment by frank-dittrich** [comment] 2015-11-16 17:31
@jfoug Apparently, you didn't test combinations of X2=1 and X2=3 (non-OMP) for max. number of logical cores.
When I tested on my laptop (`Intel(R) Core(TM) i7-2820QM CPU @ 2.30GHz` quad core, 8 logical cores), the best total combined c/s rate required running a mix of X2=1 and X2=3 binaries, while for just a single binary (or up to 4 binaries) X2=3 was better.

**Comment by magnumripper** [comment] 2015-11-16 18:03
> Is there any way to build both X2=1 and X2=3, and have runtime selection of the proper code?

Solar will fix it eventually, in JP. He already mentioned it.

> I still argue that the proper setting is 3x, always.

So you are arguing that a regression for me is the proper setting. There's no point in arguing about something that vary among CPUs. Besides, you should argue on john-dev, not here. This may trigger Solar to make the canonical fix.

**Comment by frank-dittrich** [comment] 2016-03-18 13:06
Wow, you assigned 25 issues to me in just one minute.
Looking into all of these 25 issues will definitely take a little longer.

**Comment by magnumripper** [comment] 2016-03-19 10:45
Heh, I just picked issues with no assignee and that was opened by you. I intend to do so with other openers too.

**Comment by magnumripper** [comment] 2019-04-10 20:43
This is now "fixed" in core (actually X3 is always used) and we shall never mention it again

**Closed by magnumripper** 2019-04-10 20:43 UTC
Labels: core John (master branch)
