### ISSUE TITLE
JWT Issue

### ISSUE THREAD

**Issue by MagicAlan** [magnumripper/JohnTheRipper#2318] opened 2016-11-04 16:47 UTC
I have the following JWT (it is an example):

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3Rlc3QtdGVzdC50ZXN0ZXN0dGVzdC5jb20vIiwic3ViIjoidGVzdHwwMDAwMCIsImF1ZCI6ImZzZHJmTEtISkdZVGRmb3NpdXVUVUppdWZ5ZGd1cmZlIiwiZXhwIjoyNTQ0Nzc4NDU3LCJpYXQiOjI1NDQ3Nzg0NTcsImF6cCI6ImZzZHJmTEtISkdZVGRmb3NpdXVUVUppdWZ5ZGd1cmZlIn0.JLsq4NDG-SBY998TnuukyssQahWDqc-X5rXTifoMS8I

I tried to crack it using John the Ripper (Jumbo) but I got the following error:

Using default input encoding: UTF-8
No password hashes loaded (see FAQ)

Specifying "--format=HMAC-SHA256" I'm still getting the same error above.
 
If I try the example JWT token in the jwt.io site, I can successfully crack it. So, my guess would be that John is not loading the value because of its size?

Can anybody help me with this issue? thanks a lot!

**Comment by claudioandre** [comment] 2016-11-04 18:49
> John is not loading the value because of its size?

Indeed, the check failing is in valid() line 240 of hmacSHA256_fmt_plug.c
```
if (strlen(ciphertext) > CT_LEN)
```

**Comment by MagicAlan** [comment] 2016-11-07 13:55
Hi Claudio, i changed the value from CT_LEN in (esf_fmt_plug.c), but i'm still getting the same error..

**Comment by claudioandre** [comment] 2016-11-07 16:50
What I meant in the first place was:
- the format developer built the format with this limit in mind. Unfortunately, it is not expected that a simple change like yours works.

It seems your encoded is a valid HS256 (https://jwt.io/) not supported by JtR now. That said, unless you are eager to put your hands on it, the issue is a warning/reminder to the developers.

**Comment by MagicAlan** [comment] 2016-11-07 16:55
Alright Claudio, thank you.

**Comment by magnumripper** [comment] 2016-11-07 17:52
The correct fix was simply bumping SALT_LIMBS from 3 to 5. I have committed that just now in a366c37.

**Comment by magnumripper** [comment] 2016-11-07 18:12
Hmmm I added the 'enhancement' and 'Fixed - pending verify' labels. But it says MagicAlan did it. Are we facing Github data corruption? 😨

**Comment by jfoug** [comment] 2016-11-07 18:59
Could it have something to do with the emoji used?  that is the first time I have seen that one.  Possibly it corrupts the data which the php generates in some way, that 'keeps' the ownership of the emoji when showing the child item (the enhancement).   I doubt it is corruption.  Just a github.com interface bug.

**Comment by magnumripper** [comment] 2016-11-07 19:16
No, the emoji was added later.

**Comment by magnumripper** [comment] 2016-11-07 19:17
Anyway, I could easily crack the password of the sample so I'm closing this.

**Closed by magnumripper** 2016-11-07 19:17 UTC
Labels: enhancement, Fixed - pending verify
