### ISSUE TITLE
Feature Request Windows User Account to Keepass2john/JTR

### ISSUE THREAD

**Issue by DieKart** [magnumripper/JohnTheRipper#2863] opened 2017-11-09 19:49 UTC
Keepass2john/JTR supports the keepass hash of kdb and kdbx files with and without keyfile. Keepass also has a feature of adding Windows User Account that is currently not support. Could you please add this feature or add the output of this feature so that JTR/Hashcat will have a crackable hash.
Harmj0y has written an article giving some information on this issue http://www.harmj0y.net/blog/redteaming/a-case-study-in-attacking-keepass/
Maybe you guys can help us out here: @Fist0urs, @magnumripper, @harmj0y.

**Comment by kholia** [comment] 2017-11-10 04:17
This is a duplicate of https://github.com/magnumripper/JohnTheRipper/issues/2555.

**Closed by kholia** 2017-11-10 04:17 UTC
