### ISSUE TITLE
OpenCL support issue in Ubuntu 18.04.1

### ISSUE THREAD

**Issue by madtomic** [magnumripper/JohnTheRipper#3492] opened 2018-12-08 04:07 UTC
I am testing now with a single card, AMD RX 470 card on Ubuntu 18.04.1

I found out amdgpu-pro driver can install legacy driver to support OpenCL,
using ./amdgpu-pro-install -y --opencl=legacy

Also, Alex mentioned this when he pull his shell history so I google a bit on how to do this. 

Here is my setup and I don't know why the OpenCL support is not detected while configuring.

During ./configure --enable-mpi - I see this line.
>OpenCL support ............................. no

While make... I see a warning about some code.

tezos@tezos-desktop:~/Downloads/JohnTheRipper/src$ make -s clean && make -sj4
ar: creating aes.a
ar: creating ed25519-donna.a
ar: creating secp256k1.a
single.c: In function ‘single_init’:
single.c:170:25: warning: suggest parentheses around comparison in operand of ‘|’ [-Wparentheses]
            (mpi_p_local > 1 | options.fork)
             ~~~~~~~~~~~~^~~

Make process completed.


I had tried 18.20 - 18.40 drivers, all same issue with OpenCL
>Driver and System Info

tezos@tezos-desktop:~/JohnTheRipper/run$ dpkg -l amdgpu-pro
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  amdgpu-pro     18.20-673703 amd64        Meta package to install amdgpu Pr


tezos@tezos-desktop:~/JohnTheRipper/run$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

>John Build Info

tezos@tezos-desktop:~/JohnTheRipper/run$ ./john --list=build-info
Version: 1.8.0.13-jumbo-1-bleeding-323f4babd 2018-12-07 11:06:56 +0000
Build: linux-gnu 64-bit x86_64 AVX2 AC MPI + OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 7.3.0
GNU libc version: 2.27 (loaded: 2.27)
Crypto library: OpenSSL
OpenSSL library version: 01010007f
OpenSSL 1.1.0g  2 Nov 2017
GMP library version: 6.1.2
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's


- `$ ./john --list=opencl-devices` (if applicable).
>Does not work as it wasn't detected in the build.

**Comment by madtomic** [comment] 2018-12-08 04:32
Latest driver clearly stated it supports my AMD card.
https://www.amd.com/en/support/kb/release-notes/rn-prorad-lin-18-40

Installation instruction give me some idea how to set up OpenCL support. I could try to use 
>--compute                        (DEPRECATED) Equal to --opencl=legacy --headless

https://www.amd.com/en/support/kb/release-notes/AMDGPU-INSTALLATION

I am stuck once again... err

**Comment by magnumripper** [comment] 2018-12-08 04:37
Does `clinfo` show your card?

**Comment by claudioandre-br** [comment] 2018-12-08 11:15
You should attach `config.log`. We can't see what is happening without the full log.
* e.g., it could be silly as a header in the "wrong" place.

Anyway:
* unfortunately, none of the developers use GPUs anymore (I mean, is buying);
* we are stuck in the past (GPUs **and** drivers);
* For example, I have no idea if Ubuntu 18.04 can really make someone's life more difficult;

That said, my opinion is that if you can use Windows (as suggested on john-users), you should. 

You've been fighting windmills for weeks. That is not a good user experience.

**Comment by claudioandre-br** [comment] 2018-12-08 15:37
> I had tried 18.20 - 18.40 drivers, all same issue with OpenCL

BTW: 18.20 should fail. But, 18.40 should work.

**Comment by claudioandre-br** [comment] 2018-12-15 17:59
Bug closed because of:

* **Low Priority** - They have a tendency to become high priority if enough of the users complain.

* **Business Priority** - Obsolete hardware and software. Hardware nobody owns, etc.

* **WontFix** - Covers all the reasons we chose to close the bug without taking action
  * Can't reproduce, working as intended, obsolete.
  * Required information was not provided.

**Closed by claudioandre-br** 2018-12-15 17:59 UTC
