### ISSUE TITLE
Test both OpenMP and non-OpenMP builds on non-SIMD targets in a CI

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#2955] opened 2017-12-02 13:43 UTC
We really should have both CI's enabled when doing the tests for PRs  I have recently checked in code that has a lot of unique SIMD vs non-SIMD logic, and really needed better testing.  @solardiz found a bug by static looking at code, and seeing things were missed,but only on non-SIMD-gomp builds.  When I tried to build that way on my system, it failed.  BUT this [ws]houl have easily been caught with a CI test, and the PR should never have passed.

**Comment by jfoug** [comment] 2017-12-02 13:45
ALSO, if we are not testing both gomp and non-gomp builds non-SIMD targets (in CircleCI), then we should also change that to make sure that both build types get tested.

**Comment by claudioandre** [comment] 2017-12-02 16:11
This is 100% (your) configuration. Changing the subject to:
* Test both gomp and non-gomp builds on non-SIMD targets

**Comment by claudioandre** [comment] 2017-12-02 18:28
> Do I need to do something [...]?

Yes

**Comment by magnumripper** [comment] 2017-12-02 19:23
I looked around in CircleCI web gui and all settings I understand says it should be testing PR's.

**Comment by jfoug** [comment] 2017-12-02 20:29
This is above my grade.  I know little about the CI's, other than some of the scripts run. How they are setup, I am pretty much riding in the dark.  that being said, the 2 big PRs I have, which common-izes the code, have been tested on my end, and have no failures based upon changes in them.     I will hopefully get whatever magic handshake is needed to get the circle working properly for any future PRs from me, and I will also be sure to test non-SIMD both GOMP and non until I know things are working properly/automagically

**Comment by magnumripper** [comment] 2017-12-02 20:35
#metoo. I usually hope for @kholia or @claudioandre to fix the issues 😆

**Comment by kholia** [comment] 2017-12-03 04:37
Maybe https://circleci.com/docs/1.0/fork-pr-builds/ (Building Pull Requests from Forks) can help? I am not sure where the problem is.

![circleci-1-up](https://user-images.githubusercontent.com/79528/33522393-95b52224-d811-11e7-8bb6-0904cad84d44.png)


Make sure that the "Stop Building" status is OK. You need to login to CircleCI first.

**Comment by jfoug** [comment] 2017-12-03 13:28
Ok, here are my advanced settings:
```
GitHub Status updates  :  On
Free and Open Source   :  On 
Build forked pull requests    :   On        (Note, this was one change I made yesterday, but did not change anything)
Pass secrets to builds from forked pull requests   :   Off   (reading message, I am leaving it off)
Only build pull requests   :   On    (I turned this on yesterday, but I think the right choice is off)
Auto-cancel redundant builds (Does not apply to workflows)   :   On
```

I also see the 'stop building' button just like you show above.   BUT it is not building, currently :(

**Comment by kholia** [comment] 2017-12-03 14:09
My values which are different,

```
Build forked pull requests: Off
Only build pull requests: Off
Auto-cancel redundant builds (Does not apply to workflows): Off
```

I am not sure if tweaking these values will work but let's try doing so.

**Comment by jfoug** [comment] 2017-12-03 14:37
That was how all 3 of mine were when I started.  changing them made no difference.  The "Build forked PR" sounds like what should be set ON magnumripper/bleeding-jumbo to simply eliminate the problem, IMHO   That would force that repo to builds forked PR's no matter what the fork owners settings (right or wrong) were, I think.

Yes, the 'only build pr' setting to off to me sounds wrong, BUT I was already not getting any CI work being doneon my repo.

Now, this may stem from the fact I changed my git email address a couple years back from jfoug@cox.net to jfoug@openwall.net   That 'may' have something to do with it, but when i go to circle, click around to the github application, it takes me right to my application page on github, that DOES show the circleCI application as linked and allowed full access to my private data.  So I am not quite sure how to change that IF the email change is enough to confuse circle

**Comment by jfoug** [comment] 2017-12-03 15:27
I think we are getting off track on this topic, I do not believe that both GOMP and non-GOMP builds are being tested within non-SIMD builds.   I believe we are testing only non-GOMP at this time.

@solar pointed out an issue that required testing differences between GOMP and non-GOMP builds.  I am not sure we are testing between the 2.  I know we test non-simd linux32 and non-simd linux64.  But both of those (from makefile.legacy) depend upon the OMPFLAGS value.  In Makefile.legacy, this is always false, so we never test a non-simd GOMP enabled build!  

that was the point of this post.   yes, my PR's are not getting CI testing, but that is a different issue.

@claudioandre did change the title correctly, but then hijacked the thread (and I fell for the bait ;)

The bug IS that there is no GOMP enabled non-simd testing done.

**Comment by claudioandre** [comment] 2017-12-03 22:49
> it takes me right to my application page on github

To check authorized apps on GitHub (log in and):
https://github.com/settings/applications

If CircleCI is listed and you are not confident, revoke the access and sign up on Circle again [1]. Worst case, you revoke all and redo all CI stuff again. It is not hard to sign up using GitHub.
__

See all projects enabled on CircleCI (plus the add project button)
https://circleci.com/projects/gh/jfoug (plus)
https://circleci.com/add-projects/gh/jfoug
__

See what you have built in JtR (public, I can see you did some builds in a remote past) [2]
https://circleci.com/gh/jfoug/JohnTheRipper
************
[1]  Mine
![image](https://user-images.githubusercontent.com/1702923/33530652-15a52b2a-d86a-11e7-8b96-b24dcfaa2b36.png)

[2] What you did last summer
![image](https://user-images.githubusercontent.com/1702923/33530703-0bb04428-d86b-11e7-996c-5702773bde12.png)

**Comment by claudioandre** [comment] 2017-12-03 22:57
> The bug IS that there is no GOMP enabled non-simd testing done.

My tests on Travis:
* I already test SIMD with and without omp
* I already test non SIMD with and without omp

Of course, "upstream" can add all this, but one downside will be "less agility" in CI. Travis allow to 4-6 jobjs running at once. No more than this (for free).

**Comment by jfoug** [comment] 2017-12-03 23:39
@claudioandre are you 100% sure?  I just checked in something which would ONLY fail on GMP enabled non-SIMD code, and it was tested on Travis.  BUT it passed!    So your assumptions may be wrong, or there may have been some other problem.  

But the code passed travis.  several commented on the PR, and were happy.  then Solar listed what he thought was a problem on OMP enabled non-SIMD builds.  I tried to built that way, and sure enough, it WOULD NOT BUILD.   So like I said, there is no way Travis is testing all 4 situations (w - wo SIMD and w - wo gOMP).  This code path (which failed to compile) was ONLY apparent on the non-SIMD but omp enabled.  I had been testing using Makefile.legacy stuff, and it was ONLY doing non-OMP builds, so as soon as I made a new target (I forgot you can simply uncomment the right line to turn on gOMP), and built that way, when it got to the MD5_fmt.c file, the compile failed with variables undefined.  When I rolled back my 'common-gethash.h' code, to the original stuff, it built like a champ.

**Comment by claudioandre** [comment] 2017-12-03 23:45
> @claudioandre are you 100% sure?

**My Travis**, not magnum's.
* "--disable-native-tests CPPFLAGS='-mno-sse2 -mno-mmx -U__SSE__'"
* "--disable-native-tests --disable-openmp CPPFLAGS='-mno-sse2 -mno-mmx -U__SSE__'"

But it only runs when I rebase and push; and I don't do these everyday.

**Comment by claudioandre** [comment] 2017-12-03 23:58
There is another possibility:
- I don't test some formats (approx 20). They are unable to survive when stressed, so I gave up. The bug could be in one of them.

**Comment by jfoug** [comment] 2017-12-04 00:35
The bug was on md5crypt, so I doubt it would have been tested, BUT this PR was pushed to Magnum's, so if his is not setup to test for non-SIMD gOMP enabled, then it was not tested.

**Comment by magnumripper** [comment] 2017-12-07 11:43
> if his is not setup to test for non-SIMD gOMP

You mean OpenMP (OMP), right? Not sure why you started calling it gOMP now (that's just a specific flavor of OpenMP AFAIK and we're not targetting just that one). Anyway, it's not "my" settings, it's in the source tree in `.travis.yml` and `.travis/ subdirectory`.

**Comment by claudioandre-br** [comment] 2018-12-15 18:18
Bug closed as:

* **Low Priority** - They have a tendency to become high priority if enough of the users complain.

* **Business Priority** - Obsolete hardware and software. Hardware nobody owns, etc.

* **WontFix** - Covers all the reasons we chose to close the bug without taking action.
  * Nobody cares.
  * Can't reproduce, working as intended, obsolete.
  * Required information was not provided.

BTW: I do this regularly.

**Closed by claudioandre-br** 2018-12-15 18:18 UTC
Labels: testing
