### ISSUE TITLE
'Need to fix a bug with 32 bit arrays, please contact author...'

### ISSUE THREAD

**Issue by Nightshaxx** [magnumripper/JohnTheRipper#2323] opened 2016-11-10 08:19 UTC
I am trying to recover an excel document password by extracting the hashes with office2john.py. It worked on one of the files I had, but the other gave me an error and told me to contact the author because of a bug with 32bit.

```
[matthewc@matthew-pc Documents]$ ./office2john.py "test.xls"
  File "./office2john.py", line 213
    raise ValueError, 'Need to fix a bug with 32 bit arrays, please contact author...'
                    ^
SyntaxError: invalid syntax

```
​Code it refers to:

```
213 if PY3:
214     from io import BytesIO as StringIO
215 else:
216     from StringIO import StringIO
217
​​218 #[PL] Define explicitly the public API to avoid private objects in pydoc:
219 __all__ = ['OleFileIO', 'isOleFile']
220 
221 #[PL] workaround to fix an issue with array item size on 64 bits systems:
222 if array.array('L').itemsize == 4:
223     # on 32 bits platforms, long integers in an array are 32 bits:
224     UINT32 = 'L'
225 elif array.array('I').itemsize == 4:
226     # on 64 bits platforms, integers in an array are 32 bits:
227     UINT32 = 'I'
228 else:
```

**Comment by kholia** [comment] 2016-11-10 08:31
@Nightshaxx Like I said in the private email, report this bug to the [upstream project](https://bitbucket.org/decalage/olefileio_pl/issues) page. This code is part of the OleFileIO_PL library.

**Comment by kholia** [comment] 2017-01-24 07:01
I cannot reproduce this problem.

@Nightshaxx If you want to get this problem fixed, report this issue to the [upstream project](https://bitbucket.org/decalage/olefileio_pl/issues) along with a reproducer.

I am closing this bug as I am not planning to do anything with it.

**Closed by kholia** 2017-01-24 07:01 UTC
Labels: notes/external issues
