### ISSUE TITLE
cuda compilation error : ../jumbo.h(276): warning: allowing all exceptions is incompatible with previous function "atoll"

### ISSUE THREAD

**Issue by bluerider** [magnumripper/JohnTheRipper#2200] opened 2016-08-09 03:06 UTC
Error when compiling on Centos7 with latest Nvidia cuda drivers. See make and config log below.

[make_log.txt](https://github.com/magnumripper/JohnTheRipper/files/408127/make_log.txt)
[config_log.txt](https://github.com/magnumripper/JohnTheRipper/files/408129/config_log.txt)

**Comment by claudioandre** [comment] 2016-08-11 21:51
This bug report is a duplicate of: #2198 

However, it has more information than the previous errors reported.

**Closed** 2016-08-11 23:11 UTC
