### ISSUE TITLE
Automate generation of JtR-jumbo package for Windows

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#1378] opened 2015-06-03 08:24 UTC
Once we have MinGW builds working, generation of JtR-jumbo Windows package *automatically* should be possible.

**Comment by jfoug** [comment] 2015-06-03 14:06
Ok, if we do this, then what will be built?

SSE2 ?  XOP ?  Some other SIMD ?  Non-SIMD?
OpenMP ?
OpenCL ?
What libs to expect / supply?
What ancillary tools tools also provide?

This is part of the issue with a static build, not done on the proper machine, with proper things installed.  NOTE, windows is NOT like unix, where certain libs can be expected, and expected in pretty standard places.  Also, for unix, one simply does a ./configure and gets all of the nuances handled.

Do not get me wrong, I think this is a fine goal.  But I think in the end, we are going to have to provide a somewhat stripped down and generic version. (I consider base SSE2 to be generic).  Also, expecting perl or python to be working can be pushing it for most windows installs.

This is really why I find cygwin a MUCH better solution.  Relatively easy to install properly, and gives you a true (close to true) posix shell to configure properly.  Also, with cygwin installed, you can change the PATH environment on the windows machine, AND then are able to run john exe's outside of the cygwin shell

**Comment by kholia** [comment] 2015-06-03 14:10
@jfoug yes, I also expect the first generation of this JtR-jumbo package for Windows to be pretty limited / stripped down ;(

This is more of a long-term vision (one of my friends asked me to solve this problem) :)

**Comment by jfoug** [comment] 2015-06-03 17:20
After following the instructions on the cross compile links you provided, I created a new ubuntu 14_04 VM, and put mingw on there. It took a bit to get oSSL installed (damn errors in the .pod files, which I do not care about).  But now I see this problem within config:

```
$ mingw64 ./configure --host=x86_64-w64-mingw32
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-w64-mingw32
checking whether to compile using MPI... no
checking for x86_64-w64-mingw32-gcc... x86_64-w64-mingw32-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
...
config.status: linking x86-64.h to arch.h
config.status: executing default commands
configure: creating ./fmt_externs.h
x86_64-w64-mingw32-cpp: fatal error: too many input files
compilation terminated.
configure: creating ./fmt_registers.h
x86_64-w64-mingw32-cpp: fatal error: too many input files
compilation terminated.
x86_64-w64-mingw32-cpp: fatal error: too many input files
compilation terminated.
x86_64-w64-mingw32-cpp: fatal error: too many input files
compilation terminated.
checking for john.local.conf... not found
configure: creating ../run/john.local.conf (with skeleton sections)

Configured for building John the Ripper jumbo:
```

**Comment by jfoug** [comment] 2015-06-03 18:28
Found the problem.  In ~/bin/mingw64 script (from the cross compiling page)

CPP = x86_64-w64-mingw32-cpp

This has to be 

CPP = x86_64-w64-mingw32-gcc -E

**Comment by magnumripper** [comment] 2015-06-04 00:06
I think we should primarily build a basic 64-bit SSE2 binary with no bells and whistles (most binary distros do it that way). Anything we can link statically should be fine to enable. I'm guessing we can't link OpenCL static.

Was that CPP problem something we need to tweak in autoconf?

**Comment by jfoug** [comment] 2015-06-04 14:05
> Was that CPP problem something we need to tweak in autoconf?

No, it was caused by the helper scripts I found on http://www.tinc-vpn.org/examples/cross-compiling-64-bit-windows-binary/    The script was

```
#!/bin/sh
PREFIX=x86_64-w64-mingw32
export CC=$PREFIX-gcc
export CXX=$PREFIX-g++
export CPP=$PREFIX-cpp
export RANLIB=$PREFIX-ranlib
export PATH="/usr/x86_64-w64-mingw32/bin:$PATH"
exec "$@"
```

I had to change CPP to ```export CPP="$PREFIX-gcc -E"```

**Comment by kholia** [comment] 2015-06-04 14:14
@jfoug it would be great if you can commit, and publish your changes to ".travis.yml" (in a separate branch)!

**Comment by jfoug** [comment] 2015-06-04 14:40
I have not been able to get a mingw build working at all yet.  I can not link, and have not been able to figure out why. I am not sure that I am getting openssl built correctly

**Comment by jfoug** [comment] 2015-06-04 14:55
@kholia can you try to build cross-compile with mingw?  I had to make these changes to get a compile (they are not checked in yet) : 

```diff
diff --git a/src/jumbo.h b/src/jumbo.h
index 7f66b66..bd2159e 100644
--- a/src/jumbo.h
+++ b/src/jumbo.h
@@ -280,16 +280,16 @@ extern long long atoll(const char *);
 extern char *strdup(const char *);
 extern char *strlwr(char *);
 extern char *strupr(char *);
-extern int _strnicmp(const char*, const char *, int);
+//extern int _strnicmp(const char*, const char *, int);
 extern int _strncmp(const char*, const char *);
-extern int _stricmp(const char*, const char *);
+//extern int _stricmp(const char*, const char *);
 extern FILE *fopen64(const char *, const char *);
 extern FILE *fdopen(int, const char *);
-extern int ftruncate(int, int);
+//extern int ftruncate(int, int);
 extern long long ftello64(FILE *);
 extern int fseeko64(FILE *, long long, int);
 extern int fileno(FILE *);
-extern int _exit(int);
+//extern int _exit(int);
 #define off64_t long long
 #undef __STRICT_ANSI__
 #include <sys/file.h>
```

```diff
$ git diff os-autoconf.h
diff --git a/src/os-autoconf.h b/src/os-autoconf.h
index 6c9eebc..f570337 100644
--- a/src/os-autoconf.h
+++ b/src/os-autoconf.h
@@ -49,7 +49,7 @@

 #ifdef NEED_OS_FLOCK

-#if defined (_MSC_VER)
+#if defined (_MSC_VER) || defined (__MINGW32__)
 #define OS_FLOCK                       0
 #else
 #if defined(__APPLE__) && !defined(_DARWIN_C_SOURCE)
```

Also, the makefile made did not have -lssl and -lcrypto added to the libs line (I have not looked into why).  Now, I am not able to correctly link.  I get failures listing that some winsock functions are not found (even though -lws2_32 and -lwsock are there, also, there is an error about a bad reloc address in the libs (ssl and crypto).  I have tried rebuilding a couple times, and still can not get it.

See if you can do better.  If so, possibly all I need is instructions on getting oSSL built and installed properly. I installed ossl using this (to try to integrate it into the system as though it was native)

```
mingw64 ./Configure zlib no-shared --prefix=/usr/x86_64-w64-mingw32 --openssldir=/usr mingw64
```

I have also tried without zlib (default), and also with no-asm   Nothing seems to make any difference.  I have also done a local install, then added those paths into the configure load of jtr.  Same end errors, so for me it is easier to simply try to install the libs 'like' they are native.

**Comment by kholia** [comment] 2015-06-04 15:14
@jfoug I had to do similar changes yesterday, and I am stuck too at the linking stage!

I will give it another go this weekend, thanks for taking a look.

**Comment by jfoug** [comment] 2015-06-04 17:07
I have been able to get a cygwin build working, where only a few dll's have to be used.  I use forced /lib/libssl.a vs -lssl for many of the libs, so that static code gets linked.  This build has quite a few things added (ssl, z, openmp, libdl, libcrypt, libbz2, aes asm, etc).  It is  apretty robust build.

Here is what it looks like, and the 4 DLL's needed.  This was in a CMD.exe shell, with no path entry into my cygwin64 binary directory.

```
C:\projects\phpbb\johnripper\john-1.7.9\bleed64\run\z>dir
 Volume in drive C is OS
 Volume Serial Number is 203A-14B3

 Directory of C:\projects\phpbb\johnripper\john-1.7.9\bleed64\run\z

06/04/2015  12:01    <DIR>          .
06/04/2015  12:01    <DIR>          ..
11/13/2014  04:31            69,149 cyggcc_s-seh-1.dll
04/05/2014  04:20           528,403 cyggmp-10.dll
11/13/2014  04:31            48,669 cyggomp-1.dll
11/13/2014  09:47         3,176,833 cygwin1.dll
06/04/2015  11:58        25,492,883 john.exe
               5 File(s)     29,315,937 bytes
               2 Dir(s)  163,325,300,736 bytes free

C:\projects\phpbb\johnripper\john-1.7.9\bleed64\run\z>john
John the Ripper password cracker, version 1.8.0.5-jumbo-1-bleeding_omp [cygwin 64-bit AVX-autoconf]
Copyright (c) 1996-2015 by Solar Designer and others
Homepage: http://www.openwall.com/john/

Usage: john [OPTIONS] [PASSWORD-FILES]
--single[=SECTION]        "single crack" mode
--wordlist[=FILE] --stdin wordlist mode, read words from FILE or stdin
                  --pipe  like --stdin, but bulk reads, and allows rules
--loopback[=FILE]         like --wordlist, but fetch words from a .pot file
--dupe-suppression        suppress all dupes in wordlist (and force preload)
--prince[=FILE]           PRINCE mode, read words from FILE
--encoding=NAME           input encoding (eg. UTF-8, ISO-8859-1). See also
                          doc/ENCODING and --list=hidden-options.
--rules[=SECTION]         enable word mangling rules for wordlist modes
--incremental[=MODE]      "incremental" mode [using section MODE]
--mask=MASK               mask mode using MASK
--markov[=OPTIONS]        "Markov" mode (see doc/MARKOV)
--external=MODE           external mode or word filter
--stdout[=LENGTH]         just output candidate passwords [cut at LENGTH]
--restore[=NAME]          restore an interrupted session [called NAME]
--session=NAME            give a new session the NAME
--status[=NAME]           print status of a session [called NAME]
--make-charset=FILE       make a charset file. It will be overwritten
--show[=LEFT]             show cracked passwords [if =LEFT, then uncracked]
--test[=TIME]             run tests and benchmarks for TIME seconds each
--users=[-]LOGIN|UID[,..] [do not] load this (these) user(s) only
--groups=[-]GID[,..]      load users [not] of this (these) group(s) only
--shells=[-]SHELL[,..]    load users with[out] this (these) shell(s) only
--salts=[-]COUNT[:MAX]    load salts with[out] COUNT [to MAX] hashes
--save-memory=LEVEL       enable memory saving, at LEVEL 1..3
--node=MIN[-MAX]/TOTAL    this node's number range out of TOTAL count
--fork=N                  fork N processes
--pot=NAME                pot file to use
--list=WHAT               list capabilities, see --list=help or doc/OPTIONS
--format=NAME             force hash of type NAME. The supported formats can
                          be seen with --list=formats and --list=subformats
```

Why are we trying to target mingw as our 'pre-canned' Win32 exe file?  Also note, I can reduce to only 3 DLL's by disabling the GMP.  I think I can reduce to just one, if I also remove OMP.

**Comment by kholia** [comment] 2015-06-04 17:11
@jfoug good question! 

Can we use Cygwin "cross-compiler" under the Travis CI environment? I was planning to use Travis CI to do automated builds for Windows.

The default Travis CI OS (i.e. Ubuntu) sucks when it comes to providing a working MinGW environment.

**Comment by jfoug** [comment] 2015-06-04 17:24
I do not know.  Let me see if I can get cygwin cross under ubuntu. IF that can be done, then we can figure out how to do it on travis.  

How do we get the 'base' VM for travis?   Since cygwin uses an install, it would be nice to be able to provide a pre-built image (I assume Wine).  I doubt we are going to be able to use the apt-get interface to install cygwin properly, BUT if we can just install the cygwin-gcc and libs, 'possibly' we could do that (i.e. using the ubuntu environment to configure and build)

**Comment by jfoug** [comment] 2015-06-05 15:25
@kholia Is there a better distro for cross compiling with mingw64 than ubuntu?  I am using 14_04 Ubuntu, but I could create a VM with any distro if one works better.

**Comment by kholia** [comment] 2015-06-05 16:34
@jfoug Fedora works great for MinGW stuff :-)

"doc/README.MinGW" file has the steps.

**Comment by jfoug** [comment] 2015-06-05 17:57
Ok, here are my notes:

```
Get Fedora v22 workstation live cd  ( https://getfedora.org/en/workstation/ )
Install it.  (I use virtualbox VM)
Setup vbox guest additions:  http://www.binarytides.com/vbox-guest-additions-fedora-20/  This failed for me :(

install needed mingw64 stuff (and a few other things like autoconf and wine)
sudo yum install mingw64-gcc mingw64-gcc-c++ mingw64-openssl mingw64-gmp mingw64-bzip2 autoconf wine

obtain latest jumbo sources from git

*** To build: ***

NOTE, I had to patch configure.ac changing $CPP to $CC -E for the building of the fmt_xxx.h files  then run autoconf to rebuild

mingw64-configure  OPENSSL_LIBS="-lssl -lcrypto"   (instead of ./configure)
edit makefile
 changing AS to use -gcc not -as
 change CPP to "-gcc -E" and not -cp
 change LD to -ld to -gcc
 change strip to be x86_64-w64-mingw32-strip
 Remove the JOHN_SYSTEMWIDE crap from CFLAGSX
make -sj4

Now, there is a ../run/john!!!   Just rename that bugger to john.exe and bingo!

copy the needed DLL files from: /usr/x86_64-w64-mingw32/sys-root/mingw/bin
   zlib1.dll
   libssl-10.dll
   libcrypto-10.dll
   libgmp-10.dll
   libwinpthread-1.dll

It even runs under wine!!!

```

**Comment by jfoug** [comment] 2015-06-05 17:59
Yes it DOES work, but we may have some changes to make. Either 'fixing' the mingw64-configure script suite so that CPP, LD, AS and strip are setup properly, documenting what needs to be 'fixed'.

Or we change the configure steps to make things 'work' correctly.

**Comment by jfoug** [comment] 2015-06-05 19:31
Here is an interesting 'find'.  I found all the static libs (not for gmp however), such as:

mingw64-zlib-static
mingw64-openssl-static
etc

BUT when I build this way, adding the -static flag at proper place on the linkage line, I get the EXACT same problems I was seeing on ubuntu for the static build of oSSL.  It is all the winsock __imp_startup, __imp_WSAsetup, etc type functions.

So this must be some shortcoming within openssl mingw64 build that is NOT properly building the static libs.  Too bad.

I now have a OMP mingw build also.  I had to also load these libs:

mingw64-libgomp   (I also put in mingw64-libbz2)

Once gomp was included there were more .dll's to also use (GOMP is not available in static lib)

The DLL's I now have are:

```
06/05/2015  13:12        12,668,374 john-non-omp.exe
06/05/2015  14:18        13,189,676 john.exe
06/05/2015  14:20            74,849 libbz2-1.dll
06/05/2015  13:12         2,235,392 libcrypto-10.dll
06/05/2015  14:23           501,671 libgcc_s_seh-1.dll
06/05/2015  13:12           467,935 libgmp-10.dll
06/05/2015  14:20           786,457 libgomp-1.dll
06/05/2015  13:12           422,400 libssl-10.dll
06/05/2015  13:12            59,312 libwinpthread-1.dll
06/05/2015  13:12            90,697 zlib1.dll
              10 File(s)     30,496,763 bytes
               2 Dir(s)  152,059,224,064 bytes free
```

The libgomp-1 and libgcc_s_seh-1 dll's were needed.

**Comment by kholia** [comment] 2015-06-05 20:08
@jfoug great! :+1: 

It sucks that Travis CI only supports Ubuntu. I tried finding another CI solution (even Docker based ones, capable of running Fedora), but no luck so far.

**Comment by jfoug** [comment] 2015-06-05 20:22
The problem with Ubuntu, is that we would have to install mingw64, then pull source for libz and build/install and pull source for oSSL and build/install.  The ossl build is about 20 minutes just itself.  That's pretty ugly.  Of course, we could easily do all of this with a script, BUT are we buying ourselves anything?

I will test ubuntu by building a dynamic oSSL, installing that, and seeing if the mingw64 build works after that.  That may be the 'only' thing failing on Ubuntu, since I saw the same link errors with Fedora when doing a static link.

**Comment by jfoug** [comment] 2015-06-05 21:18
With wine installed, I no longer get cross compiling :(  I have to figure some way around that

**Comment by kholia** [comment] 2015-06-05 21:20
@jfoug yeah, wine causes crazy problems during the cross-compilation process.

Maybe disabling the "binfmt_misc" kernel module will help?

**Comment by jfoug** [comment] 2015-06-05 21:28
I just uninstalled wine for now.

**Comment by jfoug** [comment] 2015-06-05 21:36
Ok, I now have Ubuntu building john, after making the dynamic ossl.

Here was my configure line for oSSL

CROSS_COMPILE=x86_64-w64-mingw32- ./Configure no-static shared --prefix=/usr/x86_64-w64-mingw32 --openssldir=/usr mingw64

It still builds a static.  I get a long warning about putting DLL's into a non-standard location, so I am not 100% sure things are perfect.

But it DID build a ../run/john executable which we were not able to get to link prior to this on ubuntu.

**Comment by kholia** [comment] 2015-06-05 21:39
@jfoug cool!

The next step would be to get this working within the Travis CI environment.

https://github.com/kholia/JohnTheRipper/tree/Travis+MinGW is what I was doing, before I ran into those linking problems.

**Comment by jfoug** [comment] 2015-06-05 21:54
Try changing this:

```
sed -i 's/:.dll.a/ -Wl,--export-all -shared:.dll.a/g' Configure
sed -i 's,.*target already defined.*,$target=$_;,g' Configure
mingw64 ./Configure --openssldir=$HOME/mingw64/usr/local mingw64
mingw64 make
mingw64 make install
```

to this:

```
CROSS_COMPILE=x86_64-w64-mingw32- ./Configure no-static shared --openssldir=$HOME/mingw64/usr/local mingw64
mingw64 make
mingw64 make install_sw
```

**Comment by kholia** [comment] 2015-06-06 12:00
@jfoug I am now stuck at "aes/aes.a: could not read symbols: Archive has no index; run ranlib to add one" error message.

See https://travis-ci.org/kholia/JohnTheRipper/builds/65681704 for the details.

What is the real problem here? Old toolchain?

**Comment by jfoug** [comment] 2015-06-06 13:07
The right ranlib must be run. All build tools must be mingw64 stuff. Can you run make without -s and see if it shows which took is used

**Comment by kholia** [comment] 2015-06-06 13:10
@jfoug "/usr/bin/ar" is being used, which is not right at all!

Also, it seems that we don't propagate "AR" environment variable (if set) to src/Makefile and src/aes/Makefile. I am trying to fix this problem now, but no luck so far.

**Comment by jfoug** [comment] 2015-06-06 13:22
In my good builds, AR env var was set before calling configure and make

**Comment by kholia** [comment] 2015-06-06 13:24
@jfoug running "mingw64 ./configure --host=x86_64-w64-mingw32" is overwriting the "AR" value (which is currently set by the mingw64 script).

**Comment by kholia** [comment] 2015-06-06 13:38
https://github.com/magnumripper/JohnTheRipper/commit/8bff8a623639cd496bfc46a71b2e52e8bdc35079 has fixed this "ar" problem. Moving on!

**Comment by kholia** [comment] 2015-06-06 13:44
MinGW builds are now working (thanks to @jfoug for doing the heavy lifting)/

The next steps are testing, and automated publishing of the build artifacts.

http://docs.travis-ci.com/user/deployment/releases/ might be helpful :)

**Comment by jfoug** [comment] 2015-06-08 14:36
I think we are really close now.  After I fixed my strip (not 100% needed, but is important), I am able to do a ```git pull``` followed by a valid JtR build cross compiling on Ubuntu64.

Here is the additional inforamation:

```
cat ~/bin/mingw64

mingw64 ./configure OPENSSL_LIBS="-lssl -lcrypto" --host=x86_64-w64-mingw32
mingw64 make -sj4
mv ../run/john ../run/john.exe
```

The file made is john, not john.exe since we are 'building' under ubuntu, even though cross compiling.  I think we can fix that, but I have not looked into it.  Since we 'know' the behavior, it really is not all that important.

**Comment by kholia** [comment] 2015-06-08 18:18
@jfoug thanks! I have merged these changes into the https://github.com/kholia/JohnTheRipper/tree/MinGW branch. 

The PR is at https://github.com/magnumripper/JohnTheRipper/pull/1416 URL.

**Comment by kholia** [comment] 2015-06-08 18:30
@jfoug I still need to figure out how to locate, and copy those .dll files (in an Ubuntu based MinGW setup), which are required for running "john.exe".

**Comment by jfoug** [comment] 2015-06-08 18:30
I notice that you have a complete unique .travis.yml file.      Do you have any plans on how to do this 'for real' ?    Are we going to create a 2nd travis environment for this?  So travis #1 works just like it does today with travis #2 being only a mingw build?

**Comment by kholia** [comment] 2015-06-08 18:32
@jfoug take a look at https://github.com/kholia/JohnTheRipper/blob/MinGW/.travis.yml :)

It's ugly but it works fine.

**Comment by jfoug** [comment] 2015-06-08 18:33
The ossl files that my 'depends' link to are NOT from the mingw build. They are the oSSL for windows DLL's (very fast build), that I have installed.
 
We can work on the 'test' phase later.  We will have to build.  Then install wine, then run.  We may just have to wget DLL's from somewhere.  They may also be 'somewhere' in the ossl build  (as a .so???, that simply need to be renamed something like LIBEAY32.dll and SSLEAY32.dll

**Comment by jfoug** [comment] 2015-06-08 18:35
Yes I had already looked at your .travis.yml file.  I see only mingw in there.

**Comment by kholia** [comment] 2015-06-08 18:37
https://github.com/kholia/JohnTheRipper/blob/MinGW/.travis.yml#L35 (this does the regular Linux build, and testing)

https://github.com/kholia/JohnTheRipper/blob/MinGW/.travis.yml#L41 (this does the MinGW build)

**Comment by jfoug** [comment] 2015-06-08 19:52
Ok, to get clang to work, try this:

1. put back the comment out clang
2. cut all items from the script section and put into a file called travis-cc.sh in ./src
3. script now becomes cd src && ./travis-cc.sh

Now within the script, we always do the first line (minus the cd). This builds and tests gcc and clang.

Then we place an IF into the script, and the rest of the commands go into an if block.  Those commands are only executed if we are in a GCC building environment (I think there are env vars listing this).

Doing this, we should be able to get all 3 environments working (I think).

**Comment by kholia** [comment] 2015-06-08 20:52
@jfoug this idea works great :+1:

**Comment by jfoug** [comment] 2015-06-08 21:00
Ok, now with that change, we have 2 new scripts, a modified .travis.yml, and it looks like pretty much everything is running fine. We do install too much on the clang VM, but I think the only way around that, is to make changes to the script to do the installs.  I bet the installs are not that huge of an issue (I would think not), but they might be.

It would make sense to ask if some of these things could be installed on the default VM.  They do update that every couple of months. I would think having a mingw64 cross compiler would be something they could advertise.  It can not just be our project that needs this functionality (Windoze build testing).

But as it stands, I think this is getting close to not being a POC.

**Comment by kholia** [comment] 2015-06-09 11:36
@jfoug I have a feeling that you will like the https://github.com/kholia/JohnTheRipper/releases/ page.

Check out the "JtR-MinGW.zip" file :)

**Comment by kholia** [comment] 2015-06-09 11:37
The build crashes on some formats (under Windows 8.1 64-bit) but things are good, in general :)

**Comment by jfoug** [comment] 2015-06-09 15:11
The ONLY dll's you need to include are:

libeay32.dll
ssleay32.dll

All others have no usage by any of the exe files.

NOTE, I am not sure why we are crashing. I was not getting crashes, IIRC

I am getting a ton of formats coring.  md5crypt, dynamic_0, dynamic_1, dynamic_2 (I gave up).  Something is very wrong.

**Comment by kholia** [comment] 2015-06-10 01:27
This ticket is largely solved in commit 0387122fa582a0b509f69a15b085b58afd30835f (merged now!).

The next steps would be to make sure that the builds don't crash, and to package everything up more nicely using NSIS / pynsist.

**Comment by kholia** [comment] 2015-06-10 03:38
@jfoug the crashes seem to be caused by the super old MinGW toolchain, and getting the new MinGW toolchain on Ubuntu 12.04 (Travis CI OS) seems to be tricky.

**Comment by jfoug** [comment] 2015-06-10 15:53
Ok, I thought my mingw builds (under ubuntu) were working, but they are not.  They fail also :(

**Comment by jfoug** [comment] 2015-06-10 15:54
We might check to see if mingw-32 works.

**Comment by jfoug** [comment] 2015-06-10 16:08
Too bad we could not leverage Fedora. I did test the exe built there, and it was fine.

**Comment by kholia** [comment] 2015-06-10 17:23
@jfoug I am taking a look at CircleCI (https://circleci.com/) now. Maybe it will solve all our problems (TM).

**Comment by jfoug** [comment] 2015-06-10 19:39
https://circleci.com/docs/environment  Uses 12_04 ubuntu as the base VM

**Comment by kholia** [comment] 2015-06-10 19:41
@jfoug CircleCI supports Docker, and I have a Fedora based Dockerfile for JtR almost ready :)

I just need to spend some time getting familiar with CircleCI's Docker environment.

**Comment by jfoug** [comment] 2015-06-10 20:02
What is docker, another VM?  So we run a OS in a VM inside another VM, lol

**Comment by kholia** [comment] 2015-06-10 20:06
@jfoug don't even go into that discussion :|

![image](https://cloud.githubusercontent.com/assets/79528/8092828/f3c9dc1c-0fbc-11e5-92d6-6d354da06463.png)

**Comment by kholia** [comment] 2015-06-10 20:09
@jfoug the binaries built by Fedora's MinGW work like a champ (including OMP) :+1:

**Comment by jfoug** [comment] 2015-06-11 15:59
Once we release, we need to compare speed (oSSL speeds), from the build to the DLL's from here:  

http://slproweb.com/products/Win32OpenSSL.html

I find those DLL's to be about optimal for speed, but I would like to compare to the speed we get on the Fedora build

**Comment by magnumripper** [comment] 2015-06-11 18:53
I've seen sites having a very hard time recovering from a power outage because servers that were needed for booting the physical servers were moved into VMs running on them :dizzy_face:

**Comment by jfoug** [comment] 2015-06-21 23:40
I worked to get a 'clean' mingw64 build.  It ONLY requires LIBEAY32.DLL and SSLEAY32.DLL files (and windows system dll's).  It does not do OMP (libgomp-1.dll is required for that). Thus, there are NO dll's built from MinGW64.  However, the exe still crashes :-1: 

@kholia, since you put a Fedora VM onto a VM inside of CircleCI, I wonder if we could do the same with a Win7 VM with cygwin-64 installed???  If so, I KNOW that cygwin64 works like a champ.  Yes, we would have to release DLL's, but, .....      I am just not sure of all the ramifications of doing this.

**Comment by kholia** [comment] 2015-06-22 10:52
I don't think that CircleCI supports Windows VMs. I will double check this.

**Comment by jfoug** [comment] 2015-07-05 23:28
Have we found out anything new on this one?  It sux that the Mingw64 cross compiled build works like a champ in wine on the build box, but fails terribly in windows environment.

**Comment by kholia** [comment] 2015-07-06 14:05
No luck, I haven't looked at this stuff in a long while.

**Comment by jfoug** [comment] 2015-07-06 16:18
How was this URL setup, and work?  http://daily-builds.appspot.com/latest

I know it goes to circleci to grab a build.  I was wondering if it would be possible to setup a box to simply query git on a timer (4 times a day or so), and if there is new git items, simply pull them, then build and package and ftp upload the final package to some site.  I could script something like that pretty easily. That way we would get a WORKING Win32/64 set of files.

**Comment by jfoug** [comment] 2015-07-06 20:44
This is in x86-64.S   

```C
#if defined (_WIN64) || defined (__CYGWIN64__)
/*
 * MS use a different x64 calling convention than everyone else:
 * Arguments: RCX, RDX, R8, R9 then stack right-to-left.
 * Volatile: RAX, RCX, RDX, R8, R9, R10, R11, XMM0:XMM5
 * Non-volatile: RBX, RBP, RSI, RDI, R12:R15, XMM6:XMM15
 * Return: RAX.
 */
```

I wonder if things like this are part of the problem.  I would be 100% certain that mingw-64 would need to use the same windows-x64 ABI  If Mingw-64 does not define _WIN64, then we are in trouble here.  ALSO, there may be other locations within JtR code that is like this, where we MUST also do special coding for MinGW-64.

**Comment by jfoug** [comment] 2015-07-06 21:34
I have this script, and it builds wonderfully, and fully runable exe's

```sh
 #!/bin/sh

BIT=64

cd /c/projects/phpbb/johnripper/auto${BIT}
rm -f jrt-bleed*.zip

VAR=`git pull`
if [ "x$VAR" = "xAlready up-to-date." ]
then
  exit 1
fi

cd src
make -s clean
CPPFLAGS="-mno-avx" ./configure -C --disable-opencl
make -sj3

../run/john
if [ ! "x$?" = "x0" ]
then
  cd ..
  rm -f jtr-bleed-cygwin*.zip
  cd src
  make -s clean
  cd ..
  exit 1
fi

cd ..
mkdir pkg
cd pkg
mkdir run
cp -R ../run/* run
mkdir doc
cp -R ../doc/* doc
cp ../RE* .
cp -p /usr/bin/cygbz2-1.dll run
cp -p /usr/bin/cygcrypt-0.dll  run
cp -p /usr/bin/cygcrypto-1.0.0.dll  run
cp -p /usr/bin/cygwin1.dll  run
cp -p /usr/bin/cyggmp-10.dll  run
cp -p /usr/bin/cygsll-1.0.0.dll  run
cp -p /usr/bin/cygz.dll  run
cp -p /usr/bin/cygcc_s_seh-1.dll  run
cp -p /usr/bin/cyggomp-1.dll  run
zip -rm ../jtr-bleed-cygwin${BIT}-omp.zip *

cd ../src

make -s clean

cd ..
rmdir pkg
# now curl the zip file somewhere, and then delete them.
```

**Comment by magnumripper** [comment] 2015-07-06 23:02
> This would work fine, if I had somewhere to upload the files to.

I guess you could upload to http://openwall.info/wiki/john/custom-builds using curl or something.

**Comment by magnumripper** [comment] 2015-07-06 23:07
> This is in x86-64.S   

> ```C
#if defined (_WIN64) || defined (__CYGWIN64__)
/*
 * MS use a different x64 calling convention than everyone else:
 * Arguments: RCX, RDX, R8, R9 then stack right-to-left.
 * Volatile: RAX, RCX, RDX, R8, R9, R10, R11, XMM0:XMM5
 * Non-volatile: RBX, RBP, RSI, RDI, R12:R15, XMM6:XMM15
 * Return: RAX.
 */
```

MinGW gcc is supposed to define `_WIN64`

**Comment by jfoug** [comment] 2015-07-07 03:18
Ok, BUT there may be other things that are _MSC_VER || __CYGWIN__   or just _MSC_VER That was my point.    Whatever is going wrong, was not a problem when I was building mingw-32, but now when we are trying mingw-64, something is very wrong.

**Comment by jfoug** [comment] 2015-07-07 03:20
>>    This would work fine, if I had somewhere to upload the files to.

> I guess you could upload to http://openwall.info/wiki/john/custom-builds using curl or something.

I plan on curl, but I would really like to be able to also delete. I would like to keep only a 'current' version (or possibly 2).  These are 35+mb, and if I do a 32 bit (sse2) and a 64 bit SSE4.1 build, then that is 50mb each build.  I do not think we can clean up on the wiki, so if there are 50 builds a week, that is 2.5gb   I think Solar might complain after a few years, lol.

**Comment by kholia** [comment] 2015-07-08 11:01
The mystery around the crash deepens,

```
john.exe --test --format==wbb3  # passes!

john.exe --test --format==ssh-ng  # passes!

john.exe --test --format==ssh  # passes!

john.exe --test --format==net-md5  # fails!
```

All these runs were done on a Windows 8.1 64-bit machine. My current hypothesis is that anything which uses ``dynamic`` format stuff, will crash.

I am trying to use https://github.com/jrfonseca/drmingw to narrow this down now (I don't have much hope though!).

**Comment by kholia** [comment] 2015-07-08 11:19
```

john.exe --test --format==net-md5  # fails!

Unhandled exception at 0x00007FFB335E0F20 (ntdll.dll) in john.exe: 0xC0000374: A heap has been corrupted (parameters: 0x00007FFB3361DD40).
```

The following patch "fixes" this crash,

```
diff --git a/src/net_md5_fmt_plug.c b/src/net_md5_fmt_plug.c
index 1d2c0fe..10fdcac 100644
--- a/src/net_md5_fmt_plug.c
+++ b/src/net_md5_fmt_plug.c
@@ -388,7 +388,7 @@ static void done(void)
 {
        MEM_FREE(crypt_out);
        MEM_FREE(saved_key);
-       pDynamicFmt->methods.done();
+       // pDynamicFmt->methods.done();
 }
 
 #endif /* plugin stanza */
```

``md5crypt`` seems to be crashing for a different reason, looking into that one now.

**Comment by kholia** [comment] 2015-07-08 11:36
The following patch fixes the ``md5crypt`` crash (similar idea),

```
diff --git a/src/MD5_fmt.c b/src/MD5_fmt.c
index c777164..48c0cfa 100644
--- a/src/MD5_fmt.c
+++ b/src/MD5_fmt.c
@@ -115,10 +115,10 @@ static void init(struct fmt_main *self)
 
 static void done(void)
 {
-#ifdef SIMD_PARA_MD5
+/* #ifdef SIMD_PARA_MD5
        MEM_FREE(sout);
 #endif
-       MEM_FREE(saved_key);
+       MEM_FREE(saved_key); */
 }
 
 static int get_hash_0(int index)
```

**Comment by magnumripper** [comment] 2015-07-08 12:15
I'm pretty sure those fixes are mere workaround hacks that will lead to other problems.

**Comment by kholia** [comment] 2015-07-08 12:16
@magnumripper agreed! we need to nail down the real root cause.

**Comment by magnumripper** [comment] 2015-07-08 12:19
I'm not sure `-DDYNAMIC_DISABLED` works as it should right now (it should be fixed if not). You could try a build using that and see what happens.

eg `./configure CPP=-DDYNAMIC_DISABLED`

**Comment by magnumripper** [comment] 2015-07-08 12:42
Feck it's totally broken. I'm on it.

**Comment by magnumripper** [comment] 2015-07-08 12:49
da2e752 fixes `./configure CPPFLAGS=-DDYNAMIC_DISABLED`

**Comment by jfoug** [comment] 2015-07-30 02:04
I just got a new Fedora VPS, so I will see about setting this up. Heck, I might even build our own 'custom' CI like environment, lol.

**Comment by jfoug** [comment] 2015-08-04 04:23
I am getting close to having this one done, with an automatic 'gitcheck, gitpull, configure, make, -test=0, zip, deploy' script.  The build is done with Cygwin64.  I simply have a script that monitors git every 2 minutes, and if there is anything new, it pulls, and builds 2 times (one pure SSE2 and one XOP, I want a 3rd that is AVX2, but I will have to figure out how to build that way on a non-AVX2 cygwin box).  Each of those are zip'd, into an only exe files zip.  There is also a 'base' zip, that contains ./docs ./run (except the exe files), and the needed cygwin dll's.

I will play with it a bit more, but I think this is very close to release ready.

**Comment by magnumripper** [comment] 2016-08-18 22:39
I believe this is in place

**Closed by magnumripper** 2016-08-18 22:39 UTC
Labels: enhancement, non-trivial, testing
