### ISSUE TITLE
Various bitlocker issues

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2512] opened 2017-04-21 07:16 UTC
```
Benchmarking: BitLocker, BitLocker [Iterated-SHA256 AES 64/64]... (8xOMP) DONE
Speed for cost 1 (iteration count) of 1048576
Raw:	8.2 c/s real, 1.0 c/s virtual

Device 2: GeForce GT 650M
Benchmarking: bitlocker-opencl [PBKDF2-SHA256 AES OpenCL]... DONE
Speed for cost 1 (iteration count) of 10
Raw:	15.4 c/s real, 304 c/s virtual
```
1. Algo name should (afaik) not be PBKDF2. I think both should be just "SHA256 AES". We usually don't say "iterated".

2. Iteration count differs between CPU and OpenCL. Is that correct (as in different test vectors) or is one of them wrong?

**Comment by kholia** [comment] 2017-04-21 08:15
1. Isn't `Iterated-SHA256 AES` more informative than simply saying `SHA256 AES`?

2. `opencl_bitlocker_fmt_plug.c` contains the following code which is obviously not correct,

```
static unsigned int iteration_count(void *salt)
{
        //return randoms num
        return 10;
}
```

**Comment by kholia** [comment] 2017-04-21 08:17
While the iteration count is fixed in BitLocker, it is good to have the fixed value as part of the hash format itself for future expandability purposes.

**Comment by magnumripper** [comment] 2017-04-24 21:47
Only the iteration count (in the OpenCL version) remains now. And it'll be fixed just by starting to use the function provided in bitlocker_common.h

**Comment by kholia** [comment] 2017-05-13 16:41
@e-ago Hi! Can you please take care of this last remaining problem?

**Comment by e-ago** [comment] 2017-05-15 17:00
@magnumripper @kholia done: I've opened a new pull request ( https://github.com/magnumripper/JohnTheRipper/pull/2546 ) Can you merge only the last commit?

**Comment by magnumripper** [comment] 2017-05-16 07:04
#2546 doesn't make sense. The common function uses a struct that your code doesn't use. It will never report right.

What also needs to be done is:
1. Start using `bitlocker_common_get_salt()` instead of the weird strcpy `get_salt()` we have now.
2. Change your `set_salt()` accordingly (*use the values from the struct, no re-parsing so much simpler code*)

**Comment by e-ago** [comment] 2017-05-17 13:59
I'm sorry, I committed the wrong version of the file.
Anyway I've applied also the changes suggested by @magnumripper , removing my get_salt(), cleaning my set_salt() and using the bitlocker_common_get_salt() function.
This new version successfully find "password@123" with the minimalistic test image.
Please let me know if there is some other issue in this version.

I still need to improve the size of the input password (more than 16 characters) and performance: with my original standalone version I reached up to more than 300 p/s on a Tesla K80, while with john ( main kernel splitted) the rate is about 140 p/s

**Comment by magnumripper** [comment] 2017-05-17 19:19
> with my original standalone version (main "big" kernel) the password rate was about 300 p/s on a Tesla K80, while with john ( main kernel splitted ) the rate is about 140 p/s

That's strange. There's definitely nothing in JtR's design that would explain this.

**Comment by claudioandre** [comment] 2017-05-17 20:00
This is expected. On super, I was able to gain (without effort) 200 p/s: from 601 to 808. The problem is:
* I run a test or test-full on well (while testing something) recently. It is, already, devastating (in terms of time on a test run) for weak boards. Should we make it even harder/demanding?

That said, for testing purposes at least, we can try GWS\*2 and GWS\*4 to see how it behaves on e-ago's hardware.

**Comment by magnumripper** [comment] 2017-05-17 20:08
Oh, right. Our GWS is held down by auto-tune for keeping a sane total crypt_all() duration. That's probably the full answer.

We'll need to solve that issue in Jumbo core sooner or later and then bitlocker will get better with little or no change.

**Closed** 2017-05-18 13:17 UTC
Labels: Maintenance/cleanup

**Comment by magnumripper** [comment] 2017-05-18 13:29
> with my original standalone version (main "big" kernel) the password rate was about 300 p/s on a Tesla K80, while with john ( main kernel splitted ) the rate is about 140 p/s

This patch...
```diff
$ git diff
diff --git a/src/opencl_bitlocker_fmt_plug.c b/src/opencl_bitlocker_fmt_plug.c
index f84b1e9..272a2c1 100644
--- a/src/opencl_bitlocker_fmt_plug.c
+++ b/src/opencl_bitlocker_fmt_plug.c
@@ -334,7 +334,7 @@ static void reset(struct db_main *db)
                // Auto tune execution from shared/included code.
                autotune_run(self, HASH_LOOPS * ITERATIONS, 0,
                             (cpu(device_info[gpu_id]) ?
-                             1000000000 : 10000000000ULL));
+                             1000000000 : 200));
        }
 }
 
```
...will tell auto-tune to tune for a max. of 200 ms *single kernel-call duration* instead of a max. of 10 seconds *total crypt_all()* duration (which is only 2.4 ms per call at best). The result ought to be a lot better performance but very VERY slow response because we'll get up to **13 minutes** of total crypt_all duration. If you try it and be patient, it should show some good speed once it gets past self-tests, runs for some time and eventually responds to a status request...

The problem is not your format, it's that Jumbo isn't quite designed for this extreme situation. I'm still trying to figure out what to do about it (@solardiz, any ideas?) but it'll be in core code and once we fix it, your format will perform better.
