### ISSUE TITLE
VTP to john format

### ISSUE THREAD

**Issue by Percent01** [magnumripper/JohnTheRipper#1620] opened 2015-08-06 22:44 UTC
I think the following python script doesn't work correctly when I would like to export vtp md5 digest from pcap file to john format:
pcap2john.py

I uploaded my wireshark dump with 1 vtp advertisement message: http://s000.tinyupload.com/?file_id=7326498926501755828
Somebody could provide a sample pcap file to test again the pcap2john.py python script?!

**Comment by kholia** [comment] 2015-08-06 23:41
@Percent01 https://github.com/kholia/my-pcaps has sample .pcap files.

**Comment by Percent01** [comment] 2015-08-07 06:02
Is it the correct output for this pcap file?
wget https://github.com/kholia/my-pcaps/raw/master/VTP/20-0.0-1412865365.pcap

./pcap2john.py 20-0.0-1412865365.pcap 
1487:$vtp$2$196$14000107000105dc000186a164656661756c740014000105000505dc000186a56368656e6100000010000103000605dc000186a6666666001800020c03ea05dc00018a8a666464692d64656661756c743000030d03eb117800018a8b74726372662d64656661756c7400000001010ccc040103ed0701000208010007090100072000040f03ec05dc00018a8c666464696e65742d64656661756c7400030100012400050d03ed117800018a8d74726272662d64656661756c740000000201000f03010002$80$0201010c646f6d61696e313233343536000000000000000000000000000000000000000000000015000000003134313030393134333631376010913064949d6f47a53b2ad68ef06b0000000106010002$6010913064949d6f47a53b2ad68ef06b


When I open this pcap file with wireshark I realize this information:
Version: 2
Management Domain Length: 12
vtp domain: domain123456
vtp md5 digest: 1d414242bffb0f6a409fb8416a1faf99

**Comment by kholia** [comment] 2015-08-29 12:24
VTP parsing needs to be enhanced a bit to fix this. However, it will be a long while before I get to this problem.

**Comment by kholia** [comment] 2015-08-29 12:28
https://github.com/kholia/my-pcaps/ has all the information (if someone else is interested in solving this).

**Comment by kholia** [comment] 2016-02-13 18:29
The original problematic .pcap file isn't downloadable anymore, and I don't remember what this bug was about.

What should we do? Close this bug?

**Comment by magnumripper** [comment] 2016-02-13 20:21
I don't seem to have that file either.

**Comment by kholia** [comment] 2016-03-13 10:42
I had a quick chat with the bug reporter and he is unable to reproduce this issue himself, hence closing this bug.

**Closed by kholia** 2016-03-13 10:42 UTC
Labels: New format
