### ISSUE TITLE
lotus5-opencl fails on super

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#2048] opened 2016-02-14 20:40 UTC
This is with `scl enable devtoolset-3 bash`:

The error doesn't occur when I test lotus5-opencl individually.

```
[frank@super run]$ ./john --test --format=lotus5-opencl
Device 6: GeForce GTX TITAN X
Benchmarking: lotus5-opencl, Lotus Notes/Domino 5 [OpenCL]... DONE
Raw:	23150K c/s real, 20487K c/s virtual

[frank@super run]$ ./john --test=0 --format=lotus5-opencl
Device 6: GeForce GTX TITAN X
Testing: lotus5-opencl, Lotus Notes/Domino 5 [OpenCL]... PASS
[frank@super run]$ ./john --test=0 --format=opencl
Device 6: GeForce GTX TITAN X
Testing: sha1crypt-opencl, (NetBSD) [PBKDF1-SHA1 OpenCL]... PASS
Testing: oldoffice-opencl, MS Office <= 2003 [MD5/SHA1 RC4 OpenCL]... PASS
Testing: PBKDF2-HMAC-MD4-opencl [PBKDF2-MD4 OpenCL]... PASS
Testing: PBKDF2-HMAC-MD5-opencl [PBKDF2-MD5 OpenCL]... PASS
Testing: PBKDF2-HMAC-SHA1-opencl [PBKDF2-SHA1 OpenCL]... PASS
Testing: rar-opencl, RAR3 (length 5) [SHA1 OpenCL AES]... (32xOMP) PASS
Testing: RAR5-opencl [PBKDF2-SHA256 OpenCL]... PASS
Testing: truecrypt-opencl, TrueCrypt AES256_XTS [RIPEMD160 OpenCL]... (32xOMP) PASS
Testing: lotus5-opencl, Lotus Notes/Domino 5 [OpenCL]... OpenCL CL_INVALID_COMMAND_QUEUE error in opencl_lotus5_fmt_plug.c:300 - Shit hit fan
```

**Comment by frank-dittrich** [comment] 2016-02-14 21:15
With --device=0, lotus5-opencl passes self test on super (even with --format=opencl, i.e., testing all opencl formats).

**Comment by magnumripper** [comment] 2016-02-14 21:49
See also #1726

**Comment by magnumripper** [comment] 2016-08-18 21:36
This is just a dupe of (current state of) #1726

**Closed by magnumripper** 2016-08-18 21:36 UTC
Labels: bug
