### ISSUE TITLE
Consider using Judy array for OpenCL formats

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1761] opened 2015-09-13 23:04 UTC
http://www.openwall.com/lists/john-dev/2015/09/12/12

**Comment by claudioandre-br** [comment] 2018-12-15 18:31
Bug closed as:

* **Low Priority** - They have a tendency to become high priority if enough of the users complain.

* **Business Priority** - Obsolete hardware and software. Hardware nobody owns, etc.

* **WontFix** - Covers all the reasons we chose to close the bug without taking action.
  * Nobody cares.
  * Can't reproduce, working as intended, obsolete.
  * Required information was not provided.
****
BTW: when I implemented Bloom Filter I considered Judy not suitable for GPUs.

**Closed by claudioandre-br** 2018-12-15 18:31 UTC
Labels: enhancement

**Comment by solardiz** [comment] 2018-12-15 18:33
Related: @alainesp's https://github.com/alainesp/Practical_Research/blob/master/research_cuckoo_cbg.md
