### ISSUE TITLE
Several formats FAILED (plaintext_length) in --stress-test

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1235] opened 2015-04-28 00:26 UTC
The first iteration succeeds, but the others fail.
```
[fd@f22b run]$ ./john --stress-test=0 --format=for* |head
Will run 4 OpenMP threads
Testing: Fortigate, FortiOS [SHA1 256/256 AVX2 8x2]... (4xOMP) PASS
Testing: FormSpring [sha256($s.$p) 256/256 AVX2 8x]... (4xOMP) PASS
All 2 formats passed self-tests!
Testing: Fortigate, FortiOS [SHA1 256/256 AVX2 8x2]... (4xOMP) PASS
Testing: FormSpring [sha256($s.$p) 256/256 AVX2 8x]... (4xOMP) FAILED (plaintext_length)

1 out of 2 tests have FAILED
Testing: Fortigate, FortiOS [SHA1 256/256 AVX2 8x2]... (4xOMP) PASS
Testing: FormSpring [sha256($s.$p) 256/256 AVX2 8x]... (4xOMP) FAILED (plaintext_length)
$ ./john --stress-test=0 --format=formspring |grep "^Testing:"|head -n 3
Testing: FormSpring [sha256($s.$p) 256/256 AVX2 8x]... (4xOMP) PASS
Testing: FormSpring [sha256($s.$p) 256/256 AVX2 8x]... (4xOMP) FAILED (plaintext_length)
Testing: FormSpring [sha256($s.$p) 256/256 AVX2 8x]... (4xOMP) FAILED (plaintext_length)
$ ./john --stress-test=0 --format=hMailServer |grep "^Testing:"|head -n 3
Testing: hMailServer [sha256($s.$p) 256/256 AVX2 8x]... (4xOMP) PASS
Testing: hMailServer [sha256($s.$p) 256/256 AVX2 8x]... (4xOMP) FAILED (plaintext_length)
Testing: hMailServer [sha256($s.$p) 256/256 AVX2 8x]... (4xOMP) FAILED (plaintext_length)
$ ./john --stress-test=0 --format=MediaWiki |grep "^Testing:"|head -n 3
Testing: MediaWiki [md5($s.md5($p)) 256/256 AVX2 8x3]... (4xOMP) PASS
Testing: MediaWiki [md5($s.md5($p)) 256/256 AVX2 8x3]... (4xOMP) FAILED (plaintext_length)
Testing: MediaWiki [md5($s.md5($p)) 256/256 AVX2 8x3]... (4xOMP) FAILED (plaintext_length)
$ ./john --stress-test=0 --format=md5ns |grep "^Testing:"|head -n 3
Testing: md5ns, Netscreen [md5($s.$p) (OSC) (PW > 31 bytes) 256/256 AVX2 8x3]... (4xOMP) PASS
Testing: md5ns, Netscreen [md5($s.$p) (OSC) (PW > 31 bytes) 256/256 AVX2 8x3]... (4xOMP) FAILED (plaintext_length)
Testing: md5ns, Netscreen [md5($s.$p) (OSC) (PW > 31 bytes) 256/256 AVX2 8x3]... (4xOMP) FAILED (plaintext_length)
$ ./john --stress-test=0 --format=osc |grep "^Testing:"|head -n 3
Testing: osc, osCommerce [md5($s.$p) (OSC) 256/256 AVX2 8x3]... (4xOMP) PASS
Testing: osc, osCommerce [md5($s.$p) (OSC) 256/256 AVX2 8x3]... (4xOMP) FAILED (plaintext_length)
Testing: osc, osCommerce [md5($s.$p) (OSC) 256/256 AVX2 8x3]... (4xOMP) FAILED (plaintext_length)
$ ./john --stress-test=0 --format=phpass |grep "^Testing:"|head -n 3
Testing: phpass ($P$9) [phpass ($P$ or $H$) 128/128 AVX2 8x3]... (4xOMP) PASS
Testing: phpass ($P$9) [phpass ($P$ or $H$) 128/128 AVX2 8x3]... (4xOMP) FAILED (plaintext_length)
Testing: phpass ($P$9) [phpass ($P$ or $H$) 128/128 AVX2 8x3]... (4xOMP) FAILED (plaintext_length)
$ ./john --stress-test=0 --format=PHPS |grep "^Testing:"|head -n 3
Testing: PHPS [md5(md5($p).$s) 256/256 AVX2 8x3]... (4xOMP) PASS
Testing: PHPS [md5(md5($p).$s) 256/256 AVX2 8x3]... (4xOMP) FAILED (plaintext_length)
Testing: PHPS [md5(md5($p).$s) 256/256 AVX2 8x3]... (4xOMP) FAILED (plaintext_length)
$ ./john --stress-test=0 --format=pix-md5 |grep "^Testing:"|head -n 3
Testing: pix-md5, Cisco PIX [Cisco PIX (MD5) 256/256 AVX2 8x3]... (4xOMP) PASS
Testing: pix-md5, Cisco PIX [Cisco PIX (MD5) 256/256 AVX2 8x3]... (4xOMP) FAILED (plaintext_length)
Testing: pix-md5, Cisco PIX [Cisco PIX (MD5) 256/256 AVX2 8x3]... (4xOMP) FAILED (plaintext_length)
```
```

**Comment by magnumripper** [comment] 2015-04-28 07:35
This is a dupe of #1135

**Closed by magnumripper** 2015-04-28 07:35 UTC
