### ISSUE TITLE
Introduce configure options to enable/disable SIMD

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#2862] opened 2017-11-09 16:19 UTC
We should introduce end-user friendly configure options to enable/disable SIMD (and have those options substitute the needed platform-specific compiler flags automatically).

Maybe also be able to choose which SIMD, on architectures that support many (like on x86: MMX, SSE*, AVX, XOP, AVX-2, AVX-512)? Of course, this can be done with custom `CFLAGS`, but the point of this issue is to make things simpler for end-users, and for ourselves too.

**Comment by magnumripper** [comment] 2017-11-09 21:59
Basically, I see two types of users:
1. J. Random Luser, who wants a build fairly optimized for the build host. He won't use this.
2. Mrs. Dist, who knows all about configure and CFLAGS. Neither will she.

**Comment by solardiz** [comment] 2017-11-09 22:08
What about "unnamed" users who would nevertheless be able to use `./configure --disable-simd` if the default SIMD-enabled build fails (and it is in fact more likely to fail) or if they need to test longer passwords (other than with hash types simple enough that Jim's command-line dynamic formats could be used for them, hopefully providing a high enough limit)? It's useful for us to be able to give such simple instructions in those cases.

It is also useful for us to be able to test such builds in a generic manner, without diving into platform-specific CFLAGS.

**Comment by jfoug** [comment] 2017-11-09 22:21
I kind of agree with Solar on this. It would be 'nice' to simply do a ```./configure --disable-simd && make -s clean && make -sj8``` without having to remember CFLAGS, or CPPFLAGS or whatever 'magic' is needed to build a non-SIMD build.

**Comment by magnumripper** [comment] 2017-11-09 22:22
Adding these options will introduce bugs and problems and confusion. If "the default SIMD-enabled build fails" we should put our efforts in fixing that, not working around it.

On the contrary, we should drop some of our present options IMHO. They just give me headache.

**Comment by solardiz** [comment] 2017-11-10 12:28
Adding these options will also make us fix bugs earlier, help us and users work around problems, and reduce confusion when we come up with and give instructions to make non-SIMD builds. Right now, I don't even know how to make a non-SIMD build for PPC64 in #2861. Sure it's some bugs we'll fix anyway, and SIMD will also work then, but it's useful to be able to quickly and easily test both kinds of builds.

While we should fix SIMD build bugs seen on "supported platforms" whenever we learn of them, "the default SIMD-enabled build fails" will be a recurring issue on uncommon and older platforms anyway.

**Comment by solardiz** [comment] 2017-11-10 12:33
"8x slower band aid" - that's not always the case. On some ARM/NEON, the NEON is only +50% or so. For some formats, we don't even have SIMD support, or can't reasonably have it on current hardware (most notably, for bcrypt). If the user wants to use only one of those formats and the SIMD build fails, it is in fact best for them to do a non-SIMD build right away and proceed with the actual work instead of waiting for us to possibly fix the bug for their platform (which we might not bother with if the platform is rare/outdated).

**Comment by jfoug** [comment] 2017-11-10 13:25
There is may also not be a way to build non-SIMD for x86-64 (I am aware of how to do it).  I can do so on i686 using Makefile.legacy but not on x86-64 I do not have a procedure for doing it.

There is a rub, and that comes from formats doing things like #if __SSE2__ type logic, and NOT using the logic that was computed at configure time.  Core is a big offender here.  So simply trying to configure something like    #if SIMD_OFF  is not trivial.  Yes, we might be able to hide that some how within an early call in arch.h (or a late call in autoconf.h) to simply undef things like SSE2, etc and make sure that all SIMD defines are cleared.  But I also agree, that an easy to do way to build non-SIMD would not be a bad thing, IMHO.   There are times when I want to test long password type stuff (in dyna).   I simply use to use legacy to build an 'any' on cygwin32 to get the binary I want to do it.   It does work, but not my favorite way.

**Comment by magnumripper** [comment] 2017-11-10 13:32
> There is may also not be a way to build non-SIMD for x86-64 (I am aware of how to do it)

Not sure what you tried to say there, totally ambiguous 😆 but anyway there should be no problems building non-SIMD. Just say `-mno-sse` and tell configure not to do any native tests nor to use `-march=native`. I have done it many times.

> There is a rub, and that comes from formats doing things like `#if __SSE2__` type logic, and NOT using the logic that was computed at configure time. Core is a big offender here. So simply trying to configure something like #if SIMD_OFF is not trivial. 

That would be a completely wrong way to do it. The right way is to tell compiler (as I wrote above) not to use SIMD - and then there will be no `__SSE2__` either. All is fine.

**Comment by solardiz** [comment] 2017-11-10 13:44
I agree this would be about compiler flags, except that SSE2 is such an integral part of x86-64 that system headers might depend on it (and/or SSE and MMX, which are implied by SSE2) being enabled. I ran into this with glibc, resulting in:

    ./configure --disable-native-tests CFLAGS='-O2 -mno-sse2 -mno-mmx -U__SSE__'

So that plain SSE is left enabled in the compiler, as a header depended on it (but luckily not on SSE2, nor on MMX in this case). There might be similar issues on some non-x86 archs as well.

So our options are: (1) use hackish compiler flags as above, or (2) actually introduce our own USE_SIMD macro and checks for it in the code.

**Comment by magnumripper** [comment] 2017-11-10 13:46
OK, fine. Any volunteers?

**Comment by magnumripper** [comment] 2017-11-10 13:48
I want this as a PR, **not** a cowboy commit please.

**Comment by claudioandre** [comment] 2017-11-10 18:02
> there should be no problems building non-SIMD.

In fact if anyone searches on bleeding GitHub for "non-simd build" he/she will find a good starting point. It's been there (at least) for a month.

**Comment by solardiz** [comment] 2017-11-10 18:15
Found https://github.com/magnumripper/JohnTheRipper/blob/56e28cdfc4a146dd4270703134271c2b6977b3e6/src/CircleCI-MinGW.sh but it's not exactly user-friendly and is specific to bleeding-jumbo. My proposed configure option would look the same in every jumbo version we release, while its implementations under the hood could vary between versions.

**Comment by jfoug** [comment] 2017-12-08 05:52
Adding --enable-withoutsimd

I have a pretty good go, it was not all that hard to add.  I had to make sure that none of the macros in the m4 directory loaded SIMD code (the mic logic was the exception).  I also added a CFLAG of -DJOHN_NO_SIMD   Then in the arch.h the JOHN_NO_SIMD flag comments out code.  Then in configure, when building fmt_*.h I had to also add the -DJOHN_NO_SIMD to the CC lines, so that the raw-sha*_ng.c formats would not be added.

Tested and worked fine on x86-64 build. I will also test on the powerpc builds.  Once I have a good feeling about it, I will make a local topic branch in my code, and build a PR.

Since @magnumripper was not overly happy about this flag, I will let that PR sit a bit, until I get comments from others.   However, I personally have wanted an easy to use flag like this one in configure for quite some time. It makes doing build testing on non-simd builds easier, than using the legacy makefile like I had been doing.

**Comment by jfoug** [comment] 2017-12-08 05:54
NOTE, I also 'left' the ```__SSE__``` flag enabled.  I do not think it introduces any SIMD into john's build, BUT at least for cygwin, if you disable that, it will not build under 64 bit.  I did #undef all of the other SIMD flags in x86-64.h IF the ```-DJOHN_NO_SIMD``` flag was set .

**Comment by magnumripper** [comment] 2017-12-08 07:16
You have got to be joking, we're not merging anything called --enable-withoutsimd.

It should be `--disable-simd`.

**Comment by jfoug** [comment] 2017-12-08 14:49
Ok, working on that now.

**Comment by magnumripper** [comment] 2017-12-08 14:54
Great, no offense! 🍻

**Comment by jfoug** [comment] 2017-12-08 15:01
None taken.  No offense for being flushed out of the shadows ;)

**Comment by magnumripper** [comment] 2017-12-10 08:41
Did we want this option to merely disable our use of intrinsics within JtR, or to actually disable SIMD output from the compiler? The current PR only does the former (in case basic SIMD like eg. -msse2 is default, which it normally is). That means it's only good for test purposes.

The other approach (actually adding `-mno-mmx` and so on) is better but is less generic and less future-proof.

**Comment by jfoug** [comment] 2017-12-10 15:56
IMHO, the non-SIMD should just be how john's code itself builds.  The default library code, and headers, if they were built with SIMD instructions, we are not about to rebuild them, they should simply work. 

This is about systems, for whatever reason, that simply are not building or running properly using SIMD, but still could benefit from a working copy of john.   Yes, one 'simple' approach, is to simply document:

```
CFLAGS="-O2 -mno-sse2" ./configure      && make -s clean && make -sj8  && ../run/john -test=0
```
is one way to go, and then to figure out all of the proper CFLAG changes, validating them all, etc.  What I have been trying to do, is to make a single configure switch that simply does the same thing.

But we have all sorts of fun.  As listed by @solar, there may be expectations by the build environment. It may be written to only work for SSE2+  (a lot, or all x86_64 systems appear this way), or it may even be written to expect SSE4+    So, on the intel side, this is NOT a trivial problem.

On the PPC and ARM side, this appears to be much more trivial.  Simply make a bit of a change to the SIMD detection logic in the m4/jtr_ppc.m4 file (and arm file) and small touches to their arch.h files, and we are pretty much golden. This is because we have not inserted SIMD stuff in anything other than in format files (loaded from simd-intrinsics.c or x86*.S)    But for the intel side, we have rouge formats doing their own probing, and even some core files doing their own probing.  That is the crux of the overall problem.  shutting down SIMD in the formats is not too hard. Possibly, shutting that down is as far as we go.

**Comment by solardiz** [comment] 2017-12-10 16:02
I think the difference between x86* vs. other archs is not that big. On any arch, system headers might make assumptions about availability of some minimum SIMD instruction set required by that system. As to our use of intrinsics by non-formats, I only recall `cracker.c` (where our use is non-SIMD, so should probably be left enabled if we can) and `wordlist.c` (where the use is SIMD, but is probably harmless if it builds at all - not imposing any limitations, unlike some uses in formats). I am undecided on whether this option should affect the use by `wordlist.c` or leave it alone. Either would work for me.

**Comment by solardiz** [comment] 2017-12-11 19:28
Besides --disable-simd, should we possibly also have --enable-simd[=altivec], etc. so that we could override configure's detection both ways? For example, we'd currently fail to detect AltiVec on non-Linux, but we could then at least force-enable it.

**Comment by jfoug** [comment] 2017-12-11 22:28
VERY good point.

As for the ppc code, I will put calling it into a wrapper. If the build is not linux, the program will simpyl print "1" to the screen and return 0.  That way, the code will simply build SIMD (i.e. all checking will succeed) on non-linux systems (until we get solid code that works). Then the user can simply use --disable-simd if running on a non 7_23 version.

**Comment by magnumripper** [comment] 2017-12-12 00:14
Perhaps we should have a switch instead so it gets more extensible. For example:
`--enable-simd` would do nothing (it's the default).
`--disable-simd` would disable most or all use of SIMD (eg. `-mno-mmx -mno-sse2` depeding on arch), just like the current #2991 tries to accomplish.
`--enable-simd=avx2` would result in `-mavx2`.
`--enable-simd=altivec would result in whatever option is needed for that.

...and so on. No, wait. Perhaps most cases are solved with a default that `-enable-simd=foo` would result in `-mfoo`? That would take care of x86 any many others right away.

**Comment by magnumripper** [comment] 2017-12-12 09:25
I think from the looks of #2991 we need to ditch the idea of resetting archs like `-mno-mmx -mno-sse2` with that option, and just use the JOHN_NO_SIMD macro for everything. This will also work for any arch - no special cases.

Meanwhile, I committed the bug fix for `simd-intrinsics.h` to bleeding jumbo now. On systems where system headers and tools can handle an actual non-SSE2 build, it's as easy as adding `CFLAGS="-mno-mmx -mno-sse2 -g -O2"` to the configure options.

This will however mean that --disable-simd will produce a whole different build (in the details) than one made with `CFLAGS="-mno-mmx -mno-sse2 -g -O2"`.

**Comment by magnumripper** [comment] 2017-12-12 09:29
That may boil down to
```
--disable-simd       results in setting JOHN_NO_SIMD
--enable-simd=foo    results in adding "-mfoo" to CFLAGS
```
Both of the above also disables native testing.

**Comment by jfoug** [comment] 2017-12-12 18:04
Btw, commenting can stop for a bit. i am pretty sure I have this handled now.

Here is what was done.

1. configure sees --disable-simd.  It does these things differently
    a.  -DJOHN_NO_SIMD flag added
    b.  at the end of the jtr_x86.m4 macro stuff, it sets CPU to "SIMD_disabled", and turns off Hyperthreading.  The SIMD_disabled shows up as the john build type (just like AVX2 would have).
    c.  the aes SIMD checks in configure are commented out (like they were prior)
2. arch.h  Most are not effected, since the compiler flags are 'extras'.  BUT on x86-64, the compiler flags are NOT extra. So there are numerous scatterings of !JOHN_NO_SIMD and some that are JOHN_NO_SIMD (reverse logic)
3. several files needed JOHN_NO_SIMD logic.  Blake2 stuff, stribog, params.h, simd-intrisics.h, etc

So now the code is build WITH -mavx2 (if building on an AVX2 system).  BUT the simd logic has been trimmed of actual usage with the defines.   the defines were not nearly as bad as I had expected.   NOTE, I still am not 100% sure about the DES stuff in x86-64, that may still take some work.

But the other usages of it (such as ALL usages of simd-intrinsics.c) are now handled, along with there are no problems seen compiling or running openCL, AND we should not have the compile problems we were seeing with the emulation of ```CFLAGS="-mno-sse2 -mno-mmx"``` which we were seeing before.

I still have more testing to do, before I check this one in.  It may boil down to the original simd-intrinsics.h can be used, with no additional #define checking.   Part of the problem is I have 6 different build/tests to do, and some of them are VERY slow (like the ppc64 stuff).  But once I have a version that makes all systems happy, I will get that checked into my branch and a PR done.  I hope that this one is golden, after all of the wild goose chases.  NOTE, this one probably will make exes which use the CPUID checking inside of john (for the x86 stuff) since they do get the -mavx2 flag. the compiler WILL have potential for spitting out code runnable only by that CPU.

As for the native testing (with this code), I think it is meaningless. It can be done, it will simply be ignored by the #defines.

As for ```--enable-simd=foo```  That will have to be addressed AFTER this one.  That opens up a Pandoras box of additional crap.  Look at the current ALTIVEC stuff.  it requires 3 -m flags, not just 1!  Also, any simd addition would have to have the proper logic ALREADY inside of pseudo-intrinsics.h file.  I think if we do allow this, it would almost have to be something like
```
--enable-simd="-mavx2 -DJOHN_AVX2"
--enable-simd="-maltivec -msvx -mpower8vector -DJOHN_ALTIVEC"
```

Well, that does not work either, because we can not pass in the CPU type, that gets put into john's (and configures') build string. 

So if we want to have this, it would have to be a table of exceptable values, and then the logic required for them is added.

So:

```
--enable-simd=avx2

would
 
set CPU string to AVX2
add -mavx2 and -DJOHN_AVX2 to the compiler command line
```

```
--enable-simd=altivec (or altivec2)

would
 
set CPU string to ALTIVEC (or ALTIVEC2)
add -maltivec -msvx -mpower8vector and -DJOHN_ALTIVEC to the compiler command line
```

```
--enable-simd=altivec1

would
 
set CPU string to ALTIVEC1
add -maltivec -msvx  and -DJOHN_ALTIVEC1 to the compiler command line
```

etc.   NOTE, this might be important to have, it might not be. Would this make cross compiling easier?  Now, you can simply tell configure what flavor to use, have it all setup right, and it just gets built, without the probing checks.  However, it may still have to check the flags, to make sure the compiler can handle them, but that is about it.

**Comment by magnumripper** [comment] 2017-12-12 20:48
> So:
> --enable-simd=avx2
> 
> would
> 
> set CPU string to AVX2

No. It should add `-mavx2` to CFLAGS. Nothing more. CPU string is already set to AVX2 by configure and/or arch.h.

> add -DJOHN_AVX2 to the compiler command line

No, that too already happens. I routinely build for all intel archs including AVX2 from an AVX build host. The **only** thing I do is add -mavx2 to CFLAGS.

>
> --enable-simd=altivec (or altivec2)
> 
> would
>  
> set CPU string to ALTIVEC (or ALTIVEC2)

What CPU string? If you mean CPU_NAME it's only used for x86 and already taken care of. If you started using this in your recent PPC patches, fine but this should happen in configure and/or arch.h and be set from compiler macros just like the intel ones. This is irrelevant for this issue.

> add -maltivec -msvx -mpower8vector

That's what I said originally. I had this in mind:
```sh
case $simd in
altivec1)
    CFLAGS = "$CFLAGS -maltivec -msvx"
    ;;
altivec*)
    CFLAGS = "$CFLAGS -maltivec -msvx -mpower8vector"
    ;;
*)
    CFLAGS = "$CFLAGS -m${simd}"
    ;;
esac
```
The last "default" case takes care of many cases, I think all intel ones. Anything that needs more than that has to get an own case.

> and -DJOHN_ALTIVEC to the compiler command line

What is that for? I only see it being tested in ppc*.h but nothing ever sets it.

**Closed** 2017-12-25 01:28 UTC
Labels: enhancement
