### ISSUE TITLE
--prince hidden options lack sanity check

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1646] opened 2015-08-11 09:41 UTC
What I intended:
```
./john --stdout --prince=test --prince-elem-cnt-min=2 --prince-elem-cnt-max=2
11
21
12
22
4p 0:00:00:00 0.00% 26.66p/s 22
```

What I did:
```
./john --stdout --prince=test --prince-elem-cnt-min=2--prince-elem-cnt-max=2|wc -l
Press 'q' or Ctrl-C to abort, almost any other key for status
508p 0:00:00:00 0.00% 2309p/s 22222222
508
```

I had hoped john would tell me that `2--prince-elem-cnt-max=2` isn't a valid value for `--prince-elem-cnt-min=`.

**Comment by magnumripper** [comment] 2015-08-11 11:55
I think this is more or less a core problem and a dupe of #1300.

**Closed** 2015-08-16 18:34 UTC
