### ISSUE TITLE
TS errors for hmac-sha256 after recent salt length change

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1909] opened 2015-11-24 11:35 UTC
```
$ ../run/john --list=build-info 
Version: 1.8.0.6-jumbo-1-1667-g2d353ed
Build: linux-gnu 64-bit AVX-ac
SIMD: AVX, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
$JOHN is ../run/
Format interface version: 13
Max. number of reported tunable costs: 3
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 5.1.1
GNU libc version: 2.21 (loaded: 2.21)
Crypto library: OpenSSL
OpenSSL library version: 0100010bf
OpenSSL 1.0.1k-fips 8 Jan 2015
GMP library version: 6.0.0
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
```

```
$ ./jtrts.pl hmac-sha256 -v -stoponerror
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper 1.8.0.6-jumbo-1-1667-g2d353ed [linux-gnu 64-bit AVX-ac]
--------------------------------------------------------------------------------

John Jumbo build detected.
--pot=NAME option is valid
--encoding=NAME option is valid
all.chr (../run/all.chr) not found
alnum.chr found, inc_alnum_ee8763c850dee8e4b88ef547a8ed39b8 added as a capability
Types to filter on:
hmac-sha256
Capabilities in this build of john:
jumbo core inc local_pot_valid encode_valid utf8 cp1252 cp1251 koi8r cp437 cp737 cp850 cp858 cp866 iso8859-1 iso8859-15 inc_alnum_ee8763c850dee8e4b88ef547a8ed39b8

form=hmac-sha256                  guesses:    0 -show=   0 0:00:00:04 DONE : Expected count(s) (1500)  [!!!FAILED1!!!]
Exiting on error. The .pot file tst-.pot contains the found data
The command used to run this test was:

../run/john -ses=tst-  -pot=tst-.pot hmacSHA256_tst.in --wordlist=pw.dic -form=hmac-sha256
and
../run/john -show   -pot=tst-.pot hmacSHA256_tst.in -form=hmac-sha256 2>/dev/null
```

```
$ ../run/john -ses=tst-  -pot=tst-.pot hmacSHA256_tst.in --wordlist=pw.dic -form=hmac-sha256
Loaded 1500 password hashes with 1500 different salts (HMAC-SHA256 [password is key, SHA256 128/128 AVX 4x])
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:04 DONE (2015-11-24 12:35) 0g/s 1441p/s 2162Kc/s 2162KC/s X1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789..0A234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
Session completed
```

```
$ ./jtrts.pl -q
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper 1.8.0.6-jumbo-1-1667-g2d353ed [linux-gnu 64-bit AVX-ac]
--------------------------------------------------------------------------------
form=hmac-sha256                  guesses:    0 -show=   0 0:00:00:03 DONE : Expected count(s) (1500)  [!!!FAILED1!!!]
.pot CHK:hmac-sha256              guesses:    0 -show=   0 N/A N/A : Expected count(s) (1500)  [!!!FAILED4!!!]  (0 val-pwd  1 inval-pwd)
form=episerver_sha1               guesses: 1476 -show=1476 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED1!!!]
form=episerver_sha1-utf8          guesses: 1403 -show=1403 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED1!!!]
form=episerver_sha256-utf8        guesses: 1437 -show=1437 0:00:00:00 DONE : Expected count(s) (1500)(1202)  [!!!FAILED1!!!]
form=ripemd-128                   guesses:    0 -show=   0 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED1!!!]
.pot CHK:ripemd-128               guesses:    0 -show=   0 N/A N/A : Expected count(s) (1500)  [!!!FAILED4!!!]  (0 val-pwd  1 inval-pwd)
Some tests had Errors. Performed 599 tests.  5 errors  2 errors reprocessing the .POT files
Time used was 1294 seconds
```

**Comment by frank-dittrich** [comment] 2015-11-24 12:41
Some of the issues might be older, because in https://github.com/magnumripper/JohnTheRipper/issues/1769 I reported
```
orm=episerver_sha1               guesses: 1476 -show=1476 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED1!!!]
form=episerver_sha1-utf8          guesses: 1403 -show=1403 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED1!!!]
form=episerver_sha256-utf8        guesses: 1437 -show=1437 0:00:00:00 DONE : Expected count(s) (1500)(1202)  [!!!FAILED1!!!]
form=ripemd-128                   guesses:    0 -show=   0 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED1!!!]
.pot CHK:ripemd-128               guesses:    0 -show=   0 unk unk : Expected count(s) (1500)  [!!!FAILED4!!!]  (0 val-pwd  1 inval-pwd)
```

**Comment by frank-dittrich** [comment] 2015-11-24 13:38
With `$ ./jtrts.pl -q -type full`, I get just one more error:
```
form=PHPass                       guesses:  990 -show= 990 0:00:00:00 DONE : Expected count(s) (1500)(970)  [!!!FAILED1!!!]
```

**Comment by jfoug** [comment] 2015-11-24 18:14
$ ./jtrts.pl hmac-sha256 -v -stoponerror
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper 1.8.0.6-jumbo-1-1667-g2d353ed OMP [cygwin 64-bit AVX-ac]
--------------------------------------------------------------------------------

John Jumbo build detected.
--pot=NAME option is valid
--encoding=NAME option is valid
all.chr (../run/all.chr) not found
alnum.chr found, inc_alnum_ee8763c850dee8e4b88ef547a8ed39b8 added as a capability
Types to filter on:
hmac-sha256
Capabilities in this build of john:
jumbo core opencl inc local_pot_valid encode_valid utf8 cp1252 cp1251 koi8r cp437 cp737 cp850 cp858 cp866 iso8859-1 iso8859-15 inc_alnum_ee8763c850dee8e4b88ef547a8ed39b8

form=hmac-sha256                  guesses: 1500 0:00:00:00 DONE  [PASSED]
.pot CHK:hmac-sha256              guesses: 1500 0:00:00:00 DONE  [PASSED] (1500 val-pwd)

All tests passed without error.  Performed 1 tests.  Time used was 4 seconds

$ ../run/john --list=build-info
Version: 1.8.0.6-jumbo-1-1667-g2d353ed
Build: cygwin 64-bit AVX-ac OMP
SIMD: AVX, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
$JOHN is ../run/
Format interface version: 13
Max. number of reported tunable costs: 3
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 4.9.3
OpenCL headers version: 1.2
Crypto library: OpenSSL
OpenSSL library version: 01000203f
OpenSSL 1.0.2c 12 Jun 2015
GMP library version: 6.0.0
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's



Now, I have a OMP build (yours is not), and I am cygwin under Win7, where you are linux. But other than that, this is pretty close to same. This could be a non-OMP bug.  I will check.

**Comment by jfoug** [comment] 2015-11-24 18:18
$ ./jtrts.pl hmac-sha256 -v -stoponerror
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper 1.8.0.6-jumbo-1-1667-g2d353ed [cygwin 64-bit AVX-ac]
--------------------------------------------------------------------------------

John Jumbo build detected.
--pot=NAME option is valid
--encoding=NAME option is valid
all.chr (../run/all.chr) not found
alnum.chr found, inc_alnum_ee8763c850dee8e4b88ef547a8ed39b8 added as a capability
Types to filter on:
hmac-sha256
Capabilities in this build of john:
jumbo core opencl inc local_pot_valid encode_valid utf8 cp1252 cp1251 koi8r cp437 cp737 cp850 cp858 cp866 iso8859-1 iso8859-15 inc_alnum_ee8763c850dee8e4b88ef547a8ed39b8

form=hmac-sha256                  guesses:    0 -show=   0 0:00:00:04 DONE : Expected count(s) (1500)  [!!!FAILED1!!!]
Exiting on error. The .pot file tst-.pot contains the found data
The command used to run this test was:

../run/john -ses=tst-  -pot=tst-.pot hmacSHA256_tst.in --wordlist=pw.dic -form=hmac-sha256
and
../run/john -show   -pot=tst-.pot hmacSHA256_tst.in -form=hmac-sha256 2>/dev/null



So this bug is NON-OMP!

**Comment by jfoug** [comment] 2015-11-24 18:19
I assigned to @magnumripper since I think he just opened up this (and other formats) to change recently.

**Comment by jfoug** [comment] 2015-11-24 18:36
This appears to only be an issue in SIMD non-OMP builds.

**Comment by jfoug** [comment] 2015-11-24 20:06
If the last long salt test string (I think the 4th one) is commented out, then the hash works fine.  There is some memory issues going on, or cleanup 'failures'.

**Comment by jfoug** [comment] 2015-11-24 21:02
@frank-dittrich can you validate that commenting out line 76 of hmacSHA256_fmt_plug.c fixes this for your build.

**Comment by magnumripper** [comment] 2015-11-24 21:20
Let's use this issue for hmac-sha256 only. Please never stuff several completely unrelated problems into one same issue. It always ends in a mess.

To my defense I did run TS before committing 2d353eda1 but I admit to not trying non-OpenMP. Off the top of my head, I saw one strange thing that I didn't "reproduce" when changing salt length:
```diff
@@ -87,7 +89,8 @@ static struct fmt_tests tests[] = {
 static unsigned char *crypt_key;
 static unsigned char *ipad, *prep_ipad;
 static unsigned char *opad, *prep_opad;
-JTR_ALIGN(MEM_ALIGN_SIMD) unsigned char cur_salt[SALT_LENGTH * 4 * MAX_KEYS_PER_CRYPT];
+JTR_ALIGN(MEM_ALIGN_SIMD) unsigned char cur_salt[SALT_LIMBS][64 * MAX_KEYS_PER_CRYPT];
+static int salt_len;
 static int bufsize;
 #else
 static ARCH_WORD_32 (*crypt_key)[BINARY_SIZE / sizeof(ARCH_WORD_32)];
```
Not the change from `SALT_LENGTH * 4` (where SALT_LENGTH was 56) to simply `64`. I thought this was correct, and I think I still do... we already have the SIMD width and interleaving represented as MAX_KEYS_PER_CRYPT.

But that's the only thing I can think of. Is that `* 4` somehow needed? Why?

**Comment by frank-dittrich** [comment] 2015-11-24 21:23
@jfoug commenting out that one test "fixes" iit for me as well.

**Comment by jfoug** [comment] 2015-11-24 21:28
I tried the *4 on the new code, and it does not make any change (only tested on failing non-OMP build)

**Comment by jfoug** [comment] 2015-11-24 21:32
Ok, found a HUGE problem (likely THE problem).  salt_len is set in get_salt, and then USED in crypt_all.  BUT it is not part of the salt, and set_salt() does not update it!!!

So having that salt be the last one in testing, leaves a 3 limb salt as being the ONLY way that crypt_all will work for real test data.

**Comment by magnumripper** [comment] 2015-11-24 21:34
Yeah, that's the problem for sure. Feel free to commit a fix, or I'll do it a bit later.

**Comment by jfoug** [comment] 2015-11-24 21:35
I'll get it, and make the size of the salt to a tiny thing (just a pointer and int inside a struct)

**Comment by jfoug** [comment] 2015-11-24 21:49
The tiny salt is off the table for now. Too hard to salt dupe remove.  I will just keep the [3][64*MAX] sized buffer.

**Comment by magnumripper** [comment] 2015-11-24 22:00
I see no need to complicate things here. The salt is not that big anyway.

Since the format currently relies on salt being a C string, you can simply add a strlen in set_salt() and be done with it. But I do plan on making the HMAC formats hex-salt capable later (perhaps for J3)

**Comment by magnumripper** [comment] 2015-11-24 22:01
> add a strlen in set_salt()

Oh right, we can't do that because the salt is interleaved. A salt struct is probable better.

**Comment by jfoug** [comment] 2015-11-24 22:10
23f77d2   Not to big of a change.

**Closed** 2015-11-24 22:18 UTC
Labels: bug
