### ISSUE TITLE
Update on blockchain cracking?

### ISSUE THREAD

**Issue by ljx34** [magnumripper/JohnTheRipper#1803] opened 2015-10-05 07:21 UTC
Don't think much has been done about it... I do believe that it's not cracking wallets that it should be..

I have downloaded a wallet I know the password of, used blockchain2john.py and tried to crack with no luck.

Could somebody give me some info on this? also am I supposed to be using the -json option when using blockchain2john  from a downloaded wallet? 

Please I could really use your help, thanks for this fantastic mod :)

**Comment by magnumripper** [comment] 2015-10-05 07:44
This may be a dupe of #663 and/or #1050

**Comment by ljx34** [comment] 2015-10-07 05:48
Maybe.. but is there no response on this then? because thats from june 2014..?

Also I did ask other questions I have an issue with/not sure about.

**Comment by magnumripper** [comment] 2015-10-07 07:38
Sorry, all of us work on a voluntary basis here. Your best hope is for @kholia to get a relapse.

**Comment by kholia** [comment] 2015-10-07 09:09
@ljx34 

Please upload a sample wallet file which exhibits the problem clearly. Also, describe the exact steps you took earlier. Thanks!

**Comment by magnumripper** [comment] 2015-10-08 21:11
Please do so in #663 or #1050, I'm closing this one.

**Closed by magnumripper** 2015-10-08 21:11 UTC
