### ISSUE TITLE
unicode_range.c (sourced from subsets.c) take a lot of memory to compile with gcc

### ISSUE THREAD

**Issue by torerobo** [magnumripper/JohnTheRipper#3636] opened 2019-02-05 10:48 UTC
Hey. Today I downloaded the JTR version.
Installed the libssl-dev package (OS Kali Linux 4.17.0-kali1-amd64).
git clone git: //github.com/magnumripper/JohnTheRipper -b bleeding-jumbo john
chmod -R 777 ~/john
cd john / src
./configure && make -s clean && make -sj1 

I get cc1: out of memory allocating 8228848 bytes after a total of 298749952 bytes
make[1]: *** [Makefile:1598: subsets.o] Error 1
make[1]: *** Waiting for unfinished jobs....
ar: creating ed25519-donna.a
ar: creating secp256k1.a
make: *** [Makefile:189: default] Error 2

./configure && make -s clean && make -sj4
I get gcc: fatal error: Killed signal terminated program cc1
compilation terminated.
make[1]: *** [Makefile:1598: subsets.o] Error 1
make[1]: *** Waiting for unfinished jobs....
ar: creating secp256k1.a
ar: creating ed25519-donna.a
make: *** [Makefile:189: default] Error 2

**Comment by magnumripper** [comment] 2019-02-05 17:19
Let me guess: You are running in a VM and you assigned it just 512 MB of RAM, and no swap? Something like that. If so, the solution is simply to bump memory and/or add swap.

But even if that is the case, thank you for reporting: I think I know what piece of code I should review for better portability with systems have limited resources.

**Comment by torerobo** [comment] 2019-02-05 19:46
Kali linux (amazon t2.micro). 1GB of RAM. The fact is that with previous versions on the same glands, the compilation was successful.

**Comment by magnumripper** [comment] 2019-02-06 00:57
Try `make debug subsets.o && make -sj4`

**Comment by magnumripper** [comment] 2019-02-06 01:04
Your OP does not add up. You claim you ran this:
```
./configure && make -s clean && make -sj1
```

But the above (the `-j1` in particular) can't produce the output below (multiple processes definitely running):
```
cc1: out of memory allocating 8228848 bytes after a total of 298749952 bytes
make[1]: *** [Makefile:1598: subsets.o] Error 1
make[1]: *** Waiting for unfinished jobs....
ar: creating ed25519-donna.a
ar: creating secp256k1.a
make: *** [Makefile:189: default] Error 2
```
If you had really used `-sj1`, the "ar" output would not have shown after the error. Perhaps that was just a little copy/paste mismatch and it's of no importance but be sure you try `-sj1` if low on memory. `-sj4` will suck a lot more memory.

**Comment by torerobo** [comment] 2019-02-06 07:32
There is no error, it is the output of [js1] and [js4] that has thrown off. Yes, I did a swap and from swap ~ 80 MB was requested for a successful compilation.

history
06.02.2019 10:28:43 ./configure && make -s clean && make -sj1

**Comment by claudioandre-br** [comment] 2019-02-17 22:09
`clang` also fails. But, the problem is not in the latest `subsets.c`, it is in `clang` itself.
* When I compile the latest source using my reproducible environment (clang version 7.0.0-3), it works fine.

For reference:
```
LLVM ERROR: out of memory
Stack dump:
0.	Program arguments: /usr/lib/llvm-8/bin/clang -cc1 -triple x86_64-pc-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name subsets.c -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -target-feature +avx -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -momit-leaf-frame-pointer -coverage-notes-file /cwd/src/subsets.gcno -resource-dir /usr/lib/llvm-8/lib/clang/8.0.0 -D AC_BUILT -D JOHN_AVX -I /usr/local/include -D ARCH_LITTLE_ENDIAN=1 -D _POSIX_SOURCE -D _GNU_SOURCE -D _XOPEN_SOURCE=600 -D HAVE_HT -I /usr/local/include -D CL_SILENCE_DEPRECATION -D HAVE_ZTEX -internal-isystem /usr/local/include -internal-isystem /usr/lib/llvm-8/lib/clang/8.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -Og -Wall -Wdeclaration-after-statement -Werror -Wno-error=cpp -Wno-error=#warnings -Wno-deprecated-declarations -Wformat-extra-args -Wdate-time -std=gnu89 -fdebug-compilation-dir /cwd/src -ferror-limit 19 -fmessage-length 0 -fopenmp -fsanitize=address -fsanitize-blacklist=/usr/lib/llvm-8/lib/clang/8.0.0/share/asan_blacklist.txt -fsanitize-address-use-after-scope -fno-assume-sane-operator-new -funroll-loops -pthread -fobjc-runtime=gcc -fdiagnostics-show-option -o subsets.o -x c subsets.c -faddrsig
```

**Comment by solardiz** [comment] 2019-03-21 23:10
Testing on CentOS 7 with devtoolset-7 running on Xeon Phi 7210, `subsets.c` takes ~1.5 minutes to compile and uses up 800 MB. This easily dominates the compile time for the whole jumbo, because everything else gets compiled much sooner by the many parallel processes (with `make -sj256`).

This fix works for me:

```diff
$ git diff
diff --git a/src/unicode_range.c b/src/unicode_range.c
index bb9f1ab..0a11701 100644
--- a/src/unicode_range.c
+++ b/src/unicode_range.c
@@ -1,3 +1,8 @@
+#ifdef __GNUC__
+#pragma GCC push_options
+#pragma GCC optimize ("O0")
+#endif
+
 static size_t full_unicode_charset(UTF32* charset)
 {
        int i, c;
@@ -2276,3 +2281,7 @@ static size_t full_unicode_charset(UTF32* charset)
 
        return i;
 }
+
+#ifdef __GNUC__
+#pragma GCC pop_options
+#endif
```

The resulting `subsets.o` isn't large:

```
$ size subsets.o
   text    data     bss     dec     hex filename
  52921       0    3956   56877    de2d subsets.o
```

Also, I suggest that we compile `unicode_range.c` on its own and into its own object file, and make the function non-static. The way it currently is, it's not getting listed as a dependency for `subsets.o`, so after I make edits to `unicode_range.c` I have to manually `rm subsets.o` to get it recompiled.

**Closed** 2019-03-26 17:46 UTC
Labels: enhancement
