### ISSUE TITLE
ZTEX version numbers says 1.8.x

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#3995] opened 2019-05-22 16:23 UTC
From https://github.com/magnumripper/JohnTheRipper/issues/2600#issuecomment-494759763
> > `SN: 15 productId: 10.15.0.0 "inouttraffic JtR 1.8.x" busnum:1 devnum:94`
> > why does it say `JtR 1.8.x` here?
> 
> This is somewhat tricky to edit, so I chose not to bother, nor to bother @Apingis with a request to make this edit prior to our release (especially given that he was mostly unavailable at the time). I imagine the easiest way to edit this string is in the .ihx file, without actually recompiling the firmware, and in the host code for what string to expect. Should we maybe use JtR-unrelated versioning scheme there, so that this doesn't become confusing each time we make a new major release?

It's no big deal really, but anyway:
- Isn't there a checksum that would fail if we edit the binary?
- An independent version number would probably be a good idea - maybe an actual version of (just) the firmware instead, at @Apingis discretion.

**Comment by solardiz** [comment] 2019-05-22 16:56
This is dupe of #3992, so please close one or the other.

> Isn't there a checksum that would fail if we edit the binary?

There are per-line checksums, see 4747ba441941479474377653f5f6d0f4222520c9 for the previous change of the version string.

https://en.wikipedia.org/wiki/Intel_HEX

**Closed** 2019-05-22 23:28 UTC
Labels: Maintenance/cleanup
