### ISSUE TITLE
"Perfect hash tables" not compatible with single mode

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2232] opened 2016-08-23 16:47 UTC
Sayantan's OpenCL formats that use "perfect hash tables" may hang indefinitely upon loading a file in --single mode. The reason is single mode keeps dupes, and (I presume) the hash table code re-tries over and over again to reach a state with no collisions.

I have absolutely no idea how to fix this. Single mode doesn't work very well with OpenCL anyway, but it would be nice to emit some error instead of hanging.

**Comment by solardiz** [comment] 2016-08-23 17:39
This sounds like it should be fixed in the "perfect hash tables" code (detect dupes, or detect being invoked from "single"), not in "single mode" code, so I don't intend to look into it.

**Comment by magnumripper** [comment] 2016-08-23 22:13
@solardiz I didn't expect you to fix it at all - the reason I assigned you to this issue was I was looking for input of any sort. I'm at a loss here and I have a strong feeling Sayantan is "lost" forever.

Perhaps we should somehow error out when in single mode and reaching bt*.[ch] at all. I guess that is doable.

**Comment by solardiz** [comment] 2016-08-23 22:21
> Perhaps we should somehow error out when in single mode and reaching bt*.[ch] at all. I guess that is doable.

Makes sense to me, assuming the problem is as you describe (I didn't test). Thanks!

**Closed** 2016-08-24 16:09 UTC
Labels: bug
