### ISSUE TITLE
Fix CircleCI testing

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2962] opened 2017-12-04 10:39 UTC
We need to re-work the CircleCI jobs. We can configure/build and then run several tests on it, in one job, that's fine and dandy. But what we must NOT do is make several different builds in one job. It's utterly confusing and the log file is humongous - almost impossible to spot problems in it.

**Comment by magnumripper** [comment] 2017-12-07 13:20
Also, the `src/CircleCI-MinGW.sh` script should be moved to eg. `.circleci/` (at same level as `src`, not under it). Are there more such files in `src`?

**Comment by magnumripper** [comment] 2017-12-07 14:58
The script location is fixed now. Not sure how to do the rest... I hate learning volatile platforms.

**Comment by claudioandre-br** [comment] 2018-12-15 18:17
Bug closed as:

* **Low Priority** - They have a tendency to become high priority if enough of the users complain.

* **Business Priority** - Obsolete hardware and software. Hardware nobody owns, etc.

* **WontFix** - Covers all the reasons we chose to close the bug without taking action.
  * Nobody cares.
  * Can't reproduce, working as intended, obsolete.
  * Required information was not provided.

**Closed by claudioandre-br** 2018-12-15 18:17 UTC
Labels: testing
