### ISSUE TITLE
--incremental and --external shouln't silently ignore --rules

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1699] opened 2015-08-21 20:41 UTC
```
./john --stdout --incremental --rules=d|head
Press 'q' or Ctrl-C to abort, almost any other key for status
123456
12345
111189
123455
111188
12344
121288
121289
112345
112344
```

```
$ ./john --stdout --external=keyboard --rules=d|head
Press 'q' or Ctrl-C to abort, almost any other key for status
`
1
2
3
4
5
6
7
8
9
```

Apparently, --rules is just ignored.
I did not yet check master, just bleeding-jumbo.

**Comment by frank-dittrich** [comment] 2015-08-21 22:54
Master doesn't have these problems.

```
(master)run $ ./john --stdout --external=keyboard --rules
Invalid options combination or duplicate option: "--rules"
(master)run $ ./john --stdout --incremental --rules
Invalid options combination or duplicate option: "--rules"
```

**Comment by magnumripper** [comment] 2015-08-24 23:44
This is a dupe of #1697

**Closed by magnumripper** 2015-08-24 23:44 UTC
Labels: bug
