### ISSUE TITLE
accdb file support

### ISSUE THREAD

**Issue by kireinasora** [magnumripper/JohnTheRipper#2597] opened 2017-06-30 12:33 UTC
Environment: Windows 10
John the Ripper v1.8.0.9-jumbo-1-bleeding (Bleeding version on 2017-03-06)

Hi, I saw in your post that you added support for accdb files.
However, when I use office2john.py on it, it says "Invalid OLE file"

Can I ask if there is something wrong?
thanks

**Comment by kholia** [comment] 2017-06-30 14:53
1. Use the latest version of JtR jumbo from this repository.

2. Upload (or email to me) a sample ACCDB file which demonstrates this problem. Which version of MS Office created that ACCDB file?

3. What happens when you run `office2john.py` on a Linux system on that file? The `office2john.py` program was never tested on Windows.

**Comment by kholia** [comment] 2017-07-01 05:13
I received the the ACCDB file over email, and here are my notes.

* The file was most likely created with MS Access 2007. It has `.accdb` extension and has `Standard ACE DB` text in the file header.

* Access 2007 does not always use AES based encryption, which is the only encryption type we support for Access files. The file seems to be using `CryptoAPI` based encryption method as it has the string `Microsoft Base Cryptographic Provider v1.0` in it. This also implies usage of RC4 and SHA1 primitives.

It is unlikely that I will attempt adding support for such types of ACCDB file due to the relative unpopularity of such files, and the complexity of the task.

References:

* http://www.everythingaccess.com/tutorials.asp?ID=Changing-the-encryption-type-in-Access-2007

* https://msdn.microsoft.com/en-us/library/cc313118(v=office.12).aspx (Office File Formats). No documentation seems to exist for Access file formats.

**Comment by kholia** [comment] 2017-07-01 08:01
[Sample Access DBs.zip](https://github.com/magnumripper/JohnTheRipper/files/1116921/Access.File.Formats.zip)

The databases with names starting with `Office 2007 - Access 2007 -` reproduce the problem being reported.

**Comment by kireinasora** [comment] 2017-07-01 08:07
a little bit sad
but thanks a lot for the effort of answers

2017-07-01 16:01 GMT+08:00 Dhiru Kholia <notifications@github.com>:

**Comment by kholia** [comment] 2017-07-01 08:41
@kireinasora I might have a solution. It seems to be your lucky day. I am testing my code right now ;)

**Comment by kholia** [comment] 2017-07-01 09:00
[accdb2john.py.txt](https://github.com/magnumripper/JohnTheRipper/files/1116944/accdb2john.py.txt)

Use this program (after renaming it to `accdb2john.py`) instead of `office2john.py` to extract the hash from the ACCDB file. It will take a while to extract the hash from large files.

@kireinasora Good luck with the password recovery! 👍

**Comment by kireinasora** [comment] 2017-07-01 09:50
Oh thanks Dhiru, love you!

It works with python 2, I am recovering my password now

2017-07-01 17:00 GMT+08:00 Dhiru Kholia <notifications@github.com>:

**Comment by kholia** [comment] 2017-07-01 11:30
Note:

In this particular case, guaranteed data decryption seems possible due to usage of RC4-40.

I believe that https://github.com/kholia/RC4-40-brute-office/ can be combined with a modified version of `UCanAccess` JDBC driver to achieve this.

**Comment by kholia** [comment] 2017-07-04 10:02
This will be fixed soon by a PR (in progress now.)

**Closed by kholia** 2017-07-04 10:02 UTC
Labels: enhancement

**Comment by kholia** [comment] 2017-09-05 05:27
[Access File Formats.zip](https://github.com/magnumripper/JohnTheRipper/files/1276183/Access.File.Formats.zip) (for backup and reference purposes).

**Comment by rubenkr** [comment] 2018-05-24 11:15
Hey @kholia your py script accdb2office.py is AWESOME (!). I am working with it on my outlook2013 PST (5GB!) file. It says range() makes overflow. So it replaced it quick and dirty by xrange(). Unfortunately it then says Python int too large to convert to C long. I am using it with python27. Would be very grateful for your help. Cheers

**Comment by kholia** [comment] 2018-05-24 12:15
Use `office2john.py` script included in this repository. Let us know if it runs into similar problems.

**Comment by rubenkr** [comment] 2018-05-24 12:22
Wow that was fast @kholia. Yes I tried it before with error "invalid ole file". G**gle brought me to this thread here.

**Comment by kholia** [comment] 2018-05-24 12:30
Wait a moment. This thread is about Office ACCDB files. You are dealing with a Outlook PST file. Two very different things!

Please don't hijack threads (err... issue) and don't use this GitHub repository for asking support questions. We have `john-users` mailing list for support.

**Comment by rubenkr** [comment] 2018-05-24 12:31
Ok sorry, I didn't meant to offend. Just I thought it would be related. My mistake

**Comment by kholia** [comment] 2018-05-24 12:36
Look into https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/doc/README-PST. 

For further support questions, please use `john-users` mailing list.

http://www.openwall.com/lists/john-users/
