### ISSUE TITLE
hdaa fails OpenMP code path (--enable-openmp-for-fast-formats)

### ISSUE THREAD

**Issue by claudioandre-br** [magnumripper/JohnTheRipper#3752] opened 2019-04-04 15:59 UTC
```
../run/john --test-full=0 --format=cpu
[....]
Testing: hdaa, HTTP Digest access authentication [MD5 128/128 AVX 4x3]... (2xOMP) FAILED (cmp_all(6144))
```

**Comment by magnumripper** [comment] 2019-04-07 21:44
Dupe of #3107. I may fix it before release, or possibly I'll just disable OpenMP for it, we'll see

**Closed by magnumripper** 2019-04-07 21:44 UTC
Labels: bug
