### ISSUE TITLE
JTR Not ? 

### ISSUE THREAD

**Issue by Rdgeno** [magnumripper/JohnTheRipper#4163] opened 2019-11-24 00:27 UTC
John is in the newest version.
I followed the directions in the install with John both the regular and Windows specific. 
I also used this tutorial to install Cygwin.

https://openwall.info/wiki/john/tutorials/win64-howto-build 

I edited the outputs for space, also I have a AMD RX 560 GPU and Intel i7 3700 with the newest Intel Opencl and newest AMD drivers. Running John on Windows 10 Home Up to date, using Cygwin, just installed up to date.

./pass_gen.pl -tstall

All formats were able to be run (458 total formats). All CPAN modules installed

./john --test=0
Device 1: pthread-Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz

./john --test

Device 1: pthread-Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Benchmarking: sha1crypt-opencl, (NetBSD) [PBKDF1-SHA1 OpenCL 8x]... \

./john --list=opencl-devices

 ./john --list=opencl-devices
Platform #0 name: Portable Computing Language, version: OpenCL 1.2 pocl 1.3 RelWithDebInfo+Asserts, LLVM 8.0.1, SPIR, SLEEF, POCL_DEBUG
    Device #0 (1) name:     pthread-Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
    Device vendor:          GenuineIntel
    Device type:            CPU (LE)
    Device version:         OpenCL 1.2 pocl HSTR: pthread-x86_64-unknown-windows-cygnus-bdver2
    Driver version:         1.3
    Native vector widths:   char 16, short 16, int 8, long 4
    Preferred vector width: char 16, short 16, int 8, long 4
    Global Memory:          16908 MB
    Global Memory Cache:    8 MB
    Local Memory:           4 MB (Global)
    Constant Buffer size:   4 MB
    Max memory alloc. size: 8 GB
    Max clock (MHz):        3392
    Profiling timer res.:   1 ns
    Max Work Group Size:    4096
    Parallel compute cores: 8
    Speed index:            108544

(No GPU)

./configure LDFLAGS=-L/opt/AMDAPP/lib CFLAGS=-I/opt/AMDAPP/include

Target CPU ................................. x86_64 AVX, 64-bit LE
AES-NI support ............................. run-time detection
Target OS .................................. cygwin
Cross compiling ............................ no
Legacy arch header ......................... x86-64.h

Optional libraries/features found:
Memory map (share/page large files) ........ yes
Fork support ............................... yes
OpenMP support ............................. yes (not for fast formats)
OpenCL support ............................. yes
Generic crypt(3) format .................... yes
libgmp (PRINCE mode and faster SRP formats)  yes
128-bit integer (faster PRINCE mode) ....... yes
libz (pkzip and some other formats) ........ yes
libbz2 (gpg2john extra decompression logic)  yes
libpcap (vncpcap2john and SIPdump) ......... no
OpenMPI support (default disabled) ......... no
ZTEX USB-FPGA module 1.15y support ......... no

Install missing libraries to get any needed features that were omitted.

Configure finished.  Now "make -s clean && make -sj4" to compile.

 make -sj4

$ make -sj4
ar: creating aes.a
ar: creating secp256k1.a
ar: creating ed25519-donna.a
Securing executables.
Warning: setting dynbase on file with no relocation info (../run/john.exe).
Warning: setting dynbase on file with no relocation info (../run/unshadow.exe).
Warning: setting dynbase on file with no relocation info (../run/unafs.exe).
Warning: setting dynbase on file with no relocation info (../run/unique.exe).
Warning: setting dynbase on file with no relocation info (../run/undrop.exe).
Warning: setting dynbase on file with no relocation info (../run/rar2john.exe).
Warning: setting dynbase on file with no relocation info (../run/zip2john.exe).
Warning: setting dynbase on file with no relocation info (../run/genmkvpwd.exe).
Warning: setting dynbase on file with no relocation info (../run/mkvcalcproba.exe).
Warning: setting dynbase on file with no relocation info (../run/calc_stat.exe).
Warning: setting dynbase on file with no relocation info (../run/tgtsnarf.exe).
Warning: setting dynbase on file with no relocation info (../run/racf2john.exe).
Warning: setting dynbase on file with no relocation info (../run/hccap2john.exe).
Warning: setting dynbase on file with no relocation info (../run/raw2dyna.exe).
Warning: setting dynbase on file with no relocation info (../run/keepass2john.exe).
Warning: setting dynbase on file with no relocation info (../run/bitlocker2john.exe).
Warning: setting dynbase on file with no relocation info (../run/dmg2john.exe).
Warning: setting dynbase on file with no relocation info (../run/putty2john.exe).
Warning: setting dynbase on file with no relocation info (../run/uaf2john.exe).
Warning: setting dynbase on file with no relocation info (../run/wpapcap2john.exe).
Warning: setting dynbase on file with no relocation info (../run/gpg2john.exe).
Warning: setting dynbase on file with no relocation info (../run/cprepair.exe).
Warning: setting dynbase on file with no relocation info (../run/base64conv.exe).

Make process completed.

Or:

 make -s clean && make -sj4
ar: creating aes.a
ar: creating secp256k1.a
ar: creating ed25519-donna.a
Securing executables.
Warning: setting dynbase on file with no relocation info (../run/john.exe).
Warning: setting dynbase on file with no relocation info (../run/unshadow.exe).
Warning: setting dynbase on file with no relocation info (../run/unafs.exe).
Warning: setting dynbase on file with no relocation info (../run/unique.exe).
Warning: setting dynbase on file with no relocation info (../run/undrop.exe).
Warning: setting dynbase on file with no relocation info (../run/rar2john.exe).
Warning: setting dynbase on file with no relocation info (../run/zip2john.exe).
Warning: setting dynbase on file with no relocation info (../run/genmkvpwd.exe).
Warning: setting dynbase on file with no relocation info (../run/mkvcalcproba.exe).
Warning: setting dynbase on file with no relocation info (../run/calc_stat.exe).
Warning: setting dynbase on file with no relocation info (../run/tgtsnarf.exe).
Warning: setting dynbase on file with no relocation info (../run/racf2john.exe).
Warning: setting dynbase on file with no relocation info (../run/hccap2john.exe).
Warning: setting dynbase on file with no relocation info (../run/raw2dyna.exe).
Warning: setting dynbase on file with no relocation info (../run/keepass2john.exe).
Warning: setting dynbase on file with no relocation info (../run/bitlocker2john.exe).
Warning: setting dynbase on file with no relocation info (../run/dmg2john.exe).
Warning: setting dynbase on file with no relocation info (../run/putty2john.exe).
Warning: setting dynbase on file with no relocation info (../run/uaf2john.exe).
Warning: setting dynbase on file with no relocation info (../run/wpapcap2john.exe).
Warning: setting dynbase on file with no relocation info (../run/gpg2john.exe).
Warning: setting dynbase on file with no relocation info (../run/cprepair.exe).
Warning: setting dynbase on file with no relocation info (../run/base64conv.exe).

Make process completed.

No matter what I do I can't fix that.

./john --test runs perfect
./john --test=0 runs perfect.

updatedb && locate CL/cl.h && locate libOpenCL.so (Everything shows as access denied.)

Prior to running the above command I was getting.

 ./john --format=wpapsk-opencl ARRIS2-JTR
Device 1: pthread-Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Using default input encoding: UTF-8
Loaded 1 password hash (wpapsk-opencl, WPA/WPA2/PMF/PMKID PSK [PBKDF2-SHA1 OpenCL])
/

Now I get this.

./john --format=wpapsk-opencl ARRIS2-JTR
Device 1: pthread-Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Using default input encoding: UTF-8
Loaded 1 password hash (wpapsk-opencl, WPA/WPA2/PMF/PMKID PSK [PBKDF2-SHA1 OpenCL])
pocl error: lt_dlopen("(null)") or lt_dlsym() failed with 'Access is denied.'.
note: missing symbols in the kernel binary might be reported as 'file not found' errors.
Aborted (core dumped)

I can't get it to see my GPU it's not using the Opencl and now when it runs without Opencl it's like this.

 ./john --format=wpapsk ARRIS2-JTR
Using default input encoding: UTF-8
Loaded 1 password hash (wpapsk, WPA/WPA2/PMF/PMKID PSK [PBKDF2-SHA1 128/128 AVX 4x])
Will run 8 OpenMP threads
kNote: Minimum length forced to 8 by format
Proceeding with single, rules:Single
Crash recovery file is locked: ./john.rec

It wouldn't let me run ./john --format=wpapsk-pmk-opencl or without opencl.

Now this is happening, notice the speed.

 ./john --format=wpapsk ARRIS2-JTR
Using default input encoding: UTF-8
Loaded 1 password hash (wpapsk, WPA/WPA2/PMF/PMKID PSK [PBKDF2-SHA1 128/128 AVX 4x])
Will run 8 OpenMP threads
Note: Minimum length forced to 8 by format
Proceeding with single, rules:Single
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:04 13.81% 1/3 (ETA: 18:58:08) 0g/s 102.7p/s 102.7c/s 102.7C/s att68763g3e0b70a9bcd80x..ae0b70a9bcd80$
Almost done: Processing the remaining buffered candidate passwords, if any.
Proceeding with wordlist:./password.lst
Proceeding with incremental:ASCII
0g 0:00:13:28  3/3 0g/s 93.56p/s 93.56c/s 93.56C/s pinatina..pichola1

If I posted this in the wrong place I'm sorry, I figured it's an issue since it is happening with the John install directions. I have found similar issues posted and discussed on Github, unfortunately no answer that would work. It passes all tests as I have shown above, but doesn't find the GPU and wont run the Opencl it starts to run the Opencl device then nothing the command prompt is back. If you follow the Opencl instructions everything starts erroring.  I downloaded and installed it several times. If I leave out ./configure LDFLAGS=-L/opt/AMDAPP/lib CFLAGS=-I/opt/AMDAPP/include, it will run until the command is added. I got that from the John file also. Sorry again if this isn't the right place I'm not asking for help just reporting.

**Comment by claudioandre-br** [comment] 2019-11-24 01:33
> Warning: setting dynbase on file with no relocation info (../run/base64conv.exe).
> [...]
> No matter what I do I can't fix that.

This is ok. Just a warning.
***

I would say:
* you only have POCL installed. No AMD OpenCL drivers and no Intel OpenCL drivers. 
* I see nothing wrong in JtR itself.

Although this issue is worded as a bug report, not as a question, I'm afraid you're mistaken.

We assume you are genuinely thinking you are reporting a real bug to help the project. That said, please:
- try to make your point clearer;
- are you really sure you have OpenCL drivers installed?
- if you need support as an end-user, ask for help on the mailing list john-users at lists.openwall.com (but first see the archives at http://www.openwall.com/lists/john-users/ and make sure you set a descriptive message Subject when you post).

**Comment by claudioandre-br** [comment] 2019-11-24 01:35
BTW: you can/should test your environment using the "official" JtR package. It works (usually, sometimes, at least) out of the box.

**Comment by claudioandre-br** [comment] 2019-11-24 01:47
> ./configure LDFLAGS=-L/opt/AMDAPP/lib CFLAGS=-I/opt/AMDAPP/include

On Windows? I would run a:
```
./configure
make -s clean && make -sj4
```

Only if the above fails, I would try something more "sophisticated".

**Comment by Rdgeno** [comment] 2019-11-24 02:02
Yeah I have the Intel opencl installed and the AMD Radion. Thank you for your reply. If you look at the github I dont know what happened I'm in the process of uninstalling Cygwin right now so I can at least start fresh tomorrow been at it with it since 7am its 9pm now. I really appreciate you responding especially so fast. I'm going to try everything you said and I'll let you know how it goes. I tried signing up for open wall it wont send the conformation email. You have a great day night whatever it is where you are and I just want to thank you again.RobertSent from my Metro By T-Mobile 4G LTE Android Device
-------- Original message --------From: Claudio André <notifications@github.com> Date: 11/23/19  8:33 PM  (GMT-05:00) To: magnumripper/JohnTheRipper <JohnTheRipper@noreply.github.com> Cc: Rdgeno <robertde12e@gmail.com>, Author <author@noreply.github.com> Subject: Re: [magnumripper/JohnTheRipper] JTR Not ?  (#4163) 
Warning: setting dynbase on file with no relocation info (../run/base64conv.exe).
[...]
No matter what I do I can't fix that.

This is ok. Just a warning.

I would say:

you only have POCL installed. No AMD OpenCL drivers and no Intel OpenCL drivers.
I see nothing wrong in JtR itself.

Although this issue is worded as a bug report, not as a question, I'm afraid you're mistaken.
We assume you are genuinely thinking you are reporting a real bug to help the project. That said, please:

try to make your point clearer;
are you really sure you have OpenCL drivers installed?
if you need support as an end-user, ask for help on the mailing list john-users at lists.openwall.com (but first see the archives at http://www.openwall.com/lists/john-users/ and make sure you set a descriptive message Subject when you post).


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/magnumripper/JohnTheRipper/issues/4163?email_source=notifications\u0026email_token=AM53IOJMRLWCXBBPDBWDNXTQVHKWPA5CNFSM4JQ4SU32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFABSJA#issuecomment-557848868",
"url": "https://github.com/magnumripper/JohnTheRipper/issues/4163?email_source=notifications\u0026email_token=AM53IOJMRLWCXBBPDBWDNXTQVHKWPA5CNFSM4JQ4SU32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFABSJA#issuecomment-557848868",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by solardiz** [comment] 2019-11-24 14:43
@Rdgeno This is definitely a john-users and not a GitHub matter. Can you try subscribing to john-users again? Have you checked your spam folder for the confirmation message?

**Comment by Rdgeno** [comment] 2019-11-24 16:23
I got it and thank you after the time I was having with john I didn't even
think to check the spam. Thanks again and sorry again.
Robert

**Comment by claudioandre-br** [comment] 2019-11-24 17:25
Bug closed as:

* **ExternalDependency** - We can't do much. Windows + CygWin + Drivers related.

* **Invalid** - Illegible, spam, NOT a bug, etc.;

**Closed by claudioandre-br** 2019-11-24 17:25 UTC
Labels: invalid
